### ISSUE TITLE
Is it still alive?

### ISSUE THREAD

**Issue by lanzorg** [Roemer/FlaUI#1]
Is the development dead?
Are you going to create a nuget package?

**Comment by Roemer** [comment]
No it's not dead. I spent a lot of time into research. The main "problem" is, that the underlying UIA3 library is missing many features for WinForms applications that were supported with the older UIA2 (which itself has many problems with WPF).
I'm still not sure yet if I am going to just fully support everything UIA3 does or if I will add another abstraction layer to also support UIA2 or even MSAA.
My current thinking is that I'll only go with UIA3 and therefore full WPF support and only limited WinForms support.
NuGet packages are planned as well.

**Comment by Roemer** [comment]
As you see, development continued so I'll close this :)
