### ISSUE TITLE
Accessing Elements in a Virtualized ListBox

### ISSUE THREAD

**Issue by james1301** [Roemer/FlaUI#100]
Hi, I have a virtualized ListBox. How I am I meant to access an element that isn't currently visible?

**Comment by Roemer** [comment]
What kind of patterns do you have available on your listbox? One way is to use the itemcontainerpattern (if available) and realize all items. There is a helper (ItemRealizer) which does this.

**Comment by james1301** [comment]
Yeah I have used the ItemContainerPattern like this:

`        private SHListItem[] _items;

        public SHListItem[] Items
        {
            get
            {
                if (_items == null)
                {
                    var element = FindFirstDescendant().Patterns.ItemContainer.Pattern.FindItemByProperty(null, null, null);

                    while (element != null)
                    {
                        RealizeIfNeeded(element);
                        element = FindFirstDescendant().Patterns.ItemContainer.Pattern.FindItemByProperty(element, null, null);
                    }

                    _items = this.FindFirstDescendant().FindAllChildren(cf => cf.ByControlType(ControlType.ListItem)).Select(li => li.AsListItem()).ToArray();
                }

                return _items;
            }
        }`

But just seems quite inefficient. I will take a look at the item realizer.

Is there a way to see whether the ListBox is virtualized? And conditionally virtualize until you get the right item? I am a little confused what you can pass into the FindItemByProperty, to find the correct item.  Do you have an example of passing in a propertyid and value?

**Comment by Roemer** [comment]
There is not that much beside that.
If you have a GridPattern, you could get items by index.
To use the FindItemByProperty, you can use it like: `var itemWithName = Patterns.ItemContainer.Pattern.FindItemByProperty(this, Automation.PropertyLibrary.Element.Name, "Some Value");`

**Comment by ivan-danilov** [comment]
@james1301 in theory, these `null, null, null` you pass to the `FindItemByProperty` allow you to specify condition on the element you need, and it is calculated without realization on the UIA server side. Meaning that if you have a million elements, and one in the middle satisfies your condition - you will get it without realizing 500'000 elements.

**Comment by Roemer** [comment]
Yes, the first is the element where you want to start from (null if you want to start from the top of the list), the second a property you want to search a value for and the last one the value you want to search. Unfortunately you cannot search for multiple properties without getting thru the items.

**Comment by james1301** [comment]
Ahhh I see. So name basically just seems to be the class name? I cannot see a way to get to get to an actual property name?

I guess I would have to realize the item to then check.

**Comment by Roemer** [comment]
I suspecty by "actual property" name you mean some property of your class in your application. Nope that is not possible (except you create a custom UIA property / AutomationPeer to expose your custom property). The properties I am talking about are the [UI Automation properties](https://docs.microsoft.com/en-us/dotnet/framework/ui-automation/ui-automation-properties-overview).

**Comment by james1301** [comment]
Yeah cool thanks for the info, so basically there isn't a good way to find the right item to virtualize is there?

So I've basically changed it to this:

`        public SHListItem GetItem(string text, string textAutomationElementId = null)
        {
            var item = Items.Where(i => i.GetText(textAutomationElementId) == text).FirstOrDefault();

            if (item != null)
                return item;

            var element = FindFirstDescendant().Patterns.ItemContainer.Pattern.FindItemByProperty(null, null, null);

            while (element != null && item == null)
            {
                RealizeIfNeeded(element);
                element = FindFirstDescendant().Patterns.ItemContainer.Pattern.FindItemByProperty(element, null, null);
                item = Items.Where(i => i.GetText(textAutomationElementId) == text).FirstOrDefault();

                if (item != null)
                    return item;
            }

            return null;
        }`

**Comment by Roemer** [comment]
What does the `GetText` do? Only return the name or the value? If so, you could use that as property in `FindItemByProperty`.

**Comment by james1301** [comment]
The GetText is something I've built onto my SHListItem type, it works on the actual virtualized item, so won't work at that level. This is maybe the best I can do.

Thanks for your help.

**Comment by Roemer** [comment]
Glad I could help. A few optimization possibilities exist althou in your code:
1. You can save the ItemContainerPattern in a variable so you do not need to get it again in each loop
2. Instead of searching thru all `Items` again just check to element for the text in your loop
That would save a lot of UIA calls.

**Comment by james1301** [comment]
Cool thanks.
