### ISSUE TITLE
Wildcards when searching for controls

### ISSUE THREAD

**Issue by dbtfsbre** [Roemer/FlaUI#106]
Hi, is it possible to use wildcards when searching for controls by partial name?

**Comment by dbtfsbre** [comment]
I.e. in FlaUI.Core.AutomationElements.TitleBar, there is a MaximizeButton with "Maximize" as AutomationId. But the AutomationId of the maximize button is "Maximize-Restore" for Notepad on Windows 10. It does not find the button.

Would it be possible to use a wildcard there?

**Comment by Roemer** [comment]
Wildcards are not supported by the UIA framework.
What you can do is get all Buttons `TitleBar.FindAllChildren(cf => cf.ByControlType(ControlType.Button))` and then use normal C# to search for that element in the list (eg. `elements.Where(e => e.AutomationId.StartsWith("Maximize"))`).
Another way would be to extend the TitleBar class to search for this additional AutomationId and create a PR for that :)

**Comment by dbtfsbre** [comment]
@Roemer Good to know that partial match is not supported. The performance of UIA should be high enough to allow searching through the list of all elements. I need to test this for a while.

**Comment by Roemer** [comment]
Can we close this issue?
