### ISSUE TITLE
Wait.UntilInputIsProcessed() enhancement

### ISSUE THREAD

**Issue by marcelo-maciel** [Roemer/FlaUI#107]
I see that this method has an TODO

public static void UntilInputIsProcessed()
        {
            // Let the thread some time to process the system's hardware input queue.
            // For details see this post: http://blogs.msdn.com/b/oldnewthing/archive/2014/02/13/10499047.aspx
            // TODO: Should this be configurable?
            Thread.Sleep(100);
        }

I think TestStack.White has a good approach as starting point, with an optional parameter then:

public static void UntilInputIsProcessed(int millisecondsToWait = 100)
        {
            // Let the thread some time to process the system's hardware input queue.
            // For details see this post: http://blogs.msdn.com/b/oldnewthing/archive/2014/02/13/10499047.aspx
            // TODO: Should this be configurable?
            Thread.Sleep(millisecondsToWait);
        }

If you like, i can send a PR.
After, we can think of a better solution.

**Comment by Roemer** [comment]
Yes, why not :)

**Comment by Roemer** [comment]
PR merged.
