### ISSUE TITLE
Label should be invokeable (clickable)

### ISSUE THREAD

**Issue by danhi** [Roemer/FlaUI#110]
It's possible to handle a click event for a label, which can be quite useful.  But the FlaUI Label doesn't have an invoke routine.

**Comment by Roemer** [comment]
Invoke is really an "Invoke" from the InvokePattern. Labels do not support that pattern. But you should be able to use `Click()`.

**Comment by danhi** [comment]
Sorry, thought I'd looked for that, but guess I hadn't.

**Comment by Roemer** [comment]
Does it work and can we close this issue?

**Comment by danhi** [comment]
Sorry, I thought I had used the comment and close button on my last reply.  I just closed it.
