### ISSUE TITLE
Can't clear selection from Listview

### ISSUE THREAD

**Issue by danhi** [Roemer/FlaUI#114]
the listview doesn't have a clear member, and the remove member requires a row index which you can't get from the gridrow returned from selected item.

**Comment by danhi** [comment]
Any thoughts on this?

**Comment by Roemer** [comment]
Does the item support a SelectionItemPattern?

**Comment by danhi** [comment]
So I tried to use IsPatternSupported, which says it takes a PatternId, but that class doesn't have any members to use.  How is this call supposed to work?

**Comment by HyruleWarrior** [comment]
You can call <AutomationElement>.Patterns.SelectionItem.IsSupported on your ListView. Another way to check is to use FlauInspect and check your ListView with it. It lists out all the patterns and if the element supports them or not.

**Comment by danhi** [comment]
Thanks. I'll try that.

Sent from my android device.

-----Original Message-----

**Comment by danhi** [comment]
So I get the listview as a grid, as there isn't a AsListview, then .Patterns.SelectionItem.IsSupported returns false.

**Comment by maxinfet** [comment]
Could you provide a screenshot from FlaUI Inspect of the control?

**Comment by danhi** [comment]
![listview](https://user-images.githubusercontent.com/3358389/32700811-99826eb0-c787-11e7-9fe4-b1db1b20ad57.jpg)
It shows as a list, but there isn't an AsList.  Using AsGrid works, but doesn't give me the SelectedPattern.

**Comment by Roemer** [comment]
The SelectionItem pattern should be available on the items inside the list. Can you check that? You should then be able to call `RemoveFromSelection()` on all children.

**Comment by danhi** [comment]
So that does work, but I have to iterate over all the rows, finding the selected ones and then removing them from the selection.  It would be nice to implement the clear function. But this works, so ...
