### ISSUE TITLE
Serialization example

### ISSUE THREAD

**Issue by mudi77** [Roemer/FlaUI#115]
I'd like to see whether it is possible to store elements from library into HD (e.g. AutomationElement) and reconstruct that objects by serialize and deserialize or another way how can be "sharing" achieved ?

**Comment by Roemer** [comment]
I'm not sure if that makes sense at all. An AutomationElement is bound the the "Window-Handle" of the corresponding window (or control). If the window is destroyed, the handle is invalid. So when you open an application, somehow serialize/store the window, close the application, reopen it, then you cannot reuse the serialized window object as it is a different one.

**Comment by Roemer** [comment]
Do you still need more information or is that fine for you?

**Comment by Roemer** [comment]
Closed due to inactivity. Please reopen if you have something to add.
