### ISSUE TITLE
How increase performance of test execution

### ISSUE THREAD

**Issue by pedroNew** [Roemer/FlaUI#118]
Hi. 
I have comparison of executing simple test by FlaUI and TestComplete (clicking button found on ribbon's tab) - TestComplete is much quicker (2.3 s by FlaUI and 1.3 s by TestComplere). How can I increase FlaUI performance? 

My method is really as far is really simple but I'm afraid of performing larger tests (working with grids) can be hard.

I have this kind of searching implemented:

```csharp
private Ribbon GetRibbon(TreeScope scope) {
    return FindFirst(scope, ConditionFactory.ByControlType(Ribbon.RibbonControleType)
        .And(ConditionFactory.ByName(Ribbon.RibbonName))).AsRibbon();
}

public Dictionary<string, IEnumerable<Button>> GetOperationsInSelectedModule3() {
    return FindFirstChild(cf => cf.ByControlType(ControlType.Pane))
        .FindFirstChild()
        .FindAllChildren()
        .ToDictionary(e => e.Name, e => e.FindAllChildren()
            .Select(cc => cc.AsButton()));
}
```

What am I doing wrong?

**Comment by Roemer** [comment]
One problem I see is the `GetOperationsInSelectedModule3` method as it could need many interop communications to work. You have 1xFindFirstChild, 1xFindFirstChild, 1xFindAllChildren, for each children .Name and again FindAllChildren. You should consider using [Caching](https://github.com/Roemer/FlaUI/wiki/Caching) here if you really need all that (and especially cache the result in a variable in your code).

The second thing is in your `GetRibbon`. You use parameter for `TreeScope`. If you use `Descentands` this can take way longer as it has to traverse the whole tree until it finds the first match. It's always better to use child and navigate the tree on your own (or by using XPath).

Working with grids is not a problem at all (we do have several 100 tests with fairly complex UIs). It all depens on correctly finding what you need and using `TreeScope.Children` as much as possible.

**Comment by pedroNew** [comment]
Thx! I'll try to use Children scope.
About Caching? It's not clear for me how deal with it. Maybe you have more complex examples?
