### ISSUE TITLE
How deal with not supported control type

### ISSUE THREAD

**Issue by pedroNew** [Roemer/FlaUI#119]
Hi,

I have app with structure as below:
![notsupported](https://user-images.githubusercontent.com/23615869/32938627-1a95abe0-cb7d-11e7-8674-93c48ed092b4.png)
I have grid, cells are supported but I can't find rows. What can  I do with it?

**Comment by Roemer** [comment]
There is a bug in FlaUInspect which has problems when the control type is not supported. Can you try the current nightly of flauinspect (https://ci.appveyor.com/api/buildjobs/pqybbovudd4kqr2r/artifacts/Artefacts%2FFlaUInspect-1.2.0.zip)?
Also if the ControlType is not supported, you should use other fields to find the control (eg. Name or AutomationId),

**Comment by pedroNew** [comment]
On this build of FlaUIInspect this controles are classified as 'Custom' :) :+1: 
Ok, thx for advices. 
Issue to close
