### ISSUE TITLE
How close Pane control?

### ISSUE THREAD

**Issue by pedroNew** [Roemer/FlaUI#120]
Hi,

My pane control in my application has close button but I can't locate it by FlaUI. Any ideas how I can close pane?

Best regards,
P.

**Comment by maxinfet** [comment]
Could you provide a screen shot of inspect so that we can see what the tree structure of the application looks like. Also could you add some code what for what you have tried so far?

**Comment by pedroNew** [comment]
![untitled](https://user-images.githubusercontent.com/23615869/33457242-2a2ec41a-d622-11e7-81cb-58fab51d9b3f.png)
What I've tried so far? There is no any UI element founded by FlaUI to deal with (as you can see on the screenshot, this (x) button isn't visible in app structure presented by FlaUIInspect) - co there is nothing to show. Now I'm using ugly hacks - closing this tab by keyboard shortcuts. But I think I can more rely on clicking on object.

**Comment by Roemer** [comment]
This x-button seems to be rendered by a custom ui control/library. If this library do not expose this (x) as a UIA control, it gets hard. If it is WPF, you could try creating your own AutomationPeer for this control, another workaround would be to just calculate the position of this (x) based on the position of your pane (should be pretty static I guess) and just click that location.

**Comment by pedroNew** [comment]
Unfortunately it's WinForms app (based on DevExpress libraries). The only solution is calculate relative position as you mentioned. Thx for advices. I'm closing issue
