### ISSUE TITLE
WinForm app and Menu

### ISSUE THREAD

**Issue by tilentur** [Roemer/FlaUI#122]
Hi,

I have a simple windows app - windows forms, .Net 4 in c#

I'm trying to implement clicking on a menu and once i expand/click the first menu item, I can not click on the second one ..

Here is the code

```
windows.FindFirstByXPath("/MenuBar/MenuItem[@Name='File']").AsMenuItem().Expand(); // menu is succesfuly expanded
windows.FindFirstByXPath("/MenuBar/MenuItem/MenuItem[@Name='Add']").AsMenuItem().Click(); // no cigar
```

**Comment by Roemer** [comment]
I do have some logic which should help when using menues. Can you try using the `Menu` class? See the example here: https://github.com/Roemer/FlaUI/wiki/Menu
Otherwise could you provide a sample application?

**Comment by Roemer** [comment]
Is it working now?

**Comment by tilentur** [comment]
I had to use a diferent approach ... (down and dirty :wink:)

`
var Automation = new UIA2Automation();
var window = app.GetMainWindow(Automation);
var menu = window.FindFirstChild(cf => cf.Menu()).AsMenu();
var edit = menu.Items["File"];
edit.Click();

var addBridge = edit.FindFirstChild(cf => cf.Menu()).AsMenu().Items["Add Bridge..."];
addBridge.Click();
`

Structure is a
![capture](https://user-images.githubusercontent.com/32763634/35279935-dae9387a-004e-11e8-83ee-d815e2ccd266.PNG)

**Comment by Roemer** [comment]
Cool thanks for the feedback. Glad it works.
