### ISSUE TITLE
The value property returns null for the dataItem inside a DataGridView 

### ISSUE THREAD

**Issue by ArunaBalasubramanian** [Roemer/FlaUI#123]
Hi @Roemer ,

I have been facing issue with a specific DataGridView that returns null on the dataItem. Could you please suggest as how to pull the value for this specific DataItem?
![datagrid](https://user-images.githubusercontent.com/24669266/33871022-af2a6b48-df36-11e7-8398-a6194f08969b.png)

**Comment by Roemer** [comment]
Are you using a control library and if so, which one? It seems to me that the text information is not correctly provided to Microsoft UIA (and therefore also to FlaUI),

**Comment by Roemer** [comment]
Can you provide some more information?

**Comment by ArunaBalasubramanian** [comment]
@Roemer - The control is datagrid only, however the values inside are painted rather than being assigned to a DataGridCell. Is there any alternative to pull such value?

**Comment by Roemer** [comment]
Theres several possibilities:
- Use the `Capture` class and compare the images if it is for a test
- Assign the value to the cell but manually paint it
- Create your own / extended `AutomationPeer` to provide the value to UIA.
