### ISSUE TITLE
Get all button in an application window

### ISSUE THREAD

**Issue by davishoang96** [Roemer/FlaUI#125]
Hi Roemer, 

I did try TestStack to get all button from a windows WPF form. Here is my code:

To get all button in the application window.
```csharp
TestStack.White.UIItems.IUIItem[] listitem = MainWindow.GetMultiple(SearchCriteria.ByControlType(ControlType.Button));

int i = 0;
foreach(TestStack.White.UIItems.UIItem item in listitem)
{
    Console.WriteLine(i + " - " + item);
    i++;
}
```

Is there any way I can get all button in FlaUI framework?

**Comment by Roemer** [comment]
If you only need to find the child buttons, you can use
```csharp
window.FindAllChildren(cf =>cf.ByControlType(ControlType.Button));
```
If you need absolute all buttons, you can use
```csharp
window.FindAllDescendants(cf =>cf.ByControlType(ControlType.Button));
```

**Comment by davishoang96** [comment]
Happy New Year :) 

Thanks for the guidance, I was able to create a foreach loop to print all Button to the Console. Is there any way that I can put FrameworkType to the conditionfactory? By doing this, I can spy all UI element that exists on an AUT.

**Comment by Roemer** [comment]
Thanks, same to you.
You can use any property as conditions. For example:
```csharp
child.FindFirstChild(new PropertyCondition(Automation.PropertyLibrary.Element.FrameworkId, "WPF"));
```
