### ISSUE TITLE
Getting main window takes lots of time to complete > 30 sec

### ISSUE THREAD

**Issue by godrose** [Roemer/FlaUI#126]
I'm trying to get the main window using the library facilities and following the sample
However the following lines just take forever to complete and yield the main window:

```csharp
using (var automation = new UIA3Automation())
{
    var mainWindow = app.GetMainWindow(automation);
    if (mainWindow == null || mainWindow.IsOffscreen || mainWindow.IsEnabled == false)
    {
        throw new Exception();
    }
    return mainWindow;
}
```

I'm running in Windows 10 FCU and latest versions of UWP and associated packages.
The test projects use 4.6.1 version and SpecFlow with xUnit 2.1.0

Just to clarify. I start the app from its deployment location.

**Comment by godrose** [comment]
Just to clarify. I start the app from its deployment location.

**Comment by godrose** [comment]
@Roemer

**Comment by Roemer** [comment]
Is your application hanging like an initializating or something? Also could you try debug thru the code to see where exactly it hangs?

**Comment by godrose** [comment]
Thanks for the reply. It's initializing Ok. The test hangs on the GetMainWindow line

**Comment by Roemer** [comment]
Can you step into the flaui code to see where it hangs inside there?

**Comment by godrose** [comment]
I'm using the nuget package so not really. Unless you publish the symbols as well.
Of course I can compile the source code and perform a smoke test...

**Comment by godrose** [comment]
This is the app that I test:
https://github.com/LogoFX/Samples.Universal

**Comment by Roemer** [comment]
There are symbol packages available in appveyor: https://ci.appveyor.com/project/RomanBaeriswyl/flaui/build/artifacts

**Comment by Roemer** [comment]
Is the app supposed to just be a blue window with a gray cross/border in the middle?

**Comment by godrose** [comment]
No. It's supposed to present two simple text boxes and a button

**Comment by godrose** [comment]
@Roemer How exactly can I consume these packages. I've added them as the symbol sources but stepping in doesn't result in opening the source code...

**Comment by godrose** [comment]
@Roemer It's stuck in this line:
`return _process.MainWindowHandle == IntPtr.Zero;`
because the Main Window Handle never seems to be anything but zero

**Comment by Roemer** [comment]
WPF / Universal Apps tend to not use many window handles, so it might be safer to use the Desktop element and find the appropriate window by process id from there.
Regarding the second issue: what is the condition you're using to search?

**Comment by godrose** [comment]
1. I didn't get the first note. Is there any code example to demonstrate
that?
2. An automation id. It's defined in the first text box. You can find it in
Login view

**Comment by Roemer** [comment]
Have a look at the `GetAllTopLevelWindows` in `Application`. You can try using that one or write your own method which searches for a window on the desktop by name.

**Comment by godrose** [comment]
Ok. What about the automation id issue?

**Comment by Roemer** [comment]
May be related. YOu're probably searching on the wrong "main window". Try finding the correct one with the Desktop method I wrote above and then search on that window.

**Comment by godrose** [comment]
`GetAllTopLevelWindows` returns empty array

**Comment by godrose** [comment]
It's very unstable. Sometimes the `GetMainWindow` hangs, sometimes not. Sometimes it returns window with FrameworkId Set to Win32, sometimes to XAML.
Very indeterministic.

**Comment by Roemer** [comment]
I think the problem is that you have the wrong process. UWP apps have some kind of launcher (that's the one you have) which launch another process (the real one). I guess we need to find a reliable way to get the correct process for an UWP app.

**Comment by godrose** [comment]
I think I found one. It finally begins to work )

**Comment by godrose** [comment]
@Roemer Thanks for the assistance!

**Comment by Roemer** [comment]
Do you mind posting a quick recap on what you did now to fix it?

**Comment by godrose** [comment]
@Roemer I'm using the following code. It doesn't always work; most of the times it does.
`
var processes = System.Diagnostics.Process.GetProcesses();
            var appFrameHost = processes.FirstOrDefault(t => t.ProcessName.Contains("ApplicationFrameHost"));            
            Application.LaunchStoreApp(startupPath);
            ApplicationContext.Application =  Application.Attach(appFrameHost);
            ApplicationContext.Application.WaitWhileBusy();
`

**Comment by jordanbee1992** [comment]
Having the exact same issue. Also on .NET 4.6.1, so will try on later version. Godrose's mitigation works about 50% of the time.
