### ISSUE TITLE
Can FlaUI run in Java?

### ISSUE THREAD

**Issue by coolalexhuang** [Roemer/FlaUI#127]
Hi Roemer, as most of our projects are built in Java, can FlaUI run in Java project?

**Comment by Roemer** [comment]
Depends on what UI Framework you're using. You can try inspecting it with any Inspect tool (like FlaUInspect). Whatever you see there can be automated with FlaUI.

**Comment by maxinfet** [comment]
Did you mean "Can I use the FlaUI dlls from Java?" or did you mean "Can I automate a Java UI using FlaUI?"

**Comment by coolalexhuang** [comment]
@Roemer @maxinfet , I apologize to make you confused, my question is "Can I use the FlaUI dlls from Java?", if not, do you know any other libraries can do it?

**Comment by maxinfet** [comment]
In theory you should be able to consume the FlaUI dll from Java. I am not familiar with how Java interop with managed .Net dlls works but it seems like their are some libraries to help with that. https://stackoverflow.com/questions/10743715/how-to-call-into-net-dll-from-java

**Comment by Roemer** [comment]
@maxinfet Sure, the wrappers could be in an own project probably. Although I'm not sure how much overhead it is to maintain them.

**Comment by Roemer** [comment]
Closed due to inactivity.
