### ISSUE TITLE
Does FlaUI support Firefox?

### ISSUE THREAD

**Issue by gaoming1977** [Roemer/FlaUI#130]
Hi, Roemer and FlaUI contributers,
I just contact the UIA weeks before. Thanks for your great work. 
Does FlaUI support Firefox or any plan to support? It seems it support both IE and Chrome although some extra configuration needed. 
More, it seems the UIA3 support IE web page with some performance issue. How to enhance or optimize? 
Thanks,

**Comment by Roemer** [comment]
Hi
FlaUI supports Firefox partially, as Firefox only partially supports the underlying technology `Microsoft UI Automation`. Best is if you quickly try what you want. Same goes for Chrome and IE.
If you do want to test websites (and not the browser itself life creating/closing tabs, using the menu, adjusting settings...) you're probably better served with Selenium or any other dedicated web automated testing framework. Same goes for the IE web page.
What kind of performance issues do you have? Can you post a sample?

**Comment by gaoming1977** [comment]
Thanks for your reply, Roemer.
As the performance, I tried to use Inspector(the one of Windows SDK tools) and FlaUI-Inspector(the one using FlaUI core and UIA3) to identify the elements (for example, <input> tag) in the web page. It seems Inspector could identify it quicklier. :) 
As the Selenium or other web automated testing framework, we need the function of capturing mouse & keyboard events and identifying elements. It seems that need to do some extra extension. Furthermore, we want unify the API of Windows Applications and Web Applications.

**Comment by Roemer** [comment]
FlaUInspect should not be used for performance measurements, it's far from optimized :) You should try FlaUI directly to see if it has the same problems. Other than that, you should be able to have basic support for browsers as they more or less support the UIA framework. Give it a try and post feedback here or on gitter.
