### ISSUE TITLE
FlaUI with Internet Explorer or Chrome

### ISSUE THREAD

**Issue by hammonjj** [Roemer/FlaUI#132]
Does FlaUI support automating thing in Internet Explorer or Chrome? I'm having issues grabbing web page elements, but wasn't sure if this was actually supported or not and couldn't find any examples doing it.

Thanks!
James

Edit: Never mind, I figured out how to integrate with Internet Explorer. I would delete this issue if I knew how to do it!

**Comment by Roemer** [comment]
Deleting is not possible in GitHub. So make the issue usefull: Did you do something special to integrate it with IE? Might be helpful for others.
