### ISSUE TITLE
Application.WaitWhileBusy does not provide information on success

### ISSUE THREAD

**Issue by danielpullwitt** [Roemer/FlaUI#137]
Currently there is no way to determine if a call to Application.WaitWhileBusy actually succeeded.

Under the hood the timeout is passed to Process.WaitForInputIdle which returns a bool to indicate success / failure. This result is neither processed nor returned via the WaitWhileBusy method.

So in effect if I give a timeout and the application does not become responsive within the time limit, I can not find out (except by further operations failing).

**Comment by Roemer** [comment]
You're absolutely right. Just commited a change which returns a boolean instead. This will be in the next release.
