### ISSUE TITLE
Automation Clobbering UI Fields

### ISSUE THREAD

**Issue by hammonjj** [Roemer/FlaUI#138]
EDIT: Sorry about the weird formatting on the code, I can't seem to get the code block to work on the first couple of lines.
Edit2: Fixed by @Roemer

I'm prototyping this framework for an SSO solution for my company and we decided to start with doing complex-ish operations in Outlook to verify capabilities and are having some problems. When creating a new email, I am selecting the various field (to, subject, body, etc), but all of the input is just going into the "To" field (screenshot attached). I've tried sleeping threads, using the various wait functions, but can't seem to correct this behavior. What could be causing it? I've also placed a snippet of my code below for reference.

Also, you'll notice that I sleep for a second before trying to get the top level windows after pressing the send email button. Is there a way to get a notification on those instead of sleeping the thread?

Thanks!
James

```csharp
private void SendEmail_Click(object sender, RoutedEventArgs e)
{
    using(var automation = new UIA3Automation())
    {
        var mainWindow = _ApplicationHandle.GetMainWindow(automation);

        //Create Email
        var newEmailButton = mainWindow.FindFirstDescendant(cf => cf.ByText("New Email"))?.AsButton();
        newEmailButton?.Invoke();

        //Get Popup Window
        Thread.Sleep(1000);
        var topLevelWindows = _ApplicationHandle.GetAllTopLevelWindows(automation);
        var emailWindow = topLevelWindows.First(w => w.Name.Contains("Untitled"));

        //Fill Out To/Subject/Contents
        var toField = emailWindow.FindFirstDescendant(cf => cf.ByName("To"))?.AsTextBox();
        toField.Text = "james.hammond@philips.com";

        var subjectField = emailWindow.FindFirstDescendant(cf => cf.ByName("Subject"))?.AsTextBox();
        subjectField.Text = "Subject Field";

        var bodyField = emailWindow.FindFirstDescendant(cf => cf.ByAutomationId("Body"))?.AsTextBox();
                bodyField.Text = "Email Body";

        //Send
        var sendEmailButton = emailWindow.FindFirstDescendant(cf => cf.ByName("Send"))?.AsButton();
        sendEmailButton?.Invoke();
    }
}
```

![subjectline](https://user-images.githubusercontent.com/4194631/35534076-9ffc3052-04fc-11e8-8aaf-9b8d28870255.PNG)

**Comment by Roemer** [comment]
Hi James

For the first issue, it is quite possible that the controls do not fully support the value pattern and when FlaUI tries to type, it sets the focus to the wrong field. To see more details, I need a screenshot of an Inspect tool (like FlaUInspect) which shows the tree of controls involved here. I can test this tomorrow where I have an Outlook available myself.

The second issue is harder. There are events where you could subscribe but I found that they are not extremely reliable. The best bet here is to use the `Retry` class and just do a look with it until the window is found.

**Comment by hammonjj** [comment]
Hey Roemer!

Thanks for the reply, but can you define "value pattern" for me? I don't understand what that means exactly. UI spy screenshot attached of the "To" field

![tofieldinspect-inspect_exe](https://user-images.githubusercontent.com/4194631/35536841-4ffc8076-0505-11e8-85cd-32f0bd238067.png)

**Comment by Roemer** [comment]
Is there a child in the control? Can you expand it?
In UIA you mostly work with patterns. But the control needs to support it correctly. FlaUI uses those patterns with some fallbacks if available.

**Comment by hammonjj** [comment]
So I figured out part of it, once I started using the AutomationIDs, most of the fields starting working properly (not sure why), but I now have a new problem. There's one field that is "read only" (the body of the email), which is obviously not right. I must be grabbing the wrong component. My current plan is to just simulate a Tab press and then enter text in the field that is acquired after Tab. I figured out how to press the guy, but I was wondering if there was a method for getting the Automation Element that is currently in "focus", if that makes sense.

Thanks!

**Comment by pedroNew** [comment]
Hi,

You can retrieve currently focused element from AutomationBase object:

`var automationBase = new UIA2Automation();
var focusedElement =  automationBase.FocusedElement();
focusedElement.CaptureToFile(@"e:\test.bmp");`

**Comment by Roemer** [comment]
So I had a deeper look at it.

First about the automation ids:
The problem with the subject fiel is that there are two elements with the same text `Subject`. The first is the label and the second the edit. You did find only the label and since that is not writeable, FlaUI just presses the keyboard keys as fallback and therefore writing in the previous selected field.
You need to select the edit either by unique automation ID or for example by adding `.And(cf.ByControlType(ControlType.Edit))`.

Now about the body:
This is a good example of bad automation/accessibility support...
The effective control with the body text is nested a bit and is of the type `Document`.
I found it by using `emailWindow.FindFirstDescendant(cf => cf.ByControlType(ControlType.Document));`
Unfortunately this has no patterns available to edit it. So you can either tab to it or click on it and then use the keyboard like:
```csharp
var bodyField = emailWindow.FindFirstDescendant(cf => cf.ByControlType(ControlType.Document));
Mouse.LeftClick(new Point(bodyField.BoundingRectangle.Left + 1, bodyField.BoundingRectangle.Top + 1));
Wait.UntilInputIsProcessed();
Keyboard.Type("Hello World!");
```

**Comment by hammonjj** [comment]
Thanks a lot for all of your help! I'm seeing a trend here with you mentioning patterns. Do you know of a good resource to learn about them? I tried googling it, but, as you might expect, my results weren't particularly good.

Thanks again!

**Comment by Roemer** [comment]
In general, FlaUI tries to abstract all the UIA knowledge away and provide simple APIs for it. But it allows you to fully use all underlying UIA objects and commands as well.
The best documentation is on msdn itself.
The overview page is: https://msdn.microsoft.com/en-us/library/ms728097(v=vs.85).aspx
The most important things to understand are patterns, searching, treewalking, caching.
Also check out [FlaUIs wiki](https://github.com/Roemer/FlaUI/wiki) for some information (and feel free to extend it).

**Comment by maxinfet** [comment]
@Roemer I see problems like this on StackOverflow all the time for automating Outlook. Really awesome to see what is finally going on with those controls.

**Comment by hammonjj** [comment]
@Roemer Thanks again for your help. I was able to fully automate Outlook and our company is going to move to the next prototype stage in a quasi live environment!

**Comment by Roemer** [comment]
Great it is working.
Feel free to come back if you have more issues / questions.
