### ISSUE TITLE
cell.Value property gives the Name property instead (MSAA proxy)

### ISSUE THREAD

**Issue by TorjusE** [Roemer/FlaUI#139]
Hey,
I'm working with a winforms application created with devexpress, so the properties i use are the ones I get from the MSAA proxy provider generated by UIA (correct?). I'm working with a lot of grids and I'm trying to assert the value of a particular cell.
I'm still fairly new to the programming of automated tests and to FlaUI so I might be doing something wrong.
I will try to post the relevant info from the microsoft inspect tool:

![image](https://user-images.githubusercontent.com/34065427/35968203-7adbb4c2-0cc3-11e8-8d3d-b574e6d95a35.png)

**""table** (the grid)
ControlType:	UIA_TableControlTypeId (0xC374)
LocalizedControlType:	"table"
LegacyIAccessible.Role:	table (0x18)
IsGridItemPatternAvailable:	false
IsGridPatternAvailable:	false
IsLegacyIAccessiblePatternAvailable:	true
ProviderDescription:	"[pid:8264,providerId:0x1511C6 Main:Nested [pid:16040,providerId:0x1511C6 Main(parent link):Microsoft: MSAA Proxy (unmanaged:uiautomationcore.dll)]; Hwnd(parent link):Microsoft: HWND Proxy (unmanaged:uiautomationcore.dll)]"

All the other patterns displayed are false.

**"Data Panel"**
Does not show ControlType or Localized control type.
LegacyIAccessible.Name:	"Data Panel"
LegacyIAccessible.Role:	client (0xA)
LegacyIAccessible.State:	normal (0x0)
LegacyIAccessible.Value:	""
IsLegacyIAccessiblePatternAvailable:	true
ProviderDescription:	"[pid:16040,providerId:0x0 Main(parent link):Microsoft: MSAA Proxy (unmanaged:uiautomationcore.dll)]"

**"Row 1"**
Does not show ControlType or Localized control type.
LegacyIAccessible.Name:	"Row 1"
LegacyIAccessible.Role:	row (0x1C)
LegacyIAccessible.State:	selected,focused,read only,focusable,selectable (0x300046)
IsLegacyIAccessiblePatternAvailable:	true

**"Name row 0"** (this is the cell)
Name:	"Name row 0"
ControlType:	UIA_DataItemControlTypeId (0xC36D)
LocalizedControlType:	"item"
LegacyIAccessible.Name:	"Name row 0"
LegacyIAccessible.Role:	cell (0x1D)
LegacyIAccessible.State:	focused,read only,focusable,selectable (0x300044)
LegacyIAccessible.Value:	"Tor Browser"
Value.IsReadOnly:	true
Value.Value:	"Tor Browser"
IsGridItemPatternAvailable:	false
IsGridPatternAvailable:	false
IsInvokePatternAvailable:	true
IsItemContainerPatternAvailable:	false
IsLegacyIAccessiblePatternAvailable:	true
IsValuePatternAvailable:	true
ProviderDescription:	"[pid:16040,providerId:0x0 Main(parent link):Microsoft: MSAA Proxy (unmanaged:uiautomationcore.dll)]"

Here is my code:
```csharp
public static void ButtonNewRuleFromSelected()
{
    using (var app = Application.Attach("disadmin.exe"))
    {
        using (var automation = new UIA3Automation())
        {
            var softwareWindow = app.GetMainWindow(automation);
            var grid = softwareWindow.FindFirstDescendant(cf => cf.ByAutomationId("1380806")).AsGrid();
            var gridData = grid.FindFirstChild(cf => cf.ByName("Data Panel")).AsDataGridView();
            var row = gridData.FindChildAt(1).AsGridRow();
            var cell = row.FindFirstChild(cf => cf.ByName("Name row 0")).AsGridCell();
            Assert.That(cell.Value == "Tor Browser", cell.Value);
        }
    }
}
```
This gives me a failed test with the info
Message:   Name row 0
  Expected: True
  But was:  False

I put the cell.Value as the message just to display what the "value" is.

I've also done a cell.Click(); and this works, making the program click on the right cell.
In advance
Thanks

**Comment by Roemer** [comment]
Hi
Can you check with FlaUInspect what it shows for a cell? Especiall what it shows for the ValuePattern.Value.
Best is to select the cell in FlaUInspect and post a screenshot here.

**Comment by TorjusE** [comment]
Hey,
thanks for the reply, here is a screenshot with FlaUInspect 1.2:
![image](https://user-images.githubusercontent.com/34065427/36018727-1c155820-0d7d-11e8-8952-9855fa2e0c58.png)
and the rest of it:
![image](https://user-images.githubusercontent.com/34065427/36018745-2a41eab2-0d7d-11e8-8cb3-2ad2b1e288e7.png)

**Comment by Roemer** [comment]
Ok, as you see the `ValuePattern` contains the correct value.
The current implementation of the `GridCell` only returns the `Name` property as `Value`.
What you can do now is use `cell.Patterns.Value.Pattern.Value.Value`.
I know, this reads strange but makes sense.
* `cell` is the element you have
* `Patterns` is a container with all patterns
* `Value` is the pattern we want
* `Pattern` returns the pattern object
* `Value` is the Value property object of the pattern
* `Value` is the effective value of the property

**Comment by TorjusE** [comment]
Hey,
this worked after a few tries, thank you! I managed to make the the PC run out of memory the first few times... The grids I work with contains several hundred thousand rows, so I need to be very specific, or the program will look through the entire grid (?) and eat up all the memory I guess.

**Comment by Roemer** [comment]
Great
Yes, working with grids can be a bit difficult. Especially `FindFirstDescendant` or `FindChildAt` can need to search thru the entire grid.
You can have a look at the methods in the `GridPattern` that might help you navigate the grid cells without going thru the entire grid.

**Comment by TorjusE** [comment]
Thanks for the tip! I had a feeling FindFirstDescendant worked that way, but I thought FindChildAt was safer so I will keep that in mind. Ill try my hands at the methods in GridPattern then.

**Comment by Roemer** [comment]
Also check out https://github.com/Roemer/FlaUI/wiki/Caching
