### ISSUE TITLE
FlaUI CI Server Compatible?

### ISSUE THREAD

**Issue by Stu1986c** [Roemer/FlaUI#140]
Hi

I'm looking to move away from TestStack.White to FlaUI. What's FlaUI's compatability like with running on CI servers without a monitor / display?

Thanks in advance

**Comment by Roemer** [comment]
Using VMs or servers without monitor is totally fine as long as they have a logged in user with a desktop session. Just be careful when you use RDP and then disconnect as then you normally loose the desktop session. Use a special bat script to disconnect or switch to VNC to solve this.

**Comment by Stu1986c** [comment]
Excellent. Thanks ever so much for the fast response :) I'll have to give it a go and give you a shout if I get stuck.
