### ISSUE TITLE
FindFirstDescendant fails to find the control if the UI is not in focus

### ISSUE THREAD

**Issue by AstroCan** [Roemer/FlaUI#145]
I am attempting to automate login onto a website. I use the following command to find the controls
--- var element = window.FindFirstDescendant(cf => cf.ByText(identifier)); ---
It works fine when the page is in focus but fails to find the control if the page is minimized, behind another window, or not the current tab.

Thanks for your help -

**Comment by Roemer** [comment]
What browser/version and what website? UI-Testing on websites is not the strength of UIA (what FlaUI is based on), you might try Selenium for website testing.

**Comment by AstroCan** [comment]
I am using IE 11 - google.com.
I search for the "Google Search" button on the google.com page.
Here is what the process tree looks like in FlaUIInspect:
![2018-02-27 10_58_00-flauinspect v1 2 0](https://user-images.githubusercontent.com/36676766/36745604-48efa6c8-1bad-11e8-95eb-43c66ffa6250.png)

![2018-02-27 11_05_48-findfirstdescendant fails to find the control if the ui is not in focus issue](https://user-images.githubusercontent.com/36676766/36745906-363ae820-1bae-11e8-9474-ed49e7da3442.png)

So my assumption is that doing something like this:
`using (var app = Application.Attach(17560))
            {
                using (var automation = new UIA3Automation())
                {
                    var window = application.GetMainWindow(automation);
                    var uiControl = window.FindFirstDescendant(new PropertyCondition(automation.PropertyLibrary.Element.Name, "Google Search"));
                }
            }`
Should have found the control. Unless I am missing something?

Here is the app value from that processId. The returned window type is a "Pane".
![2018-02-27 10_45_48-connectorsolution debugging - microsoft visual studio](https://user-images.githubusercontent.com/36676766/36746009-72265194-1bae-11e8-9e3c-cf826512024c.png)

**Comment by Roemer** [comment]
Ok the problem is that you probably have the "wrong" iexplore process. When you start IE, it starts multiple processes. I guess one per tab and at least one "main" task. As you see in the screenshots above, you  have multiple process ids: The "main" process seems to be 17560 with is just here for orchestrating IE and which does not have a visual representation (it does have a MainWindow but it has invalid bounds and cannot be rendered). And then 18522 which is the process of your google window.

Here is a RoslynPad script which successfully searches for "Hello" on google (you might need to adjust the name/automation id):
```csharp
#r "$NuGet\FlaUI.Core\2.0.0-alpha6\lib\net45\FlaUI.Core.dll"
#r "$NuGet\FlaUI.UIA3\2.0.0-alpha6\lib\net45\FlaUI.UIA3.dll"
#r "$NuGet\FlaUI.UIA3\2.0.0-alpha6\lib\net45\Interop.UIAutomationClient.dll"
#r "PresentationCore"
#r "PresentationFramework"
#r "WindowsBase"

using System.Diagnostics;
using FlaUI.Core;
using FlaUI.Core.AutomationElements;
using FlaUI.UIA3;

using (var app = Application.Attach(2216))
{
    using (var automation = new UIA3Automation())
    {
        var window = app.GetAllTopLevelWindows(automation)[0];
        var input = window.FindFirstDescendant(cf => cf.ByName("Suche").And(cf.ByAutomationId("lst-ib")));
        input.Patterns.Value.Pattern.SetValue("Hello");
        var searchButton = window.FindFirstDescendant(cf => cf.ByName("Google-Suche")).AsButton();
        searchButton.Invoke();
    }
}
```

**Comment by AstroCan** [comment]
Sorry I left the 17560 in there by mistake. I was actually using the process id of the tab which was the 18522. But I have not attempted using the "GetAllTopLevelWindows(automation)[0]". I will give that a try and see what happen.

Thanks-

**Comment by AstroCan** [comment]
The call to GetAllTopLevelWindows returns an empty list when passing the google tab process id. If I pass in the main IE process id then it all works and I am able to find the UI controls BUT only if the tab is in focus.
So puzzling!

Any ideas?

**Comment by AstroCan** [comment]
Just to illustrate what I am seeing.
In my scenarios below I have two IE tabs opened (google and bing) and I am trying to locate controls on the google tab.

In the 1st test, I am passing the google tab process id as `Using var app = Application.Attach(68160)` and expecting to retrieve the window with `app.GetAllTopLevelWindows(automation)[0]`
As you can see in my immediate window, no window is found.
![image](https://user-images.githubusercontent.com/36676766/36808854-91c526bc-1c83-11e8-87b0-b5152b39a0f5.png)


In my 2nd test, I am passing the main IE process id 52440. I would then expect the call `app.GetAllTopLevelWindows(automation)` to return two windows (google and bing) but as you can see in my immediate window only the active tab window is returned.
![image](https://user-images.githubusercontent.com/36676766/36808934-c4d50112-1c83-11e8-851b-970a32626edc.png)

**Comment by Roemer** [comment]
You always only have one open window, the one which is active.
The active window belongs to the main IE process. But all the content of the "active tab" belongs to another process (doesn't matter unless you find by specific process id). So if you work with multiple tabs, you need to switch the tabs. You can automate that as well. There is a `Tab` in the header `Pane` with the `TabItems` which you can activate. Then the content of the `Pane` that includes the effective content changes.

**Comment by Roemer** [comment]
Is your issue solved now?

**Comment by Roemer** [comment]
Closed due to inactivity.
