### ISSUE TITLE
Calling Application.WaitWhileMainHandleIsMissing in a "Using (...)" pattern fails

### ISSUE THREAD

**Issue by AstroCan** [Roemer/FlaUI#146]
I am launching an IE application and trying to wait for the handle to be available as such:
` using (var app = Application.AttachOrLaunch(processInfo))
                {
                    app.WaitWhileMainHandleIsMissing();
                }
`

The app.WaitWhileMainHandleIsMissing() is throwing an System.InvalidOperationException.

![error](https://user-images.githubusercontent.com/36676766/36448443-e630f8ba-1644-11e8-8553-be52ba8184e7.png)

Is there anything I am missing?

Thanks for your help -

**Comment by Roemer** [comment]
The `HasExited` flag is set to true. So either you're starting IE with a shim or IE closes directly again. Can you try starting IE manually once, get the process id via `Task Manager` and try to attach to it by process id? Also what system are you using and what version of IE?

**Comment by Roemer** [comment]
See #145 . I guess it has to do with the different IE processes.

**Comment by AstroCan** [comment]
That is correct. The issue is related to #145 and having multiple instances of the same IE application.
