### ISSUE TITLE
FindFirstDescendant finds it target once, then fails on second run.

### ISSUE THREAD

**Issue by TorjusE** [Roemer/FlaUI#147]
Hi,
I am working on a simple winforms application using the designer with a button which I can click and then it fills out a form for me. 
I made a class with a method `FillFormGeneric()` which works fine, then I made a second method, `FillFormExtra()` in this class, which only works once, then it gets a nullreference exception on
`var specificsTab = editDialogue.FindFirstDescendant(cf => cf.ByName("Specifics")); `
 the second time i click the button.
The plan was to have 2 buttons, one which launches just the first method, and a 2nd which executes both of them.
This is how I have written the class which I wish to give more methods, is there something wrong with this setup since it fails on the line with `FindFirstDescendant()` on my 2nd method?

    `public static class FormInformation
    {
        public static void FillFormGeneric()
        {
            using (var app = Application.Attach("program.exe"))
            {
                using (var automation = new UIA3Automation())
                {
                    var mainWindow = app.GetMainWindow(automation);
                    var editDialogue = mainWindow.FindFirstChild(cf => cf.ByControlType(ControlType.Window));
                    var generalPane = editDialogue.FindFirstDescendant(cf => cf.ByName("General").And(cf.ByControlType(ControlType.Pane)));
                    var name = generalPane.FindFirstDescendant(cf => cf.ByAutomationId("Name")).AsTextBox();
                    string formName = UIA.Common.Name;
                    name.Enter(formName);
                    //Do more things...
                }
            }
        }

        public static void FillFormExtra()
        {
            using (var app = Application.Attach("program.exe"))
            {
                using (var automation = new UIA3Automation())
                {
                    var mainWindow = app.GetMainWindow(automation);
                    var editDialogue = mainWindow.FindFirstChild(cf => cf.ByControlType(ControlType.Window));
                    var specificsTab = editDialogue.FindFirstDescendant(cf => cf.ByName("Specifics")); //Works once, then System.NullReferenceException
                    specificsTab.Click();
                    //Do more things...
                }
            }
        }
    }`

**Comment by Roemer** [comment]
Keep in mind that the find methods return null if the element is not available at that exact moment.
Try putting a Retry.WhileNull around it.

**Comment by TorjusE** [comment]
Ok, ill try that.
Thanks for the reply.

**Comment by TorjusE** [comment]
I can't find a Retry.WhileNull in FlaUI.Core.Tools.
I see only Retry.While and Retry.WhileException
Do I have an outdated version? I've gotten FlaUI through the nuget manager in visual studio.

**Comment by Roemer** [comment]
You should use the 2.0.0 pre-release version.

**Comment by TorjusE** [comment]
Ah, I will do that then and try again on monday :)

**Comment by TorjusE** [comment]
Installed the 2.0.0 version and managed to make it work with retry while null.
Thanks for the help!
