### ISSUE TITLE
How to hook mouse and Keyboard?

### ISSUE THREAD

**Issue by 22092** [Roemer/FlaUI#150]
Hello ,
I need to look(hook) the mouse and Keyboard when call the mouse click,move and keyboard press.
May I know how to using FlaUI to do that? thanks

**Comment by Roemer** [comment]
Am I right that you want to register for mouse clicks and keybord presses? If so, FlaUI does not support that currently but there are alternatives for that like https://www.nuget.org/packages/MouseKeyHook/

**Comment by 22092** [comment]
for example:
[DllImport("user32.dll")]
static extern bool BlockInput(bool fBlockIt);
To block all input when using FlaUI to do mouse clicks and keybord presses.

but when I block all input, the FlaUI Mouse.Click() will not working.

**Comment by pedroNew** [comment]
It's expected behaviour. It doesn't matter what is actual source of the input - at the end there is always the same invocation of user32 functions.
