### ISSUE TITLE
FlaUI.Core.Capturing.MouseOverlay Error

### ISSUE THREAD

**Issue by pavlikpatrycja** [Roemer/FlaUI#151]
Hi, 
I'm using FlaUI to autmatic tests for WinForms application on Windows Server 2016. When I'm on remote desktop connection with server, run test and minimalize this window, I get error: 
Error: Failed applying overlay 'FlaUI.Core.Capturing.MouseOverlay'
System.ArgumentNullException: Value cannot be null.
I would be happy if you could help me to fix this error or create some workaround.

**Comment by Roemer** [comment]
When you minimize an RDP window, the desktop session on the RDP server is actually kind of deactivated. Therefor UI tests using the mouse (or capturing a screenshot with the mouse) won't work correctly.
So solution 1: Make sure that the mouse is absolutely never used in the UI tests.
Solution 2: Keep the window maximized
Solution 3: Do not use RDP, use VNC or something similar which is more flexible regarding this issues.

**Comment by pavlikpatrycja** [comment]
Thank you very much for such a quick response. I hope third solution works :)

**Comment by Roemer** [comment]
I also switched to VNC for all UI-Test-Agents and have no issues since then.
