### ISSUE TITLE
Waiting for loaded window

### ISSUE THREAD

**Issue by pavlikpatrycja** [Roemer/FlaUI#152]
Hi, 
I'm using FlaUI to autmatic tests for WinForms application on Windows Server 2016. I'm looking for best way to wait for loading window of an application. I tried Thread.Sleep(time) but I think it's not good because it waste time if window is loaded faster than expected time. Now I use this method: 
```csharp
public void WaitUntilWindowAppears(Window window, int waitFor = 15000)
        {
            Stopwatch watch = new Stopwatch();
            watch.Start();
            while (window==null && watch.ElapsedMilliseconds < waitFor)
            {
                System.Threading.Thread.Sleep(1000);
                window= Automation.GetDesktop().FindFirstChild(cf => cf.ByName("Name")).AsWindow();
            }
            watch.Stop();
        }
```
Is there any better method/idea to do this?

**Comment by Roemer** [comment]
Have a look at the `Retry` class.
You could use something like `Retry.WhileNull(() => Automation.GetDesktop().FindFirstChild(cf => cf.ByName("Name")));` There are plenty of configuration options for the retry methods. Check them out. There is some documentation here: https://github.com/Roemer/FlaUI/wiki/Retry

**Comment by pavlikpatrycja** [comment]
After adding second argument of type TimeSpan it works as I wanted. Thanks a lot!
