### ISSUE TITLE
Not possible get value from control over UIA3

### ISSUE THREAD

**Issue by Zizer** [Roemer/FlaUI#155]
I have WinForms Panel element with DateTime. In UIA2 i can take value over ValuePattern (28.01.2016 8:28 for example). In UIA3 ValuePattern not supported and value in LegacyIAccessiblePattern return only 28 January 2016.  How I can take full value in UIA3?

**Comment by Roemer** [comment]
You can't. For some WinForms controls, UIA2 and UIA3 behaves differently. So if you've got a WinForms application, you should probably stick to UIA2.

**Comment by Zizer** [comment]
I have many controls which working only in UIA3. If I use UIA3 and UIA2 together - UIA3 part working as UIA2.

**Comment by Roemer** [comment]
Yes, this is the expected behavior. If you need to use uia2 and uia3, you need to run the tests separate (see FlaUIs UITests on how this can be done).

**Comment by Zizer** [comment]
But some framework(Testcomplete for example) see all element. What method they use for getting control properties? WinAPI?

**Comment by Roemer** [comment]
They also use debug information, memory anlysis and other methods to get additional information. FlaUI only uses UIA.

**Comment by Zizer** [comment]
Do you know open/free framework for gui testing working without UIA using?

**Comment by Roemer** [comment]
No. I am planning to add some features to FlaUI but currently I lack free time to do this right now. As a workaround, you can always use Capture and image compare for stuff you cannot get by FlaUI right now.

**Comment by pedroNew** [comment]
@Roemer what features you have in mind? Maybe you can add some backlog items with 'help wanted' tag?

**Comment by Roemer** [comment]
@pedroNew See #162
