### ISSUE TITLE
Winforms - wait for loading new window

### ISSUE THREAD

**Issue by Tiziton** [Roemer/FlaUI#156]
Hi !
I'm using FlaUI to automation tests for Winforms application. Is there any method waiting for new window without giving the name of this window? I need to check if any window with the same process id displayed in some period of time.

**Comment by Roemer** [comment]
You can use something like that
```csharp
int processId = 1000;
using (var automation = new UIA3Automation())
{
    var desk = automation.GetDesktop();
    Retry.WhileNull<Window>(
        desk.FindFirstChild(cf =>
            cf.ByControlType(FlaUI.Core.Definitions.ControlType.Window)
            .And(cf.ByProcessId(processId))
        ).AsWindow);
}
```

**Comment by Roemer** [comment]
Any feedback on this?

**Comment by andyb1979** [comment]
Just tried it for a similar problem & yep works for me!
