### ISSUE TITLE
Interop.UIAutomationClient error

### ISSUE THREAD

**Issue by pavlikpatrycja** [Roemer/FlaUI#157]
Hi, 
I want to run tests for Winforms application from .exe file, so I need Main method in my project.
I created some tests for Winforms application in class library project and build it to get .dll file. I created console application project, add reference to my .dll and all FlaUI and NUnit libraries and build it to get .exe file. When I run my .exe file it fails. When I debug I get error: 
System.IO.FileNotFoundException: 'Could not load file or assembly 'Interop.UIAutomationClient, Version 4.5.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.' The error occured when object of my test class was created, screenshot in attachment.
Could you please help me find the issue ?
![2018-04-12_12h19_57](https://user-images.githubusercontent.com/14920046/38672443-7e68b466-3e4e-11e8-81c4-8e2afe5b7122.png)

**Comment by Roemer** [comment]
Do you use the nuget packages? If not, you also need to add the Interop.UIAutomationClient.dll and set the `Embed Interop Types` to false on it in the properties.

**Comment by pavlikpatrycja** [comment]
It worked, thank you. I could't download nuget package Interop.UIAutomationClient because your framework is 4.5 .NET version and the nuget package is not compatible with it.

**Comment by RBKjobs** [comment]
Please say how to fix this error. I get this same error and also I can't download Interop.UIAutomationClient from nuget packages. How to solve this error

**Comment by Roemer** [comment]
Easiest way is to use FlaUIs nuget package. Otherwise, make sure to use the correct interop assembly from https://github.com/Roemer/FlaUI/tree/master/src/libs/Interop and add it to your project and set the `Embed Interop Types` to `false`.

**Comment by RBKjobs** [comment]
Thanks for the clarification. It worked

**Comment by ataliady** [comment]
I have the same issue, after doing all the steps you described above. Any other fixes you can offer?

**Comment by Roemer** [comment]
@ataliady Can you elaborate a bit more? What .NET Framework are you using? What FlaUI version?
