### ISSUE TITLE
Use in a VirtualBox

### ISSUE THREAD

**Issue by danhi** [Roemer/FlaUI#158]
Has anyone ever tried running this in a VirtualBox?  It doesn't seem to be able to find buttons and the like.

**Comment by Roemer** [comment]
Hi danhi
What kind of exceptions do you get? Make sure that a user is logged in in the virtualbox vm. Maybe also make sure that the virtualbox window is completely visible.

**Comment by danhi** [comment]
Don't know what I was doing wrong before but it works great now, even when the VM is minimized, which makes running long tests much more convenient.  I can't say enough how much this product has helped me in doing a better job of testing out my app.  Thanks for all the good work!
