### ISSUE TITLE
SubMenuItems

### ISSUE THREAD

**Issue by RicardoBA** [Roemer/FlaUI#159]
Hi Roemer. I would like to perform a click on this menuItem. No success right now....
![newmodel](https://user-images.githubusercontent.com/38432836/38816668-e179524a-4196-11e8-9f97-f2b803428b34.png)

FlaUI.Core.AutomationElements.Menu menuPrincipal =
                    window.FindFirstDescendant(cf => cf.ByName("MainMenuToolbar")).AsMenu();
                FlaUI.Core.AutomationElements.MenuItem menuItemFile = menuPrincipal.Items["File"];

                menuItemFile.Expand();

From here, nothing works. menuItemFile does not have any items....

Can you help me?. Thanks!

**Comment by HyruleWarrior** [comment]
If you use FlaUInspect what does it look like?

**Comment by RicardoBA** [comment]
![flauinspect](https://user-images.githubusercontent.com/38432836/38853002-2e07ee2a-421c-11e8-842b-cf7767b6cea3.png)

I can see the control that I want but I do not see the menu items that I need to perform the click or expand. My first step is to navigate correctly through the toolbar, File->New...->New model. I can access to File item but it seems that it has not items....I think this menu was developed using Infragistic. I do not know if FlaUI can use it.

Thanks.

**Comment by RicardoBA** [comment]
![flauinspect2](https://user-images.githubusercontent.com/38432836/38858906-33055226-422d-11e8-812a-6557d0ff593d.png)

Sorry, I think this image is what you want. Notice that no chindren, items under File menu item and there are more items ....

**Comment by HyruleWarrior** [comment]
Try using Hover Mode (use Ctrl) in FlaUInspect and look at that item when the menu is expanded. They won't show up there (or in your code) if the menu is collapsed so it makes debugging tricky. If you step through, as soon as you hit a breakpoint, the menu closes so you wouldn't see it's children. 

I am guessing it is there, but it just isn't being found by whatever method you are using. You can try something like:

`menuItem.Items[0].Click()`

after your expand call just to verify it is there when expanded.

**Comment by RicardoBA** [comment]
Well, after..... tries, I've got it. Thanks for your help!. I will continue working with this API. Good job!
