### ISSUE TITLE
Evaluating the function 'FlaUI.Core.AutomationElements.Window.ContextMenu.get' timed out

### ISSUE THREAD

**Issue by jim-n** [Roemer/FlaUI#161]
FlaUI.Core: v1.3.0
When debugging in Visual Studio the FlaUI.Core.AutomationElements.Window.ContextMenu is timed out.

![image](https://user-images.githubusercontent.com/16239479/39287939-4d77e3bc-4926-11e8-9adc-41099ea41d3b.png)

Is there some other information that I can provide?

**Comment by Roemer** [comment]
Keep in mind that if you debug and set a breakpoint, the context menu will immediately close when the breakpoint is hit (because the application with the context menu looses focus and visual studio gets the focus). Might this be the issue?

**Comment by jim-n** [comment]
What I´m trying to do is to see what objects are available on a "main" window level.
So if I break after attaching to the process and try to expand the Window object I get the timeout.
This means the menu have never been expanded, so I guess there should not be any objects under the Window context menu.

By the way, I really like the framework and thank you for all the work put into it!
