### ISSUE TITLE
Starting the application separated from the constructor

### ISSUE THREAD

**Issue by pavlikpatrycja** [Roemer/FlaUI#164]
Hi! 
I consider if it is possible to separate starting application from test's constructor, because I need to make some steps before starting windows forms application. I tried to override some methods from UITestBase but I'm doing something wrong cause after my changes nothing worked... 
Thanks in advance

**Comment by HyruleWarrior** [comment]
You are probably looking for a OneTimeSetup or SetUp method. A method with the [OneTimeSetup] attribute will only be run once before any tests (whether you run 1 test or 10) where a method with the [SetUp] attribute will be run before each test.

If you need to do some stuff before launching your application for testing, the OneTimeSetup/OneTimeTeardown is the place to do it.

**Comment by pavlikpatrycja** [comment]
You're right about using OneTimeSetup and SetUp methods in tests but it isn't what I'm looking for. I really want to create method which starts the application instead of attributing it in UITestBase OneTimeSetUp but what I see is that test doesn't work without starting application in this way.

**Comment by Roemer** [comment]
You can either use the `Application.Attach` with a given processId so you can start your process on your own or don't use the `Application` at all. The  `Application` is just a very thin wrapper for some convenience methods to easily get to the main window or child windows of a given application but you can easily get that as well by just using the `Automation.GetDeskop` method and search on your own for the wanted `Windows`.

**Comment by pavlikpatrycja** [comment]
I did it finally. Thank you very much.
