### ISSUE TITLE
FindFirstByXPath fails after closing and re-opening a window

### ISSUE THREAD

**Issue by turquoiseowl** [Roemer/FlaUI#167]
Hi, I'm writing some functional tests for my app using your great library (thanks very much for that) and having fun at the moment trying to get everything fully deterministic. 

A particular problem I am having is with testing the uninstallation of my app: opening the Windows 'Programs and Features' window to select the ListItem for my app and invoking it. Using your neat XPath mechanism, I am finding that sometimes the ListItem is found and sometimes it is not. And further investigation has shown that the xpath navigator seems to puke internally with NullReferenceException coinciding with null being returned from FindFirstByXPath. In turn that happens only when I close and reopen the host 'Programs and Features' window.

Here's some code that illustrates the problem:

```
public static void LookupProgramAndFeaturesListItem()
{
    using (UIA3Automation automation = new UIA3Automation())
    {
        using (Application app = Application.Launch(new ProcessStartInfo("control.exe", "appwiz.cpl")))
        {
            Window mainWindow = Retry.WhileNull(() => automation.GetDesktop().FindFirstByXPath("/Window[contains(@Name, 'Programs and Features')]")).AsWindow();
            FlaUI.Core.Input.Wait.UntilResponsive(mainWindow);
            AutomationElement listItem = mainWindow.FindFirstByXPath("/Pane[contains(@Name, 'Programs and Features')]/Pane[@ClassName='DUIViewWndClassName']/Pane[@Name='Shell Folder View']/List[@Name='Folder View']/ListItem[@Name='Microsoft Silverlight']");
            System.Diagnostics.Debug.Assert(listItem != null); // <----- THIS BOMBS ON THE SECOND CALL
            mainWindow.Close();
        }
    }
}
public static void TestLookupOfProgramAndFeaturesListItem()
{
    LookupProgramAndFeaturesListItem();
    LookupProgramAndFeaturesListItem();
}
```

Tested on Windows 7.

I'm just wondering whether there is any caching going on that is being upset by me closing and re-opening the window. Possibly something to do with the shell explorer.exe process also.

Many thanks.

**Comment by turquoiseowl** [comment]
@jim-n Is your issue also related to windows that you have previously closed then re-opened?

I've refined the test slightly to use only a single UIA3Automation instance, as follows:

```
public static void LookupProgramAndFeaturesListItem(UIA3Automation automation)
{
    using (Application app = Application.Launch(new ProcessStartInfo("control.exe", "appwiz.cpl")))
    {
        Window mainWindow = Retry.WhileNull(() => automation.GetDesktop().FindFirstByXPath("/Window[contains(@Name, 'Programs and Features')]")).AsWindow();
        System.Threading.Thread.Sleep(1000);
        AutomationElement listItem = mainWindow.FindFirstByXPath("/Pane[contains(@Name, 'Programs and Features')]/Pane[@ClassName='DUIViewWndClassName']/Pane[@Name='Shell Folder View']/List[@Name='Folder View']/ListItem[@Name='Microsoft Silverlight']");
        System.Diagnostics.Debug.Assert(listItem != null); // <----- THIS BOMBS ON THE SECOND CALL
        mainWindow.Close();                                // <---- comment this line out then the above doesn't bomb and all works fine
        System.Threading.Thread.Sleep(1000);
    }
}
public static void TestLookupOfProgramAndFeaturesListItem()
{
    using (UIA3Automation automation = new UIA3Automation())
    {
        LookupProgramAndFeaturesListItem(automation);
        LookupProgramAndFeaturesListItem(automation);
    }
}
```

**Comment by jim-n** [comment]
When the object I search for was found it did not have all patterns since a dialog was blocking it. After the dialog was closed the patterns did not update and the property was not available.

Somehow the issue is in UIA3 since UIA2 updates the patterns for the object correctly.

This is also an issue when opening a window and grabbing the object before the window is ready for an invoke close. Then it is not possible to close the window with Close() since the object does not have the correct property, but with UIA2 this is not an issue since the pattern is updated.

**Comment by turquoiseowl** [comment]
That helps @jim-n - I've just tried UIA2 and my problem goes away! UIA2 also seems to be happier in the debugger: property evaluation in the debugger working and no annoying pauses.

I have modified my test code above to drill down using FindFirstChild calls rather than XPATH and problem remains, so xpath isn't at fault.

Kind of frustrating because I have the parent window element and cannot find any child elements; whereas if I open up FlaUInspect.exe on the same target window instance then the child elements get listed (both in UIA2 and UIA3 mode). Moreover, if I close my current test process and run a new process then I _can_ see the child windows of same parent window.

There must be something being cached somewhere that isn't being dropped when then window is closed and reopened.

Is it perhaps the COM interop that is behind some of this? Or UIAutomation3 implementation itself?

**Comment by turquoiseowl** [comment]
A further though is that the problem at hand relates to non-window elements, specifically ListView items. That is, elements that are actual windows and have HWNDs show up reliably.

**Comment by jim-n** [comment]
I think I have found a solution to my problem.
By using SystemInfo.RefreshAll() from FlaUI.Core.Tools I got the properties to update.

**Comment by turquoiseowl** [comment]
@jim-n That is interesting, thank you, and may confirm my latest suspicion about what is going on.

Looking at the code for SystemInfo.RefreshAll, it doesn't do anything particularly related; but what it does do is make what I suspect is an out-of-apartment COM call (to the WMI api). What that will do in turn is allow the message loop for the current/calling thread to pump messages thereby allowing incoming calls from other COM apartments to be handled. That in turn could very well allow something that is blocked to unblock, and that may well be related to updates of state that need to happen as a result of a window being closed and re-opened.

Underlying all this may be a requirement of UIAutomation3 which is that client calls to the API should be made from COM MTA threads and ones that are async to any UI of the client.

https://msdn.microsoft.com/en-us/library/windows/desktop/ee671692(v=vs.85).aspx

My switch to UIA2 has helped, but am now encountering new problems resulting from that, so will try your suggestion and may dig a bit deeper into this threading stuff and report back. (Oh, the joys of Windows and COM programming...!)

**Comment by Roemer** [comment]
Interesting findings. Keep me updated, especially if there is something FlaUI could do to prevent this.

**Comment by turquoiseowl** [comment]
I've abandoned my attempts to resolve this. Things tried are as follows:

* Running the test on an MTA thread -- no difference detected
* Calling SystemInfo.RefreshAll() -- no difference
* Calling System.Windows.Forms.Application.DoEvents() -- no difference
* Several other things, including banging head on wall -- no difference

What does work is switching to UIA2. This had a side effect of breaking my Xunit tests with an annoying ```System.CannotUnloadAppDomainException``` exception. This was happening because Xunit (1.9) spins up a fresh AppDomain per test case, the unloading of which checks any/all threads have been cleaned up otherwise that exception is thrown, and Xunit allows that through thus stopping the entire test run even if the tests passed.

The culprit here looks to be the ```UIAutomationClientsideProviders.dll``` lib loaded by UIA2 for Windows common controls. This library starts its own thread which seems reluctant to end, blocking on what appears to be user input. E.g. doing an Atl-Tab seems to nudge the wait allowing the thread to check whether it should end then fall out gracefully. Clicking the task bar does the same. Looks to be a bug in that lib.

If it helps anyone, my solution was to do a custom build of Xunit 1.9.2 and wrap the AppDomain.Unload call in a try/catch block.

Thanks for help and closing as unfixable.
