### ISSUE TITLE
Trying to access Grid but not showing up

### ISSUE THREAD

**Issue by Geograd** [Roemer/FlaUI#169]
Hey guys,

Love FlaUi so far but I'm running into a strange issue. I'm trying to access a grid but it's not showing up in the inspect and there's no children besides a vertical scroll bar when I try the FindAllChildren() of the pane. Any help or ideas would be greatly appreciated!

![strange grid issue](https://user-images.githubusercontent.com/10901048/40766588-cf0db70e-6464-11e8-92e7-1c9ae1c32620.jpg)

**Comment by Geograd** [comment]
Some more info. The combo box only seems to show up when it's actually selected. Any way to access the grid/cells through FLAUI?

![example 2](https://user-images.githubusercontent.com/10901048/40808768-08b43eec-64dd-11e8-903a-9882d26184b5.jpg)

**Comment by Roemer** [comment]
Is this grid from a control library? If so, which one?

**Comment by Geograd** [comment]
What do you mean a control library? It's from a software I'm trying to automate.

**Comment by Roemer** [comment]
Ah you don't have access to the source control of this software? Is this software free/downloadable?

**Comment by Geograd** [comment]
No. Don't have access to the source and no it's an enterprise software. I could send you a demo disc if that's something you need though. Have you seen this happen before with software?

**Comment by Roemer** [comment]
The classname of the grid is `MIGrid` which sounds like some kind of control of a control libary or custom control. If that control does not implement UIA/Accessibility correctly, there is not much any of the UIAutomation which rely on UIA can do. Have you checked with any other inspect tool if it also does not see anything (best with the original inspect.exe)?

**Comment by Geograd** [comment]
It probably doesn't. I doubt they had in mind for someone to use automation with their software, which is why we are trying to make it work to make their lives easier lol. So I would have to activate/focus on the element to have the UIA be able to see it then right? So I'll have to figure out how to use the keyboard keys or a mouse click to get down to those elements and work through them. Thanks for the info!

**Comment by Geograd** [comment]
In an unrelated question. Is there an easy way to detect when a popup window inside of an application occurs? Like how do I detect when focus is taken away from the main window?

**Comment by Roemer** [comment]
Yes, if there is no accessibility support, you need to use mouse with coordinates, keyboard, screenshots (and OCR) to automate it.
For the focus: You can try the `FocusedElement()` method or periodically check if there is a control of type `Window` in your process which is modal or has a specific title or something.

**Comment by Roemer** [comment]
I'll close this. If you have further questions please raise additional issues.
