### ISSUE TITLE
PropertyNotSupportedException when searching by XPath and elements without ControlType in search path.

### ISSUE THREAD

**Issue by lukasvogel** [Roemer/FlaUI#170]
Hi guys,
I'm currently trying to automate Paint. Unfortunately, Microsoft's Ribbon UI seems to have Control Elements that do NOT have a control type, as can be seen in FlauInspect:

![grafik](https://user-images.githubusercontent.com/1242460/40912638-75081132-67f2-11e8-9cf9-1b3cd490e0a1.png)

If I now try to select an element by XPath that is below one of those elements like this:
```
//Button[@Name='Pinsel']
```

I get the following exception:
```
FlaUI.Core.Exceptions.PropertyNotSupportedException: The requested property 'ControlType [#30003]' is not supported
   bei FlaUI.Core.FrameworkAutomationElementBase.GetPropertyValue[T](PropertyId property)
   bei FlaUI.Core.AutomationElementXPathNavigator.get_LocalName()
   bei MS.Internal.Xml.XPath.XPathAxisIterator.get_Matches()
   bei MS.Internal.Xml.XPath.XPathDescendantIterator.MoveNext()
   bei MS.Internal.Xml.XPath.DescendantQuery.Advance()
   bei MS.Internal.Xml.XPath.FilterQuery.Advance()
   bei MS.Internal.Xml.XPath.XPathSelectionIterator.MoveNext()
   bei FlaUI.Core.AutomationElements.AutomationElement.FindAllByXPath(String xPath)
   bei WindowsAutomation.Application.FindMatchingElements(IEnumerable`1 windows, Func`2 findFirst, Func`2 findAll, Boolean ensureExclusive, Boolean returnAllMatches) in C:\Users\(...)\Application.cs:Zeile 167.
   bei WindowsAutomation.Application.GetElementsByXpath(String xpath, Boolean ensureExclusive, Boolean returnAllMatches) in C:\Users\(...)\Application.cs:Zeile 120.
   bei FlaUI.Core.Tools.Retry.While[T](Func`1 retryMethod, Func`2 checkMethod, Nullable`1 timeout, Nullable`1 interval, Boolean throwOnTimeout, Boolean ignoreException, Boolean lastValueOnTimeout, T defaultOnTimeout)
   bei FlaUI.Core.Tools.Retry.WhileEmpty[T](Func`1 checkMethod, Nullable`1 timeout, Nullable`1 interval, Boolean throwOnTimeout, Boolean ignoreException)
   bei WindowsAutomation.Application.GetElements(String xpath, Double timeout, Boolean ensureExclusive, Boolean returnAllMatches) in C:\Users\(...)\Application.cs:Zeile 59.
``` 

I've also found the offending lines of code in FlaUI:

https://github.com/Roemer/FlaUI/blob/0de6187d255e42ffcf9d7dae86696ddd3004c44e/src/FlaUI.Core/AutomationElementXPathNavigator.cs#L59

This obviously fails if an Element has no control type. 
Is it possible to add a fallback, like "NotSupported", "NoControlType", or something like that?

I can submit a pull request but I'm not sure what an agreeable name would be.

Thanks for all your work!

**Comment by Roemer** [comment]
Hi Lukas
I also stumble uppon this problem from time to time. Can you try to get more information about those "invisible" controls with another inspect tool like UIAVerify or Inspect?
The fix would probably be to use `TryGetValue` in the `ControlType` and return  `NotSupported` in that case. Or maybe even extend `ControlType` and add a default that is `NotSupported` which would be used in that case (which would also go partially into #121).

**Comment by lukasvogel** [comment]
Hi,
according to UIAVerify, its actually one (instead of the two shown?) custom element:

![grafik](https://user-images.githubusercontent.com/1242460/40920604-5ce07b74-680d-11e8-9fa1-53d934998778.png)

I'll try to investigate further...

**Comment by Roemer** [comment]
I think I remember that UiaVerify defaults to "Custom" if the control type is not supported which is actually not correct.
I accepted your PR with the Unknown type.
