### ISSUE TITLE
Can't access LocalizedControlType?

### ISSUE THREAD

**Issue by Geograd** [Roemer/FlaUI#175]
I'm trying to access the LocalizedControlType of a window to check to see if it's Dialog, but I can't seem to access this field in my code. Was this not added or am I doing it wrong?

`AutomationElement acvtiveWindow = automation.FocusedElement();`
`if(activeWindow.LocalizedControlType == LocalizedControlType.Dialog)`

**Comment by Roemer** [comment]
What kind of error do you get? Also I suggest using the ControlType (enum) instead of the LocalizedControlType because then it is independent of system language.

**Comment by Roemer** [comment]
Closed due to inactivity. Please re-open in case this is still an issue.
