### ISSUE TITLE
How to get text foreground color using FlaUI

### ISSUE THREAD

**Issue by YadaGiriReddy** [Roemer/FlaUI#176]
could somebody provide any example on how it can be performed

**Comment by Roemer** [comment]
Theoretically there are `Text Attributes` that should provide that information:
https://docs.microsoft.com/en-us/windows/desktop/winauto/uiauto-textattributes#text-color-attributes
FlaUI has all those implemented as well but I never tried them.

**Comment by jmbeach** [comment]
@Roemer, why does `GetSupportedPatterns` only return "SynchronizedInput" for labels? I thought it would return `Text` or `Text2`.

I'm testing by putting this code in the `LabelTests.cs` GetText Test:

```
var label = window.FindFirstDescendant(cf => cf.ByText("Test Label")).AsLabel();
var patterns = label.GetSupportedPatterns();
```

**Comment by jmbeach** [comment]
interestingly, it seems to work with textboxes

**Comment by Roemer** [comment]
For elements that support the `TextPattern`, it would look like this:
```csharp
var pattern = textBox.Patterns.Text.Pattern;
var foreColorInt = (int)pattern.DocumentRange.GetAttributeValue(TextAttributes.ForegroundColor);
var backColorInt = (int)pattern.DocumentRange.GetAttributeValue(TextAttributes.BackgroundColor);

var foreColor = System.Drawing.Color.FromArgb(foreColorInt);
var backColor= System.Drawing.Color.FromArgb(backColorInt);
``
And yes, the `Label` does not support that pattern. You could create your own label that supports that pattern.

**Comment by tomaszlachgc** [comment]
Is there another way to get the Attributes than using Patterns?
Unfortunately in FlaUInspect I see that objects that I am testing do not use the TextPattern or basically any other patterns.
