### ISSUE TITLE
FlaUI Controls Support

### ISSUE THREAD

**Issue by Vasanthkvr** [Roemer/FlaUI#177]
Hi,

Let me know the FlaUI has the support for the following controls.

1) ControlType.Calendar
2) ControlType.SplitButton
How to use the ListView. From my understanding i used it (AsGrid).

**Comment by Roemer** [comment]
In general yes. Possibly there are some missing wrappers for easy access but the basic `AutomationElement` can be used and all available patterns / properties can be accessed. If you do a wrapper around those, a PR would be welcomed.

**Comment by Vasanthkvr** [comment]
Hi,

Is FlaUI missing the  "CoreAppXmlConfiguration" used in Test Stack White.

**Comment by Roemer** [comment]
`CoreAppXmlConfiguration` is just a settings class from White. FlaUI does not need that.

**Comment by Vasanthkvr** [comment]
thanks

**Comment by Roemer** [comment]
Closed due to inactivity. Please re-open in case this is still an issue.
