### ISSUE TITLE
Feature request: Click and Drag to a specified point, rather than some distance horizontally or vertically

### ISSUE THREAD

**Issue by NotGeoff** [Roemer/FlaUI#181]
Hi,
I feel it would be helpful to add functionality to click and drag from a specified point to another specified point. It should look something like:

`Mouse.DragTo(MouseButton.Left, window.FindFirstDescendant(x => x.ByName("Drag Me")).GetClickablePoint, window.FindFirstDescendant(x => x.ByName("Put It Here")).GetClickablePoint);`

**Comment by NotGeoff** [comment]
After 5 minutes of research, I've determined I can use Mouse.Down, Mouse.MoveTo, and Mouse.Up.

**Comment by Roemer** [comment]
There is acutally a `DragHorizontally`, `DragVertically` and `Drag` method in the `Mouse` class.
