### ISSUE TITLE
Guide lines to include custom objects

### ISSUE THREAD

**Issue by RicardoBA** [Roemer/FlaUI#182]
Hi all!.

I need some guide lines about how can I make that FlaUI were able to read custom objects. FlaUI is able to work with native Microsoft objects, radio buttons, textboxes, checkboxes, etc. but I need to add custom objects defined at a dll. Has FlaUI the ability to read custom objects?. 

Thanks in advance.

Regards

**Comment by Roemer** [comment]
Can you define a `custom object`? You mean like implementing a custom UIA provider / Automation Peer? Or just a `custom control` which is built uppon various default elements?

**Comment by RicardoBA** [comment]
mmm, I think the second option. I have a dll file that contains multiple customs objects. These objects are a mix of textbox, icons, etc. FlaUI inspector does not recognize them. These objects have several methods and properties that allow their control. That's I want to do. To include that dll and  make FlaUI able to interpret that object.

Thanks

**Comment by Roemer** [comment]
FlaUI does not work like that. FlaUI uses the Windows Automation API to control Windows controls.
So if your controls expose the Windows Automation API, FlaUI works. How are the controls made? What does FlaUInspect show? Is there a way to provide me that DLL and maybe also the source code of it?

**Comment by RicardoBA** [comment]
Hi Roemer. 

After dealing with this issue internally, we believe that the option of implementing a custom UIA provider / Automation Peer is the way to do what we want. We will investigate this and later maybe contact you again.

Thank you very much

P.S.: Any help will be welcome

**Comment by Roemer** [comment]
Cool, it should be pretty easy to implement a custom AutomationPeer. Here's a post of someone who added a `ValuePattern` to his controls: #199
