### ISSUE TITLE
Element not associated to window

### ISSUE THREAD

**Issue by pavlikpatrycja** [Roemer/FlaUI#189]
Hi, after click on button in widows forms application appear ManuItem, which isn't associated to any window. Is there any way to find this element and click on it? Screenshot from FlaUInspect below. ProcessId is the same. 
![2018-08-09_10h50_32](https://user-images.githubusercontent.com/14920046/43888664-817c0942-9bc2-11e8-9a50-7b44b2664ed5.png)

**Comment by Roemer** [comment]
Are you sure it's a WinForms application and not a Win32 application? This is usually the behavior or Win32 applications.
Anyway, look at https://github.com/Roemer/FlaUI/wiki/ContextMenu. There is a special handling for Win32 menus / context menus. In case it does not automatically work correctly, you can try 
```var menu = mainWindow.GetContextMenuByFrameworkType(FrameworkType.Win32);```

**Comment by pavlikpatrycja** [comment]
I tried this but menu is null for FrameworkType.Win32 as well as for FrameworkType.WinForms

**Comment by Roemer** [comment]
👍
