### ISSUE TITLE
Moving from White to FlaUI documentation

### ISSUE THREAD

**Issue by Sl1ckR1ck** [Roemer/FlaUI#190]
Hi, 
Im a very new user of White, ive been using it for 2-3 days and it it very easy to use.

While reporting an issues, i notice many comments in other issues that FlaUI will be the replacement to White and that White will become obsolete.

So obviously i decided to move to FlaUI to avoid a transition phase before i start doing to many tests.

So i started to adapt my code to use FlaUI instead of White. I found that the API change is rather similar but behavior wise seems quite different and im having a hard time making my test pass.

The search of the controls and windows seems quite different now since the test is not able to find them (always).

Only when i go in debug mode and do step by step slowing it works. Obviously i tried to put Retry and other statements but it seems like it doesn't work always.

I was wondering that maybe im doing something wrong and that a howto move documentation would be useful.

**Comment by Roemer** [comment]
Hi
Good you give FlaUI a try as White is not maintained anymore as it has too many design problems. Yes things are different in FlaUI. It does much less "magic" and gives all the control to the programmer. One of the things is that FlaUI does not do retries automatically, you need to do them yourself (that's what the Retry class is for). Can you show me some code that fails? Usually you should choose the right retry and then the tests get rock  solid.

**Comment by Sl1ckR1ck** [comment]
Hi Roemer, thanks for replying so quickly. 

I was using this code to extract the main window:
`
        Private Shared Function GetWindow(ByVal title As String) As AutomationElements.Window
            Return Retry.While(Of AutomationElements.Window)(Function()
                                                                 Return m_application.GetAllTopLevelWindows(m_automation).FirstOrDefault(Function(w) w.Title.Contains(title))
                                                             End Function,
                                                             Function()
                                                                 Return m_application.GetAllTopLevelWindows(m_automation).FirstOrDefault(Function(w) w.Title.Contains(title)) Is Nothing
                                                             End Function, TimeSpan.FromSeconds(5))

        End Function

        Public Shared ReadOnly Property MainWindow As MainWindow
            Get

                'Dim window = GetWindow("SESResultsViewer - ")
                Dim window = Retry.While(Of AutomationElements.Window)(Function()
                                                                           Return m_application.GetMainWindow(m_automation)
                                                                       End Function,
                                                             Function()
                                                                 Return m_application.GetMainWindow(m_automation) Is Nothing
                                                             End Function, TimeSpan.FromSeconds(30))
                Return New MainWindow(window)
            End Get
        End Property
`

This code returns a MainWindow but it seems the wrong one, the controls are not found.

If i use the commented line (GetWindow method) it works fine.

Hopefully with FlaUI my issue listed in White will be resolved (finger crossed)
https://github.com/TestStack/White/issues/615
(if you have any change to take a quick look)

**Comment by Sl1ckR1ck** [comment]
Also one small comment if i may, why there no automatic retry? 

i notice that my existing code fails if i remove the mouse animations (i use the mouse movement to allow to automate video recording). Surely this is because the actions are executed before my controls have time to load.

I like the auto retry from white, it made the code cleaner.

With FlaUI, ill have to encapsulate all my .Findxxx code with retry. Im ok with this, but would crow the code a lot more, im wondering why this decision was made? White was lighting fast even with those retry

**Comment by Roemer** [comment]
First about the automatic retry:
There are cases where you expect the item to be there or not and don't want to spend time waiting as it is either there or not. Having retries everywhere slows down the execution.
Another issue is that retries can be very different. Just look at the possible parameters in the retry class. Are exceptions allowed? Should it return a default? Should it return the last successfull value when exceptions occur? Should it throw when the timeout is reached? So many possibilities and I didn't want to add all those parameters into the `Find` methods, hence the separate `Retry`.
I actually get that complaint a lot. I'm still a bit unsure if I should provide `FindXXXWithRetry` methods or go back to add a nullable `TimeSpan`  parameter to the find methods (indicating to retry when it is not null). In any way, you're free to create your own Find methods with an integrated retry for now.

Back to the MainWindow:
Have a look at https://github.com/Roemer/FlaUI/wiki/Common-Issues
There I mention that the processes MainWindow can be instable and it might be better to use `app.GetAllTopLevelWindows(automation)[0]` or even searching for a window with a specific title.

**Comment by Sl1ckR1ck** [comment]
Thanks Roemer, 

Thank you for the explanation about the Retry, it makes a lot of sense.

For the MainWindow, indeed i saw this in the common-issues, this is why i used the GetAllTopWIndows instead :)

Although the bug i stated in White is present in FlaUI too :( I know its a twisted case but it is blocking me right now :(. I can open a different issue here if you prefer.

**Comment by Roemer** [comment]
Did you try finding the window with Inspect/FlaUInspect/UIAVerify?

**Comment by Sl1ckR1ck** [comment]
Ok, i got it from the desktop. Thank you so much for your help!

**Comment by Roemer** [comment]
Cool 👍 Feel free to post issues as you find them. Also make sure you're using the latest pre-release (release candidate) of FlaUI as there are a lot of changes/improvements.

**Comment by sriramperumalla** [comment]
Hello @Roemer ,
Good Day!! Coming to the point, in our test automation, we use white framework to automation our desktop application installation and configuration (post installation UI operations) of our application and click on various elements like fly button (...), clicking ok on dialog boxes and execute buttons etc.. to run desired piece of code behind the scenes. Unfortunately, our custom installation code that calls white framework and its UI Automation libraries fails to install our desktop application several times with 3 successful attempts out of 10 attempts to install our desktop application for unknown reasons. Is it a good idea to move to FIaUI to overcome these challenges and automate our desktop application installation and configuration?
Please suggest.
Cheers,
Sriram

**Comment by Roemer** [comment]
Hi @sriramperumalla 
FlaUI provides you several benefits over White: It is maintained, it supports UIA2 and UIA3, it is extensible, it supports all native UIA features, ...
Some of the problems you might face is that White is UIA2 and UIA3 might be more stable in your scenario. Also FlaUI proviedes many helper methods for waiting or retrying which also help in many cases. So feel free, try FlaUI and if you have issues, get back to me here with issues or on gitter.

**Comment by sriramperumalla** [comment]
Hi @Roemer ,
Thanks for the quick reply.Much appreciated.We are also evaluating WinAppDriver and appium combo to achieve the same. What would you suggest? To go for FlaUI  or WinAppDriver and appium?
Thanks,
Sriram

**Comment by Roemer** [comment]
With WinAppDriver you are fairly limited in what you can do. FlaUI provides you with everything from the underlying UIA and also provides you even the native UIA objects in case you need it so FlaUI is much more powerfull. Also WinAppDriver only runs on Windows 10 as far as I know. And WinAppDriver is not open source so it cannot be extended.

**Comment by sriramperumalla** [comment]
> With WinAppDriver you are fairly limited in what you can do. FlaUI provides you with everything from the underlying UIA and also provides you even the native UIA objects in case you need it so FlaUI is much more powerfull. Also WinAppDriver only runs on Windows 10 as far as I know. And WinAppDriver is not open source so it cannot be extended. Oh and also Developer Mode in Windows seems to be needed to run it, which is sometimes not possible due to company constraints.

Hi @Roemer ,
Thanks for the response. I got exactly what I needed. I was looking for an opensource tool which I can have complete control on with out using proprietary tools to play with windows desktop applications. I will work on a pilot project to automate our desktop application with FlaUI libraries. I may ask your for suggestions during my implementation.One question is that since our desktop application installer is an exe file,we need to install it through command line. Does FlaUI libraries provide the API to trigger the exe file via command line or should I use  paexec.exe to run the command with my C# code?
Cheers,
Sriram

**Comment by Roemer** [comment]
@sriramperumalla Feel free to contact me. For simple hints or help, use the gitter forum. For issues, use the github issues. Regarding the installer, please elaborate more (preferably on gitter) on how you need it as I don't understand your setup. Usually you have an executable with an UI you want to test, so you just run the executable and run the UI tests on the ui.

**Comment by sriramperumalla** [comment]
Hi @Roemer,
Though our exe file opens up UI wizard to perform installation,it is built to support command line options to perform silent installation.I am asking about this whether FlaUI has libraries/API that support silent installation of executables with command line options. Once the application is installed, I will FlaUI to perform UI testing of all features.

**Comment by RajathHcJain** [comment]
Hi @Roemer ,

Can we use FlaUI in Linux ?
