### ISSUE TITLE
Inquiry: Support for electron apps

### ISSUE THREAD

**Issue by hkoelewijn** [Roemer/FlaUI#191]
I used Flaui to automate browser applications. Electron apps are basically browser apps that run in Chromium. Do you know if it is possible to automate them using Flaui?

**Comment by Roemer** [comment]
Windows UI Automation is not the best in testing web applications. Selenium might be better. Anyway you can look at https://github.com/Roemer/FlaUI/wiki/FAQ `Can FlaUI be used to automate Chrome?
` and see if that helps.
