### ISSUE TITLE
How to get the  Windows Desktop Application elements by Mouse Point?

### ISSUE THREAD

**Issue by numver** [Roemer/FlaUI#192]
![image](https://user-images.githubusercontent.com/9836372/44028516-b4d1977c-9f2c-11e8-9d7a-95906e8447d1.png)

For example, I want to get the element  named "IntelliJ IDEA 2017.2.4 x64" by Mouse Point on the desktop.
![image](https://user-images.githubusercontent.com/9836372/44028644-1189b634-9f2d-11e8-879b-cefeaa4ce684.png)

but I use the code "new UIA3Automation().FromPoint(Mouse.Position)" to get the  Windows Desktop Application element , but it return the Desktop element to me,like this

![image](https://user-images.githubusercontent.com/9836372/44028731-73dd5d4a-9f2d-11e8-92db-1f048d756f6b.png)

**Comment by Roemer** [comment]
Could you solve it? If not, does FlaUInspect and the `Hover Mode` work correctly?

**Comment by numver** [comment]
sometime  I want to get the close button on desktop window or  ie explorer.
![image](https://user-images.githubusercontent.com/9836372/45672320-7178e800-bb5a-11e8-923c-1cbe13627889.png)
![image](https://user-images.githubusercontent.com/9836372/45672330-789ff600-bb5a-11e8-987b-59dfbba4ad4c.png)

I use the code "new UIA3Automation().FromPoint(Mouse.Position)" or FlaUInspect to get the close button, but it can not get the real element for me .

Now, I just only traverse the nearest element through mouse coordinates to get the real element .
Do you have a more convenient way to get those elements? @Roemer

**Comment by numver** [comment]
> Could you solve it? If not, does FlaUInspect and the `Hover Mode` work correctly?

My laptop is the 4K screen，Screen resolution affects the way to get elements.

**Comment by 643364103** [comment]
> 

Hello ,How to get the nearest element through mouse coordinates?

**Comment by parvez-ahamad-shaik** [comment]
I am having same issue. new UIA3Automation().FromPoint(Mouse.Position) is not fetching real element
