### ISSUE TITLE
Find a Custom Control with FlaUI

### ISSUE THREAD

**Issue by kevinheyvaert** [Roemer/FlaUI#199]
Dear,

I am wondering if I can find a custom control with FLaUI. I have a custom usercontrol in WPF which has a property with a list of custom objects (say a list of graph objects.) Is it possible to get with FlaUI to get that custom usercontrol and then that list? I looked around already in the code but not sure were to start. I think to make a custom cast of somekind then? Or is it not possible at all?

**Comment by Roemer** [comment]
Depending on the custom control, you can just use it with the basic `AutomationElement` and use all the patterns / properties you need. Of course you can also create your own class, inherited from `AutomationElement` which nicely provide the supported patterns/properties. Easiest is to first check what patterns and properties the custom element exposes with any inspect tool like FlaUInspect.

**Comment by kevinheyvaert** [comment]
The FlaInspect tool only gives me that it is a custom control with the excepted ClassName. No other properties that I need. So I have to remake my custom control in the FlaUI code, in herited from AutomationElement, and then set my list of graph objects as a property? Just asking, my code knowledge is not that great. So in FLaUI.Core adding my own class for my custom control?

**Comment by Roemer** [comment]
No supported patterns and no child controls? If so, then the custom control does not provide any UIA information. The control needs to implement/privide that automation/accessibility information, otherwise FlaUI (and other UIA based libraries like White) do not work.

**Comment by kevinheyvaert** [comment]
automation information to the custom control is added how? I see here things about AutomationPeer class (https://blogs.msdn.microsoft.com/patrickdanino/2009/11/11/custom-controls-and-ui-automation/) and using of GUID's to identify the property with server/client (https://blogs.msdn.microsoft.com/winuiautomation/2010/12/07/uia-custom-patterns-part-1/) Not sure which one should be taken. Thanks already for the information

**Comment by kevinheyvaert** [comment]
I got  the Automation peer working with the following code:

This code is added to my custom control class: 
`protected override AutomationPeer OnCreateAutomationPeer()
      {
         return new GraphControlAutomationPeer(this);
      }`

and made this class which implements the Value pattern: 
`public class GraphControlAutomationPeer : FrameworkElementAutomationPeer, IValueProvider
   {
      private string _currentValue = "TestValue";

      public GraphControlAutomationPeer(GraphControl owner) : base(owner)
      {

      }

      protected override AutomationControlType GetAutomationControlTypeCore()
      {
         return AutomationControlType.Custom;
      }

      protected override string GetClassNameCore()
      {
         return Value.GetType().Name;
      }

      public override object GetPattern(PatternInterface patternInterface)
      {
         if (patternInterface == PatternInterface.Value)
         {
            return this;
         }
         return base.GetPattern(patternInterface);
      }

      public string Value
      {
         get
         {
            return _currentValue;
         }
      }

      public bool IsReadOnly
      {
         get
         {
            return false;
         }
      }

      public void SetValue(string value)
      {
         //parsing of the values
         this._currentValue = value;
      }
   }`

When I run a test WPF in debug mode with the custom control (GraphControl), the value and pattern is seen in the inspect tool. 
![captureinspect](https://user-images.githubusercontent.com/3530438/44660502-1004a400-aa08-11e8-83eb-136b418256f1.PNG)

When I place the same custom control in a larger project 
and run that .exe of that project, value and custom control is not seen. Does anyone has an idea why its not displayed?
