### ISSUE TITLE
Implement SetTransparency

### ISSUE THREAD

**Issue by lanzorg** [Roemer/FlaUI#2]
Some other ui automation wrappers/frameworks have this feature:
- https://github.com/mmarquee/ui-automation/blob/master/src/main/java/mmarquee/automation/controls/AutomationWindow.java#L230
- https://github.com/pywinauto/pywinauto/blob/master/pywinauto/controls/HwndWrapper.py#L1251

**Comment by Roemer** [comment]
Implemented in commit 352b18daa67255d4e9bfc3cdd9606216fe364d90
