### ISSUE TITLE
bring back BoundingRectangle.Center

### ISSUE THREAD

**Issue by bitbonk** [Roemer/FlaUI#200]
In 2.0 there is no more `Center` property on `AutomationElement.BoundingRectangle`. Probably because you moved to `System.Drawing.Rectangle`. This was very handy when I had to click on things that do not appear as clickable (`.GetClickablePoint()` throws an exception) but actually are. This happens quite frequently in our UIs and I would expect that this somewhat common scenario. So I suggest you bring back the `Center` property or something equivalent (extension method for `System.Drawing.Rectangle`).

An alternative would be that `GetClickablePoint()` uses  the center of the BoundingRectangle as a fallback if no clickable point was found.

**Comment by Roemer** [comment]
Didn't notice that went missing but absolutely makes sense to have an extension method and maybe even use it as fallback as you mentioned.

**Comment by Roemer** [comment]
This is implemented in `FlaUI.Core.Tools.ExtensionMethods`.
