### ISSUE TITLE
Strong Name of the FlaUI .dll's

### ISSUE THREAD

**Issue by kevinheyvaert** [Roemer/FlaUI#205]
I have a question about the dll's received from the Nuget packages (2.0 rc1). Are these strong named?
I need these in a project but get always this error : `System.IO.FileLoadException : Could not load file or assembly 'FlaUI.Core, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. A strongly-named assembly is required. (Exception from HRESULT: 0x80131044)` 

I tried to strong name the dll's with ildasm.exe and ilasm.exe but with the assembly again i get a *FAILURE*. Did not found the error. Can these be officially  strong named by you? Or should this be done by the users?

**Comment by Roemer** [comment]
No they are not. But there are `*.Signed` assemblies on nuget which are signed ;)
