### ISSUE TITLE
Is there a way to get the Content or Text value of a TextBlock via FlaUI?

### ISSUE THREAD

**Issue by kev24uk** [Roemer/FlaUI#214]
I have tried using the .AsTextBox() method and checking the Text property on this to no avail, but couldn't think of another way to potentially get this>

**Comment by kevinheyvaert** [comment]
You can use AutomationElement.Name to get the value of a textbox. Just search the element on ID. Or you can extend the textbox class with an AutomationPeer. An example can be found here: https://github.com/Roemer/FlaUI/issues/199
