### ISSUE TITLE
How UIA3Automation initialize adding ConditionBase？

### ISSUE THREAD

**Issue by oncefrom** [Roemer/FlaUI#218]
Can UIA3Automation. FromPoint use ConditionBase?

As shown in the figure, I made the form layer to hide the elements that I wanted to get under the mask layer through FromPoint.

![image](https://user-images.githubusercontent.com/22267592/49062184-28c26700-f24e-11e8-85f7-0270e3effd4a.png)

**Comment by Roemer** [comment]
`FromPoint` is unfortunately a framework method which does take any conditions. Best you can probably do is loop thru all the elements and check if they are below the cursor. Maybe you can explain a bit more what you want to achieve?

**Comment by oncefrom** [comment]
I want to use WPF Window to make an Element mask layer, but I have encountered an Element that PromPoint always gets to the mask layer, and I can't get the Element blocked by the mask layer.

**Comment by Roemer** [comment]
Closed due to inactivity. Feel free to re-open if the problem is still not solved.
