### ISSUE TITLE
Create Win32 test application

### ISSUE THREAD

**Issue by Roemer** [Roemer/FlaUI#22]
Is this needed? There are some things which are different so it could make sense to have one.

**Comment by Nihilium** [comment]
Hello Roemer,

I'm just be working with C# 2008 (I need this works in Win XP). I have lot experience programing but i'm be new with C#. So, you can help me making a little project with C# 2008? This is possible to works with Win XP?

Regards.

**Comment by Roemer** [comment]
According to your text it is fairly unclear what you want. In any case you're very wrong here. If you want to learn C#, ask google, there are millions of resources for that. If you want to automate your application, you can use FlaUI (even with Win XP). If you need help with that, go to the gitter chat of FlaUI. If you have issues, post new issues.
Regards

**Comment by Roemer** [comment]
I'll close this as this is not really worth the effort.
