### ISSUE TITLE
cannot convert from 'FlaUI.Core.Conditions.AndCondition' to 'FlaUI.Core.Conditions.PropertyCondition'

### ISSUE THREAD

**Issue by greyivy** [Roemer/FlaUI#230]
Hi all,

When running the below code, I get the following error:

`cannot convert from 'FlaUI.Core.Conditions.AndCondition' to 'FlaUI.Core.Conditions.PropertyCondition'`

```
AutomationElement.FindFirst(
  TreeScope.Subtree, 
  AutomationBase.ConditionFactory.ByClassName("UIItem")
    .And(AutomationBase.ConditionFactory.ByName("Downloads"))
)
```

Am I doing something wrong? This looks correct to me based on the source and the documentation.

Thanks so much!

**Comment by Roemer** [comment]
Are you sure the error is on that line? Also does it fail on run-time or compile time? What version are you using?
The following code works great on my side:
```csharp
using FlaUI.Core;
using FlaUI.Core.AutomationElements;
using FlaUI.Core.Definitions;
using FlaUI.UIA3;

var automation = new UIA3Automation();
var el = automation.GetDesktop();

el.FindFirst(TreeScope.Subtree, automation.ConditionFactory.ByClassName("UIItem").And(automation.ConditionFactory.ByName("Downloads")));
```

**Comment by greyivy** [comment]
Ah, I was using a parameter of the PropertyCondition type in a function and Roslyn was giving me the wrong line numbers. My bad, thanks so much for replying!
