### ISSUE TITLE
Cannot find buttons in inspect

### ISSUE THREAD

**Issue by Jason66Wang** [Roemer/FlaUI#233]
Hi Everyone,

I am currently using UIA2 to test a winforms application. Everything works well, but after I perform a close window action, I couldn't find buttons belong to another window. For example, I click a link to open a window called "Location", then I click a button belong to Location to open another window called "Alarms". Now I close the "Alarms" window, I will be back to the location window, I can still see those buttons in the location window, however, in the inspect it doesn't have any buttons. I have tried to only switch back to location window as well, however, it still doesn't show any buttons.

![Capture](https://user-images.githubusercontent.com/26193826/54965185-85971980-4fc3-11e9-9f77-28cea6ca531b.PNG)

Regards,
Jason

**Comment by lanzorg** [comment]
Did you try with [FlaUInspect](https://github.com/FlauTech/FlaUInspect)?

**Comment by Jason66Wang** [comment]
> Did you try with [FlaUInspect](https://github.com/FlauTech/FlaUInspect)?

I did, it showed the same information(Couldn't find the buttons). I have accomplished my task by using ideas from #136 (Get the buttons' coordinates before click any other links, and move the mouse to those coordinates and then perform a mouse left click). However, I still wanna find out what causes the buttons to disappear if it is possible.

**Comment by Roemer** [comment]
You solved it by using the mouse which is fine. UIA is full of bugs, especially in WinForms. You could also try UIA3 on your application, maybe it is more stable for your application. If the UIA provider does not provide the correct information, there's nothing FlaUI can do.
