### ISSUE TITLE
Flaui can't recognize String grid

### ISSUE THREAD

**Issue by erickmazzocco** [Roemer/FlaUI#234]
I'm using FlaUI to automate a system made in Delphi 6. Practically everything works perfectly except for the capture of grids.

The grid is of type Pane and .asgrid () does not work having all options related to grid returning exception, such as rows, headers, etc.

Any suggestions on how to manipulate a TDBAdvStringGrid grid made in Delphi?

![flaui](https://user-images.githubusercontent.com/26230705/56162138-a8ed2d00-5fa1-11e9-9bfe-1dd5e43a8e94.png)

**Comment by Roemer** [comment]
I suspect that the creators of the `TDBAdvStringGrid` did not implement UIA correctly (or at all) for their grid. You might try to contact the creators of `TDBAdvStringGrid` to verify this.
If that is the case, your only possibility is to use `Keyboard` and `Mouse` and `Capture` to interact with the grid.

**Comment by erickmazzocco** [comment]
I understand. Thanks for the feedback Roemer
