### ISSUE TITLE
Issue with Fetching rows from the DevExpress grid with FlaUI

### ISSUE THREAD

**Issue by jyothitangirala** [Roemer/FlaUI#243]
Hi @Roemer,
 I have a devexpress grid and am using FlaUI for automation. It has support for Grid pattern.From the FlaUIInspect i could not find the datapanel loaded. It is always showing the header panel loaded   with childitems but the datapanel is showing empty often.
I have tried with other inpsect tools as well same is the case. Below is the screenshot from FlaUIInspect.

Below is the code that i am using
var dataPanel = grid.FindFirstDescendant(cf => cf.ByAutomationId("dataPresenter"));
 var dataRows = dataPanel.FindAllChildren();

It is often returning 0 rows whenever is it is not visible in the inspect tool.I tried relize items code 
 var gridPattern = grid.Patterns.Grid.Pattern;
            ItemRealizer.RealizeItems(grid);
            var items = grid.AsGrid().Rows;
Datarows are being scanned by the tool and after that am still getting items count as zero.
Am i missing something. My application is full of devexpress grids.Any help would be appreciated.

Thanks,
Jyothi

![Devexpressgrid issue](https://user-images.githubusercontent.com/49689190/57684088-01f5c280-762d-11e9-8d1e-eda8e46321cd.jpg)

**Comment by jyothitangirala** [comment]
Finally The issue is solved by adding these two line in the client code.
 ClearAutomationEventsHelper.ClearAutomationEvents();
 ClearAutomationEventsHelper.IsEnabled = false;

This has solved all the inconsistency issues that i am facing :)

**Comment by TheBlueEye** [comment]
ok,i will try,thank you!

---Original---
