### ISSUE TITLE
Error when compiling FlaUIRec

### ISSUE THREAD

**Issue by bonibom** [Roemer/FlaUI#247]
The type or namespace name 'Shapes' does not exist in the namespace 'FlaUI.Core' (are you missing an assembly reference?) insrc\FlaUIRec\Views\MainWindow.xaml.cs Line 46

Reference to FlaUI.Core is added so could you please describe what a solution for this issue?

**Comment by Roemer** [comment]
This is fixed as soon as I merge the .NET Core branch.

**Comment by Roemer** [comment]
It is fixed now that the recorder is moved to it's own repo: https://github.com/FlaUI/FlaUIRec
