### ISSUE TITLE
Retry.While not working on latest version of FlaUI

### ISSUE THREAD

**Issue by manuelrodriguezGL** [Roemer/FlaUI#250]
Hi,

I'm not able to get Retry.While working. I liked the previous Retry version (WhileEmpty for example) , but this one is giving me some headaches.
Could you please update any of the examples with the new Retry version??

Thanks,

**Comment by yawnston** [comment]
What exactly isn't working for you? Could you provide a code sample of Retry not working?

**Comment by Roemer** [comment]
Please provide some details on what is not working for you.
There is some rudimentary documentation here: https://github.com/Roemer/FlaUI/wiki/Retry

**Comment by ilCosmico** [comment]
I get an issue with it too. 
It seems that the same condition run with Retry methods never succeed.

![RetryIssue](https://user-images.githubusercontent.com/8678145/68286640-b96e0d80-0081-11ea-8657-74f269d8f466.jpg)

**Comment by Roemer** [comment]
@ilCosmico 
In your example, you are retrying while the condition is true. And as you see in `result1`, it is true (which means the element exists). So you are retrying as long as the element exists. If it exists for more than 5 seconds, the retry will timeout. So it seems correct to me or not?

**Comment by ilCosmico** [comment]
Yeah, you're right... my fault, sorry. So it seems to work fine :)

**Comment by Roemer** [comment]
Good to know :) I will close this as I did not see any problems. @manuelrodriguezGL if you need further assistance, feel free to re-open this ticket with further information.
