### ISSUE TITLE
Is the FlaUI project Still Active?

### ISSUE THREAD

**Issue by RoakyWood** [Roemer/FlaUI#257]
There have been no updates since April, is this Project Still Active?

**Comment by lanzorg** [comment]
What happens to the dotnet core support?

**Comment by Roemer** [comment]
Yes the project in general is active. There are a lot of things going on currently in the .NET world. When .NET Core 3.0 will be released, I will continue with my refactoring to support .NET Core.

**Comment by RoakyWood** [comment]
Wicked good, Roemer!

**Comment by lanzorg** [comment]
The stable version of .NET Core 3.0 is available!

**Comment by Roemer** [comment]
Yes, it is indeed. I actually am starting to work on it. First thing is to split out the interop wrapper (and also generate a new one with the latest features). That is in work here: https://github.com/Roemer/UIAutomation-Interop
Next I will need to define the new assemblys that are needed (I need at least one additional for stuff that is not available in .net core like Accessibility).

**Comment by RoakyWood** [comment]
@Roemer Can you please respond to issue #259 ?

**Comment by Roemer** [comment]
Please do not use other issues to enforce an answer on an unrelated issue.

**Comment by RoakyWood** [comment]
I beg you to kindly forgive my unpardonable breach of ettiquette.

_Avec mes respectueux hommages, je vous prie d’agréer, Monsieur, l’expression de ma considération la plus distinguée._

**Comment by Roemer** [comment]
No worries :) Just keep in mind that (as most open source) that the software is maintained in free time.
