### ISSUE TITLE
Run UI Test on a Remote Device Like WinAppDriver or Appium

### ISSUE THREAD

**Issue by RoakyWood** [Roemer/FlaUI#259]
In WinAppDriver, you can create a Windows Driver Object, pass it a URL/IP Address and port and the Target app and it will launch and run assuming the app exists in the  remote device.

Unless I'm reading the issues FAQ and other documentation incorrectly, is there a way in FlaUI to pass an IP address of a remote device?

Is there another technique for projecting a test to a remote device like WinAppDriver and Appium can do?

Scenario (using WinAppDriver)
- Local device runs Windows 10
- Remote device runs Windows 10
- Remote device has the target App installed
- Run WinappDriver on local and remote machine prior to launch of test
- Run a UI test from the local machine Desktop/Laptop 
- The UI Test executes against the target software on the remote device

**Comment by RoakyWood** [comment]
@Roemer Am I missing something in the documentation? If not, can you kindly let me know if this can run remote?

**Comment by RoakyWood** [comment]
Thanks, this lets me know what direction to take with my FlaUI Tests.

**Comment by RoakyWood** [comment]
Please close. See above

**Comment by Roemer** [comment]
If you do create some kind of remote wrapper, I would definitely be interested. An anlternative would be to create a wrapper that is added to Selenium (see #50)

**Comment by RoakyWood** [comment]
I was thinking some kind of mind-meld between FlaUI and WinAppDriver's capability of remoting. I'm going to take a look at the code.

**Comment by pradeipp** [comment]
@RoakyWood Any progress regarding this? I'd like to contribute in any way if something's in progress
