### ISSUE TITLE
Question: Future of FlaUI since microsoft dropping automated UI tests support

### ISSUE THREAD

**Issue by Sl1ckR1ck** [Roemer/FlaUI#263]
Hi there, this is not a bug but a general question regarding the future of FlaUI since microsoft is deprecated CodedUITest? 
https://devblogs.microsoft.com/devops/changes-to-coded-ui-test-in-visual-studio-2019/

Are you guys still going to continue to maintain and develop this library?

**Comment by pm90pl** [comment]
FlaUI doesn't have any in common with Coded UI (on a high level). FlaUI uses the infrastructure of Microsoft UI Automation. The successor of Coded UI (WinAppDriver) is also based on UIA.

**Comment by Roemer** [comment]
I just posted a question there if the underlying technology (UIA) will still be supported. I guess it will as their proposed alternative (WinAppDriver which in my opinion will never be good enough as it is limited by the Selenium API which is made for Browsers and not Desktop apps) is also based on UIA.

**Comment by Sl1ckR1ck** [comment]
That's great to hear. Let me know when they anwser you.
Thank you for you work you're doing here. It is very useful!

**Comment by pm90pl** [comment]
I'm sure that UIA will be maintained/developed because it's a core of accessibility features.

**Comment by Roemer** [comment]
As expected, there is no answer on my question. I will close this as FlaUI will still be a supported project until UIA is dropped (which is not the case currently).
