### ISSUE TITLE
How can I catch application exception?

### ISSUE THREAD

**Issue by h10ne** [Roemer/FlaUI#265]
When an exception is thrown on a form, the test is marked as passed. How to catch an exception on the form and make the test failed?

**Comment by kevinheyvaert** [comment]
Just look for the exception text in the dialog (exceptions are shown in seperate dialogs in my application). Or you can log all your actions of your applications when its running in a log file and look for the exception message in the log before you end your test.

**Comment by pm90pl** [comment]
Same as @kevinheyvaert - in our app an exception dialog is a special form (it's showed as a popup window). So, after each test I can look for an exception window and if I find this kind of form I'll make my test to fail.

**Comment by h10ne** [comment]
Thanx all for answers!
