### ISSUE TITLE
How can I use UIA2 and UIA3 together?

### ISSUE THREAD

**Issue by h10ne** [Roemer/FlaUI#269]
My test dont work together because first test I run with UIA3 and then use UIA2 to find and test comboBox element. This test work successfully, but when next test starting, I can't find a lot of elements. When I start tests separately, all work well

**Comment by Roemer** [comment]
That does unfortunately not work. Somehow the first UIA used in a process gets loaded into it and cannot be unloaded. So you need to run them in separate processes. I did the same with the FlaUI.UITests.

**Comment by h10ne** [comment]
Can you please add link to file where you did it? I cant find it :(

**Comment by Roemer** [comment]
Here is where I use a variable in the tests to determine if UIA2 or UIA3 is used:
https://github.com/Roemer/FlaUI/blob/be9d2b7d3c02856cbee1e3da8b34d7f91503b528/src/FlaUI.Core.UITests/TestFramework/TestUtilities.cs#L21

And here is where I invoke the tests (first with UIA2 then with UIA3):
https://github.com/Roemer/FlaUI/blob/be9d2b7d3c02856cbee1e3da8b34d7f91503b528/build.cake#L100
