### ISSUE TITLE
Completely white images on Capture (sometimes)

### ISSUE THREAD

**Issue by andyb1979** [Roemer/FlaUI#275]
Hello! 

I've just started using this excellent library in some UIAutomation tests. The tests start up an application, navigate to a certain page and take a screenshot. I then compare the screenshot vs. expected. 

Sometimes I'm finding the screenshot is completely white (blank). I dont know the cause if its my code or yours. Im wondering if you've seen such issues on a CI / server build so far -- that sometime the screen capture can be white. 

I will try to narrow down the problem some more to see if I can isolate it.

Best regards, 
Andrew

**Comment by Roemer** [comment]
What is the resolution of the screenshots? Is it right or unrealistic (like 1x1 pixels)? Usually when no desktop is available the go full black.

**Comment by andyb1979** [comment]
Hello!

No its a normal sized image, about 1,000 x 800. I cannot reproduce this
issue when UIAutomation Tests are run locally but for some reason when run
on build server, randomly (sometimes) the captured images are all white.

Im wondering if its an issue of the CI Build server (TeamCity)
Or perhaps the Capture method
or perhaps something else ...

I had the idea to force my app to save a screenshot via inter-process
communication and pick it up from disk, see if that helped. FYI I have
similar image capture tests not using FLAUI and these are working fine on
the same box.

Best regards,
Andrew

**Comment by andyb1979** [comment]
Im still investigating / trying to sort this out but I think the issue is related to this:

https://www.ranorex.com/forum/ui-tests-fail-when-run-from-teamcity-t12111.html
https://www.ranorex.com/forum/black-blank-screenshots-t11557.html

essentially, when running tests on a build server like TeamCity, the power management options and login of the build server are important or you can't take screenshots (you need an active desktop to do UIAutomation). 

We had already setup the TeamCity box to do this correctly for some other visual Unit tests maybe there's a server setting which is affecting the Capture method..

still investigating ...

**Comment by Roemer** [comment]
I'm really eager to see what you find out and if FlaUI can optimize something. I never had this problem (we usually use Jenkins for the CI).

**Comment by andyb1979** [comment]
Got a lot of problems with VS2019 / .NET Core 3 / teamcity and generally
flaky build and this is one of them. I'll do my best!

Another idea I had was to add interprocess communication to the .exe under
test to make it screenshot itself and pass the image back. If it's an FLA
problem that would solve it, but if teamcity or build server issue, it
would not

**Comment by andyb1979** [comment]
This seems to be stable now (still watching it). What I did was: 
 - Set power options to never sleep, screen never to go off 
 - Set login so that the default user always logs on https://www.groovypost.com/howto/automatically-sign-in-windows-10/
 - Set RDP to run minimised https://support.smartbear.com/testcomplete/docs/testing-with/running/via-rdp/in-minimized-window.html

it seems to be related with the PC losing the desktop / there being no graphics context sometimes. Still watching it...

**Comment by kevinheyvaert** [comment]
I had this issue also with TeamCity. Like proposed, I made it so the computer never is locked and that there is a user logged in + always a screen connected or use of HDMI dummy dongle to mimick a video signal to the PC so the FlaUI library can take screenshots. Otherwise I also had white screenshots.

**Comment by andyb1979** [comment]
HDMI dummy dongle is genius!! Thanks for sharing

The build agent server actually sits in my office (faster than a
cloud-rented machine) while TeamCity is cloud hosted, So I have access to
it - I can add an HDMI dummy dongle!

**Comment by kevinheyvaert** [comment]
@andyb1979 be aware, the cheap dongles from AliExpress dont always work. So I have cheap and a bit more expensive ones in stock when the cheap one dies

**Comment by andyb1979** [comment]
bought one. So far our build box is happy with the power-management and
sleep settings changes i made

**Comment by Roemer** [comment]
Keep in mind that if you RDP to a computer and close the RDP, it by default goes back to the lock screen. In that case you can use `tscon` (see https://github.com/Roemer/FlaUI/wiki/FAQ) to keep a user logged in or use a default user to login via registery (I guess that is what you did).
I think this issue can be closed then?

**Comment by andyb1979** [comment]
Yes by all means closed. All seems to be working.

Yes we connect via Teamviewer not RDP to workaround the above.

Thanks!
