### ISSUE TITLE
Positive feedback! Have used FLA3 to smoke test an application

### ISSUE THREAD

**Issue by andyb1979** [Roemer/FlaUI#277]
Some positive feedback (not an issue)! 

I've used FLAUI 2.0.0rc1 to do some simple UIAutomationTests for a WPF application here:
https://github.com/abtsoftware/scichart.wpf.examples
https://twitter.com/AndrewJB_T/status/1193112168956338176

Thanks for creating such a great framework!

**Comment by Roemer** [comment]
Thanks for the feedback :) Glad it works for you as well. If you have improvement ideas or problems, feel free to post them as issues.

**Comment by andyb1979** [comment]
I went into a bit of detail here about what we did and how! Great work & thanks again! 
https://www.youtube.com/watch?v=WbZZZG5Rfxk
