### ISSUE TITLE
Create nuget packages

### ISSUE THREAD

**Issue by Roemer** [Roemer/FlaUI#3]
Investigate in the best method to automatically create nuget packages (and releases) with AppVeyor and add implement this.

**Comment by Roemer** [comment]
First packages are now on nuget. Currently, each build publishes packages. Not sure yet if this is good or if this should be done manually. Any opitions?

**Comment by Roemer** [comment]
Well, for now I will manually push to NuGet. Also the packages in NuGet should now be fully functional. So I will close this.

**Comment by JohanLarsson** [comment]
I would highly recommend using [paket](https://fsprojects.github.io/Paket/)
