### ISSUE TITLE
question to get value

### ISSUE THREAD

**Issue by poloab** [Roemer/FlaUI#37]
Hi. Thank you for your work with flaui, I am starting to use it and looks better alternative.

But I can't get the actual value of a control like a textbox or label, how can I achieve it?

Maybe some more samples will help us.

That you.

**Comment by Roemer** [comment]
Have a look at the UI test project (https://github.com/Roemer/FlaUI/tree/master/src/FlaUI.Core.UITests) there you can find a lot of samples.
In general you convert your element once found into the element you expect it to be (for example AsTextBox() and then you have the most important methods / properties directly available.

**Comment by JohanLarsson** [comment]
@poloab an alternative is asking on StackOverflow, questions and answers there will help many devs.

**Comment by Roemer** [comment]
Or you can also ask on [gitter ](https://gitter.im/FlaUI/)

**Comment by poloab** [comment]
Thank you. I'll try it. The UI test project that I didn't see is helpful. Thanks for your help.
