### ISSUE TITLE
Not possible to handle window that is displayed when selecting combobox item 

### ISSUE THREAD

**Issue by redsolo** [Roemer/FlaUI#39]
I have a combo box item that if the user chooses it, it will reset some other values in the same UI. The application then displays a message box asking the user to confirm that the other values are changed. But the ComboBoxItem.Select() freezes the code execution so it is not possible to handle the message box that is displayed. 

Im porting my project from White and this worked there somehow..

**Comment by Roemer** [comment]
The select from the selectionnpattern freezes in that case. You can use "Click" which does not block. There was an issue with GetClickablePoint which is fixed now. See commit d2da2df88d2c8a37a492326537c13a2b8f52f566
