### ISSUE TITLE
Don't pollute stdout

### ISSUE THREAD

**Issue by jmaxxz** [Roemer/FlaUI#43]
At present classes in FlaUI.Core write data to the console this limit's the ability of consumers to use this library in CLI applications as the library ends up polluting stdout. Please consider allowing consumers of this library to pass alternate loggers, or defaulting to [Trace](https://msdn.microsoft.com/en-us/library/system.diagnostics.trace.writeline(v=vs.110).aspx) or [Debug](https://msdn.microsoft.com/en-us/library/system.diagnostics.debug.writeline(v=vs.110).aspx)  for log information.

**Comment by Roemer** [comment]
Thanks for the feedback. Should I add log4net or just use some custom logger classes directly in flaui?

**Comment by jmaxxz** [comment]
I will open a PR, I think this can be done without adding a heavy weight solution like log4net.

**Comment by Roemer** [comment]
Cool thanks. I had a peek already and like it so far. Pretty much exactly what I would have done :)
