### ISSUE TITLE
Can not get or set value of Spinner inputs

### ISSUE THREAD

**Issue by jmaxxz** [Roemer/FlaUI#45]
FlaUI appears to be unable of getting or setting the value of a numeric spinner control in a windows forms application.

In UIA2 note that the edit control inside of the combo-box does not show up:
![image](https://cloud.githubusercontent.com/assets/828153/23820488/3761b50e-05ce-11e7-9cd5-171a74f7f768.png)

In UIA3 it shows up in the inspect tool:
![image](https://cloud.githubusercontent.com/assets/828153/23820526/3e2bac18-05cf-11e7-8ffb-af6d343c1a36.png)

However, the edit control which contains the value does not seem to be target-able by code
![image](https://cloud.githubusercontent.com/assets/828153/23820587/ad967ef6-05d0-11e7-9d0a-f29821b56c6f.png)
 

[branch with spinner on win forms app](https://github.com/jmaxxz/FlaUI/tree/spinner)

My attempts to select the current value:
```csharp
        [Test]
        public void Spinner()
        {
            var comboBox = App.GetMainWindow(Automation).FindFirstDescendant(cf => cf.ByAutomationId("numericUpDown1"));
            Assert.IsNotNull(comboBox);

            var edit = comboBox.FindFirstDescendant(cf => cf.ByControlType(ControlType.Edit));
            Assert.IsNotNull(edit);

            var value = comboBox.AsComboBox().EditableText;
            Assert.AreEqual("42", value);

            var value2 = edit.AsTextBox().Text;
            Assert.AreEqual("42", value);
        }
```

**Comment by Roemer** [comment]
It seems that it is broken in UIA2. In UIA3, I can get the edit correctly and get/set values. I'll investigate a but more but I guess there is nothing we can do.

**Comment by jmaxxz** [comment]
@Roemer does not work on my windows 10 environment, what code did you use to get/set values?

**Comment by Roemer** [comment]
```
var spinner = App.GetMainWindow(Automation).FindFirstDescendant(cf => cf.ByAutomationId("numericUpDown1"));
Assert.IsNotNull(spinner);
var edit = spinner.FindFirstDescendant(cf => cf.ByControlType(ControlType.Edit)).AsTextBox();
Assert.IsNotNull(edit);
edit.Text = "42";
Assert.AreEqual("42", edit.Text);
```

**Comment by Roemer** [comment]
You don't get min/max and such with that but at least the value.

**Comment by Roemer** [comment]
Problem was that UIA2 was loaded into the process already and then UIA3 was loaded (which then still worked on UIA2). So getting/setting the value works with UIA3.
