### ISSUE TITLE
Error on Windows XP SP3

### ISSUE THREAD

**Issue by poloab** [Roemer/FlaUI#51]
Hi, first to many thanks for this work.

I am trying to automate a Visual Foxpro aplication, and It works well in windows 10 an 8, 8.1, but when I try it in windows XP SP3, I get an error:

- When using UIA3Automation, a get: Unregistered class for component with CSLID {FF48DBA4-60EF-4201-AA87-54103EEF594E}.

- And When using UIA2Automation, the process to get the previously started aplication main windows is too slow in all Windows Operating System tested, and in windows XP I get this error : exception in type initializer "FlaUI.UIA2.Indentifiers.AutomationObjectIds".

Any idea, I need help.

Thank you

**Comment by Roemer** [comment]
I think UIA3 is not available in XP at all. Can you post the whole exception you get when using UIA2 with inner exceptions? I will try to get an XP somewhere to test this myself.

**Comment by Roemer** [comment]
I installed the modern.ie XP SP3 on virtualbox with Visual Studio 2010 C# Express and I can successfully use UIA2 and somehow even UIA3. Can you tell me more about what is installed like .Net Framework? Or did you find something else?

**Comment by maxinfet** [comment]
I am guessing if you make certain calls UIA3 will blow up. I was under the impression the virtualization pattern would exception on UIA2/3 on XP.

**Comment by Roemer** [comment]
@poloab Any news on this?

**Comment by poloab** [comment]
Yes, I was wrong and post this without verification, because the three computer where I was testing at work have windows XP SP3, but they were with update disabled and blocked (the VFP program I'm automating, doesn't work well in other OS); after I've activated update function and update windows XP, UIA2 and UIA3 (functions I am using) worked well. So only update was necesary.

I'm so sorry for you to lose your time.

Thank you for your effort.

**Comment by yupengfei** [comment]
> Yes, I was wrong and post this without verification, because the three computer where I was testing at work have windows XP SP3, but they were with update disabled and blocked (the VFP program I'm automating, doesn't work well in other Windows version); after I've activated update function and update windows XP, UIA2 and UIA3 (functions I am using) worked well. So only update was necesary.
> 
> I'm so sorry for you to lose your time.
> 
> Thank you for your effort.

Hi, I got the same error, and I install all patched I can find, by there still goes the exception. Do you have any idea?

**Comment by 1000374** [comment]
xpSp3 使用.net3.5动态库可用，4.0动态库
System.TypeInitializationException: The type initializer for 'FlaUI.UIA2.Patterns.DockPattern' threw an exception. ---> System.TypeInitializationException: The type initializer for 'FlaUI.UIA2.Identifiers.AutomationObjectIds' threw an exception. ---> System.NullReferenceException: Object reference not set to an instance of an object.
