### ISSUE TITLE
Window.ModalWindows does not report all modal windows

### ISSUE THREAD

**Issue by redsolo** [Roemer/FlaUI#52]
In our application we have a progress bar dialog that is displayed before a file is opened, and the first action the user needs to do is to pick the file in a Open File dialog. Both dialogs are displayed with ShowDialog so they are both modal, but the Window.ModalWindows only reports the first progress dialog.

As you can see the file dialog is a child of the progress bar dialog:
![flaui-multiple-modalwindows](https://cloud.githubusercontent.com/assets/494531/25042547/3ab494c2-2119-11e7-92f7-e4b5a7ec8209.png)

Code using ModalWindows:
```
Window[] windows = App.MainWindow.ModalWindows;
// windows.Length == 1
```

Progress dialog has the following pattern:
```IsModal=True
IsTopMost=False
CanMinimize=False
CanMaximize=False
WindowVisualState=Normal
WindowInteractionState=BlockedByAModalWindow
```

File dialog has the following pattern:
```IsModal=True
IsTopMost=False
CanMinimize=False
CanMaximize=False
WindowVisualState=Normal
WindowInteractionState=ReadyForUserInteraction
```

**Comment by Roemer** [comment]
The ModalWindows property only returns the modal windows which are a child element of the window (and not any descendant). If it would return any modal window, it might get complicated to identify the correct window in the end so it's probably better to search for the window on your own or at least call mainwindow.ModalWindows[0].ModalWindows[0].

**Comment by redsolo** [comment]
Ok. I understand. Im closing this issue.
