### ISSUE TITLE
ComboBox doesn't have method Select(string itemText)

### ISSUE THREAD

**Issue by jochenparm** [Roemer/FlaUI#53]
It would be nice if comboboxes had a method to select items by text instead of only by index.
Ofcourse it's possible to do so yourself as user, but it kind of feels like basic functionality for a combobox.

I'm currently in the process of migrating a small project where I'm using TestStack.White to FlaUI. 
I'll post issues here for situations where I think White's API is superior. This is one of those cases ;)

**Comment by Roemer** [comment]
Same goes for Menu/menuitems I guess. Will have a look at this.

**Comment by Roemer** [comment]
Oh and please create separate issues for everything you find :)

**Comment by Roemer** [comment]
How about a virtual FindByText method on the combobox?
The default implementation would loop thru the Items and select their .Name and returns the first which matches the text or null otherwise.
So it would look like:
```csharp
myCombo.FindByText("Some Value")?.Select();
```

**Comment by Roemer** [comment]
Pretty much like this:
```csharp
/// <summary>
/// Search the first item which matches the given text.
/// </summary>
/// <param name="textToFind">The text to search for.</param>
/// <returns>The first found item or null if no item matches.</returns>
public virtual ComboBoxItem FindByText(string textToFind)
{
    var items = Items;
    return items.FirstOrDefault(item => item.Text.Equals(textToFind));
}
```
Would that be enough?

**Comment by jochenparm** [comment]
Sure, functionally this would work, but now the API for selecting an item is different depending on whether you want to select by id or by text.
myCombo.Items[int index].Select();
myCombo.FindByText("Some Value")?.Select();

while I would find the following more logical (but it is a breaking API change...):
myCombo.Items.Select(int index);
myCombo.Items.Select(string textToFind);

**Comment by Roemer** [comment]
Check my commit above ;) It's exactly like this now. Except that it is myCombo.Select(int index or string textToFind) and not myCombo.Items.Select(...)

**Comment by jochenparm** [comment]
Great, that's even better IMO! (and nicely matches the White API ;) )
