### ISSUE TITLE
Grid has no methods Select(string itemName), Exists(string itemName) or SelectedItem property

### ISSUE THREAD

**Issue by jochenparm** [Roemer/FlaUI#54]
Grids are often used with a single column dimension as lists.
It would be nice if there was a way to select items/rows based on their value/text instead of only by index.
It would also be nice if there was an Exists(string itemName) method that identified if an item with specified value exists in the Grid. It might be valuable to implement this method for all AutomationElements that contain multiple items (ComboBox, Grid, GridRow, ...)

Something that's definitely missing is a way of returning the selected rows (for example a SelectedItems property, like the ComboBox has). Unless I'm somehow overlooking this functionality?

**Comment by Roemer** [comment]
I'm in the process of doing some refactorings to provide that. I keep you updated.

**Comment by jochenparm** [comment]
Okay, thank you!

**Comment by Roemer** [comment]
I added some methods to the Grid. Can you check the commit above and see, if that would be enough already?

**Comment by jochenparm** [comment]
Yes, at first sight this seems enough. Thank you for being so fast with the implementations!
