### ISSUE TITLE
FindChildren / FindDescendants not seeing elements the Spy tools see

### ISSUE THREAD

**Issue by sean-sel** [Roemer/FlaUI#57]
![flauinspect](https://cloud.githubusercontent.com/assets/28266625/25920966/e6f525ea-3590-11e7-95ef-3718bf3e3c1c.png)
![vsflau](https://cloud.githubusercontent.com/assets/28266625/25920973/ebe84bd6-3590-11e7-9d57-034ab3964c84.png)
I am able to use flauinspect.exe and UISpy.exe to view the Win32 Tree and Controls but I'm not able to Find Children or Descendants of the Window. The length is always 0.  How do I enable the code version to see everything the Spy tools see?

**Comment by Roemer** [comment]
1. Are you sure you have the right window?
2. Are you running Visual Studio with less privileges? Try running it as admin.

**Comment by sean-sel** [comment]
I tried Launching VS 2017 via Run as Administrator but that made no difference.
You can see from the Autos Window the window name is AcSELerator Quickset as well as the Inspector tree so it is the same window in both cases.

Specifically I was trying to access the File Menu
Element is null as no children or descendants are found.

The method used is 

`
public MenuItem File { get => FindByTypeName(ControlType.MenuItem, "File").AsMenuItem(); }

protected AutomationElement FindByTypeName(ControlType control, String name)
        {
            AutomationElement[] descends = window.FindAllDescendants(); // 0 Found
            AutomationElement[] kids = window.FindAllChildren(); // 0 Found
            var element = window.FindFirstDescendant(cf => cf.ByControlType(control).And(cf.ByName(name)));
            return element; // Returns Null
        }
`




I found that the White Library was able to discover the File Menu
var mainWindow = Application.GetWindow("AcSELerator® QuickSet - [Getting Started with QuickSet]");
var fileMenu = mainWindow.Get(SearchCriteria.ByText("File"));

**Comment by Roemer** [comment]
I think someone else once had the same problem. Probably it is some 32/64 bit issue but I could never reproduce it. Is this software freely available so I could try this as well?

**Comment by Roemer** [comment]
FlaUInspect sees the controls and FlaUInspect uses FlaUI actually so this is very strange to me.

**Comment by Roemer** [comment]
What is strange to me as well:
In your debug screenshot above the window has the name "AcSELerator® QuickSet" whereas the name in flauinspect and the one you search for in white is "AcSELerator® QuickSet - [Getting Started with QuickSet]". Are you really sure you have the right window in FlaUI? MainWindow can return the wrong window in some cases (Windows-Problem).

**Comment by sean-sel** [comment]
The program can be downloaded at [https://selinc.com/api/download/?link=https%3a%2f%2fcdn.selinc.com%2fProtected%2fsoftware%2f5030%2fSetup.exe](url)

**Comment by Roemer** [comment]
Seems like it needs a login. Could you put the installer onto a google drive or something?

**Comment by sean-sel** [comment]
You can also go to
selinc.com > Products > Software Downloads > acSELerator QUICKSET SEL-5030 SOFTWARE

**Comment by sean-sel** [comment]
My environment is Win10x64 with Visual Studio 2017. So it could be 32/64 issue.

**Comment by sean-sel** [comment]
You can create a free account to download the software. I'm looking into other ways to share it.

**Comment by Roemer** [comment]
They need a valid account and validation takes a few days... Would be great to get the installer somehow else.
In the meantime, did you check the Window Name (which is different in the FlaUInspect and the debug window) and could you also try the newest flauinspect to see, if this broke something?

**Comment by Roemer** [comment]
Oh and please also quickly try UIAutomation2 in the code.

**Comment by Roemer** [comment]
Also please try FindFirstChild instead of FindAll. Or maybe also debug FlaUIs code and see, if the native calls really return 0 or if something else fails.

**Comment by sean-sel** [comment]
using FlaUI.UIA2;

AutomationElement descend1 = window.FindFirstDescendant();
{AutomationId:TitleBar, Name:AcSELerator® QuickSet, ControlType:title bar, FrameworkId:Win32}

AutomationElement kid1 = window.FindFirstChild();
{AutomationId:TitleBar, Name:AcSELerator® QuickSet, ControlType:title bar, FrameworkId:Win32}

window.FindFirstDescendant(cf => cf.ByName("File"))
Evaluation of method FlaUI.Core.AutomationElements.Infrastructure.AutomationElement.FindFirstDescendant() calls into native method System.DateTime.GetSystemTimeAsFileTime(). Evaluation of native methods in this context is not supported.

window.FindFirstDescendant(cf => cf.ByControlType(ControlType.MenuItem));
Evaluation of method FlaUI.Core.AutomationElements.Infrastructure.AutomationElement.FindFirstDescendant() calls into native method System.DateTime.GetSystemTimeAsFileTime(). Evaluation of native methods in this context is not supported.

**Comment by sean-sel** [comment]
[https://www.dropbox.com/s/di804gp83sfwd84/SEL-5030%20Setup.exe?dl=0](url)
Let me know once you've downloaded the Setup file

**Comment by Roemer** [comment]
You can delete it. I've downloaded it.

**Comment by sean-sel** [comment]
Thanks

**Comment by Roemer** [comment]
Ok it is as I thought (and already wrote). There is a splash screen with the title "AcSELerator® QuickSet". For whatever reason,  app.GetMainWindow (respectively the MainWindowHandle of the process) always returns this Splash screen, even if it is already gone. If you wait for the splash screen to disappear before (either with a Retry while it exists or just a plain sleep) and change that line to ```app.GetAllTopLevelWindows(automation)[0]```, you get a window with a title "AcSELerator® QuickSet - [Getting Started with QuickSet]" which now is the right window and your things should start working :)

**Comment by sean-sel** [comment]
Thanks for looking into that. I think you need to update your GitHub wiki. I don't see documentation for app.GetAllTopLevelWindows and I don't see a link to your Inspect Tool I had to find it through a google search.

**Comment by sean-sel** [comment]
Roemer how do I Click On / Expand or make visible the File Menu?

window.SetForeground();
var menu = window.FindFirstChild(cf => cf.Menu()).AsMenu();
var fileMenu = menu.MenuItems["File"]; // {AutomationId:, Name:File, ControlType:menu item, FrameworkId:}

fileMenu.GetSupportedPatterns()
{FlaUI.Core.Identifiers.PatternId[2]}
    [0]: {Invoke [#10000]}
    [1]: {LegacyIAccessible [#10018]}

fileMenu.Invoke();
'fileMenu.Invoke()' threw an exception of type 'System.InvalidOperationException'
    Data: {System.Collections.ListDictionaryInternal}
    HResult: -2146233079
    HelpLink: null
    InnerException: null
    Message: "Operation is not valid due to the current state of the object."
    Source: "Interop.UIAutomationClient"
    StackTrace: "   at Interop.UIAutomationClient.IUIAutomationInvokePattern.Invoke()\r\n   at FlaUI.UIA3.Patterns.InvokePattern.<Invoke>b__3_0()\r\n   at FlaUI.Core.Tools.ComCallWrapper.Call(Action nativeAction)\r\n   at FlaUI.UIA3.Patterns.InvokePattern.Invoke()\r\n   at FlaUI.Core.AutomationElements.MenuItem.Invoke()"
    TargetSite: {Void Invoke()}

I looked at the Unit tests in the project but they don't show expanding the File Menu to make New / Open / Save accessible

fileMenu.Click() crashes the app.
I'm trying to Click on File > New... but New isn't clickable and not sure how to get File Menu to expand to make New visible

**Comment by Roemer** [comment]
That depends on the menu itself. You can look at the Menu.cs file in FlaUI. The best way is to use the SubMenuItems property to get the sub menu items which takes care of if it needs to be expanded or not and returns the appropriate submenus.

**Comment by sean-sel** [comment]
I was not able to get the menu to Invoke it keeps giving an error. Only the LegacyPattern is available. I did figure out how to navigate the menu using Send Keys however which meets my needs.
