### ISSUE TITLE
Searching in UIA2 versus UA3

### ISSUE THREAD

**Issue by ghost** [Roemer/FlaUI#59]
```csharp
var screen = App.GetMainWindow(Automation);

var titleBar = screen.TitleBar; // Does not work.
Assert.That(titleBar, Is.Not.Null, @"Could not locate TitleBar as property of screen.");

titleBar = screen.FindFirstByXPath(@"/*[@AutomationId='TitleBar']")?.AsTitleBar();
Assert.That(titleBar, Is.Not.Null, @"Error locating TitleBar by given XPath.");

titleBar = screen.FindFirstByXPath(@"/*[@LegacyIAccessible.Role = 'title bar']")?.AsTitleBar();
Assert.That(titleBar, Is.Null, @"Error locating TitleBar by given XPath.");

//var propertyCondition = CacheRequest .PropertyLibrary.LegacyIAccessible.Role, 0x1;
//titleBar = screen.FindFirst(TreeScope.Children, propertyCondition)?.AsTitleBar();
//Assert.That(titleBar, Is.Null, @"Could not locate by LegacyIAcccessibility.Role");

// Can locate by ILegacy Pass through
//titleBar = screen.FindFirstDescendant(fn => fn.ByControlType(ControlType.TitleBar))?.AsTitleBar();
//Assert.That(titleBar, Is.Null, @"Could not locate TitleBar by ControlType");

// Can locate by manual Automation Tree search and condition creation
//titleBar = screen.FindFirst(TreeScope.Children, new PropertyCondition(Automation.PropertyLibrary.Element.AutomationId, "TitleBar"))?.AsTitleBar();
//Assert.That(titleBar, Is.Null, @"Could not locate TitleBar AutomationId");

//titleBar = App.GetMainWindow(Automation).FindFirstDescendant(ctrl => ctrl.ByLocalizedControlType("TitleBar"))?.AsTitleBar();
//Assert.That(titleBar, Is.Null, @"Could not locate TitleBar using Localized Control Type of 'TitleBar'");
```
Testing an old Delphi app.

I am varying results between UIA2 and UIA3. Everyone one of these tests yields null in UIA3. Can anyone provide a little more insight with regards to the caveats in searching? How do I correctly grab something by legacy accessibility?

Cheers.

**Comment by Roemer** [comment]
Can you attach some inspect screenshots?

**Comment by JuniorHacks** [comment]
@Roemer I can not due to the nature of the customer (unfortunately). However, I will document what I find out and in a series of readme. In short, searching appears janky in these particular apps and behaves differently from UIA2 to UIA3. Weird one off edge cases like this don't work.

` //CreateProductEntryScreen = App.GetAllTopLevelWindows(Automation).Where(w => w.Title == DesiredScreenTitle)?.First();
                CreateProductEntryScreen = Automation.GetDesktop().FindFirstByXPath($"/Window[@Name='{DesiredScreenTitle}']").AsWindow();
                Assert.NotNull(CreateProductEntryScreen, $"Test must started at {DesiredScreenTitle}.");`

I just updated NUGET today and many of these issues are resolved. It would be great to learn more about searching in general with more complex examples using both XPath and the raw tree.

**Comment by Roemer** [comment]
What do you mean by "updated NUGET"? Updated to latest FlaUI? If so, can you tell me from which to which version?
Have you looked at FlaUInspect with uia2 and once with uia3 to see if they differ?

**Comment by Roemer** [comment]
Do you have any more feedback?

**Comment by Roemer** [comment]
Please re-open or create a new issue if this is still pending.
