### ISSUE TITLE
Unable to access label text in Legacy Win 32 app

### ISSUE THREAD

**Issue by sean-sel** [Roemer/FlaUI#60]
Can you help me figure out how to access the Driver Info in this screen shot? 
This is the same application you previously downloaded.
File > New will bring up this screen.

![driver_info](https://cloud.githubusercontent.com/assets/28266625/26379434/79c71cbc-3fd6-11e7-8a09-ec92c25dbac7.png)

Typical Patterns are not available and only the parent pane is available. The labels do not appear in spy trees.

It does not appear to be Content Element using UISpy > Query
![content](https://cloud.githubusercontent.com/assets/28266625/26379957/03ef4f02-3fd9-11e7-8a43-400336dd6157.png)

**Comment by Roemer** [comment]
I couldn't analyze it yet but it if is not a content element, you might try the raw treewalker to get the element.
For example:
```csharp
var pane = mainWindow.FindFirstDescendant(cf => cf.ByAutomationId("266552"));
var rawTreeWalker = Automation.TreeWalkerFactory.GetRawViewWalker();
var rawElement = rawTreeWalker.GetFirstChild(pane);
if (rawElement != null)
{
    return rawElement.Properties.Name.Value;
}
```

**Comment by sean-sel** [comment]
I tried walking the tree that didn't work either.

WalkTree(currentWindow,0);

`[TestCase(Category = "SmokeTest")]
        public void WalkTree(AutomationElement root, int indent)
        {
            if (root == null)
                return;

            var rawTreeWalker = automation.TreeWalkerFactory.GetRawViewWalker();
            var kid = rawTreeWalker.GetFirstChild(root);

            if (kid == null)
                return;

            while (kid != null)
            {
                String buffer = "";
                for (int i = 0; i < indent; i++)
                {
                    buffer += "\t";
                }
                var name = kid.Properties.Name.Value;
                Report.Progress("Name:" + buffer + name);
                WalkTree(kid, indent + 1);
                kid = rawTreeWalker.GetNextSibling(kid);
            }
        }

    }`

OUTPUT
Name:
Name:	
Name:		
Name:			
Name:				
Name:					
Name:						Driver Information
Name:							
Name:								
Name:								
Name:						Example FID
Name:							
Name:								
Name:			
Name:				
Name:					
Name:						Vertical
Name:							Line up
Name:							Position
Name:							Page down
Name:							Line down
Name:						SEL-150
Name:						SEL-221
Name:						SEL-251
Name:						SEL-267
Name:						SEL-279
Name:						SEL-287
Name:						SEL-300
Name:						SEL-311
Name:						SEL-321
Name:						SEL-351
Name:						SEL-352
Name:						SEL-387
Name:						SEL-411
Name:						SEL-421
Name:						SEL-451
Name:						SEL-487
Name:						SEL-T400L
Name:						SEL-501
Name:						SEL-547
Name:						SEL-551
Name:						SEL-587
Name:						SEL-651
Name:						SEL-700
Name:						SEL-701
Name:						SEL-710
Name:						SEL-731
Name:						SEL-734
Name:						SEL-735
Name:						SEL-749
Name:						SEL-751
Name:						SEL-787
Name:						SEL-849
Name:						SEL-2100
Name:						SEL-2411
Name:						SEL-2414
Name:						SEL-2431
Name:						SEL-2440
Name:						SEL-2523
Name:						SEL-2533
Name:						SEL-2664
Name:						SEL-3031
Name:						Misc.
Name:					
Name:						SEL-150
Name:					
Name:						000
Name:				
Name:
Name:	Install Devices
Name:	Cancel
Name:	OK
Name:
Name:	System
Name:		System
Name:	Close

**Comment by Roemer** [comment]
Unfortunately this text seems to not be exposed to UIA from the application. So there is nothing that can be done. You could only try to take a screenshot and get the text with OCR.
