### ISSUE TITLE
LegacyIAccessible, DataGrids

### ISSUE THREAD

**Issue by ghost** [Roemer/FlaUI#61]
Hey, all. Battling with some old Delphi apps and teaching myself UIA. I have some DevExpress data grids that I am trying to get into. Can anyone explain to me how to use "LegacyIAccessible" in context of FlaUI and to get data to and from the controls? 

Cheers.

**Comment by Roemer** [comment]
I think the LegacyIAccessible is too less to get data from a grid. No chance of getting a (blurred) screenshot of inspect`?

**Comment by Roemer** [comment]
Are there any more information? Or is it already solved?

**Comment by Roemer** [comment]
Closed due to inactivity.
