### ISSUE TITLE
Cannot access buttons under a tabular toolbar

### ISSUE THREAD

**Issue by EliasAthey** [Roemer/FlaUI#62]
I'm using FlaUI to test an application that has a 5 tab toolbar with unique buttons under each. The application starts with the first tab open and it's child buttons visible. Clicking these buttons works as intended.

However, when I use FlaUI to click another tab, it still only has access to the child buttons of the first tab. Is there some way to reset the current window or application so that the new tab's buttons are visible. Thank you.

**Comment by Roemer** [comment]
Might be the "Tab" issue. See if http://www.colinsalmcorner.com/post/genericautomationpeer--helping-the-coded-ui-framework-find-your-custom-controls helps.

**Comment by Roemer** [comment]
Closed due to inactivity, please reopen if my proposal didn't help.
