### ISSUE TITLE
can find loginname textbox but cannot set value

### ISSUE THREAD

**Issue by jerrylike** [Roemer/FlaUI#63]
use flaui can find loginname textbox, but can not set value for this textbox. raise exception 
![2017-6-8 13-57-23](https://user-images.githubusercontent.com/20104164/26914322-356b1ce2-4c53-11e7-8a59-d7657476990c.png)
![2017-6-8 13-58-06](https://user-images.githubusercontent.com/20104164/26914321-356875b4-4c53-11e7-9f2d-aeeffa41d10d.png)
![2017-6-8 13-58-24](https://user-images.githubusercontent.com/20104164/26914320-3565adfc-4c53-11e7-8fc2-df26aba5291a.png)

**Comment by Roemer** [comment]
Please attach a screenshot showing the control in any inspect tool.

**Comment by jerrylike** [comment]
![2017-6-8 14-09-37](https://user-images.githubusercontent.com/20104164/26914587-c47aae4c-4c54-11e7-99b4-a0dfccfe306e.png)
![2017-6-8 14-12-43](https://user-images.githubusercontent.com/20104164/26914586-c4771e26-4c54-11e7-90ec-b04bda9f855e.png)

**Comment by Roemer** [comment]
What patterns does it support? Maybe use FlUinspect for that. Also what exception does occur?

**Comment by Roemer** [comment]
Ah sorry, didn't see the 2nd screenshot. Can you try directly use the valuepattern and set the value there?

**Comment by jerrylike** [comment]
![2017-6-8 14-58-56](https://user-images.githubusercontent.com/20104164/26916016-1935d6ae-4c5b-11e7-9fe6-97a3e2c68a1b.png)

**Comment by Roemer** [comment]
Can you try focusing the control and use Keyboard to input text?

**Comment by jerrylike** [comment]
use FlUinspect
![3](https://user-images.githubusercontent.com/20104164/26916787-38bd0aee-4c5e-11e7-980f-f2a54e47a98e.png)

**Comment by Roemer** [comment]
May I ask why you closed it? Is it working now?
