### ISSUE TITLE
Signed NuGet package

### ISSUE THREAD

**Issue by kirillkovalenko** [Roemer/FlaUI#64]
I've noticed that there is a signing key in the source tree, but NuGet package does not seem to be signed. 
I get the following errors

```
>CSC : error CS8002: Referenced assembly 'FlaUI.Core, Version=1.2.0.0, Culture=neutral, PublicKeyToken=null' does not have a strong name.
>CSC : error CS8002: Referenced assembly 'FlaUI.UIA3, Version=1.2.0.0, Culture=neutral, PublicKeyToken=null' does not have a strong name.
```
Could you please provide a signed version as NuGet package as well?

**Comment by Roemer** [comment]
I am thinking about only providing signed packages on nuget. Not sure why someone could need the non-signed package.

**Comment by Roemer** [comment]
Will be included in the next release.
