### ISSUE TITLE
Registering for Events

### ISSUE THREAD

**Issue by sean-sel** [Roemer/FlaUI#65]
How do I register for events and synchronously wait for those events to occur?
There is no documentation on this and I see barely any tests for event handling, while there seem to be multiple types of events registered.

My scenario is that when I click on the first list it changes the second and third list.
![image](https://user-images.githubusercontent.com/28266625/27186174-be104166-51a4-11e7-9111-2ec9702b82c3.png)

When I loop through the list and select it
```csharp
foreach (var family in settingsDB.Fams())
{
	family.ScrollIntoView();
	family.Select();
	
	foreach (var model in settingsDB.Mods())
	{
		model.ScrollIntoView();
		model.Select();
		foreach (var version in settingsDB.Vers())
		{
			version.ScrollIntoView();
			version.Select();
		}
	}
}
```
The selection is too fast and it clicks on the second list before the first list has caused the second list to change. What is the best way to detect that the second list has changed before selecting it?
I was looking into registerStructureChangedEvent but found no good examples of how to use this.
UI.Wait is not helpful here.

**Comment by Roemer** [comment]
To be honest, I haven't tested the events that much :)

But the StructureChangedEvent could be used like this:
```csharp
var list = mainWindow.FindFirstChild(cf => cf.ByAutomationId("MyList"));
var eventHandler = list.RegisterStructureChangedEvent(TreeScope.Subtree, (element, type, arg3) =>
{
    // TODO: Do what ever you want
    // e.g. sending a signal to continue
});
list.RemoveStructureChangedEventHandler(eventHandler);
```

**Comment by sean-sel** [comment]
I discovered that if I use click instead of select then my problem is solved. 
Thanks for the tip on the event handler
