### ISSUE TITLE
Custom wait hooks

### ISSUE THREAD

**Issue by joemorr** [Roemer/FlaUI#66]
Is there currently any mechanism in FlaUI to make a custom wait hook? Possibly similar to test stack's IWaitHook (http://teststackwhite.readthedocs.io/en/latest/AdvancedTopics/Waiting/)

**Comment by Roemer** [comment]
Currently not as I do not see the point in it. You can always wrap FlaUI calls in your own methods with your wait method. E.G "GetWindowWhenLoaded" which gets a window and waits until a spinning icon disappears. You can try to convince me that the wait hooks make sense ;)

**Comment by joemorr** [comment]
Thanks for the reply. 

It is likely not necessary in most cases; and could potentially be a performance black hole. I was looking into it to try and workaround some stability and development pains. I was hoping to make a hook so it would run all the time without extra explicit wait calls in my page objects or tests themselves. I am hoping to avoid
```
window.Click(button1)
WaitForSomeLongAsync()
window.Click(button2)
WaitForSomeLongAsync()
```
or
```
while (!pageObjectCheckForExpectedAndKeepyRetrying()) && timeSpent <= timeout)
{
    pageObject.TryOperation()
}
```
...and so on. The goal would be to take some of the development time, complexity of page objects, and debugging timing issues and just pawn it off into a hook. And if I do not have to worry about timing issues as much hopefully the tests would be more stable. Oh and also it would clean up my code :).

I will try and find a clean way to refactor without it though. Thanks again.

**Comment by rafaelubaldo** [comment]
If you check the FlaUI Retry.While, it may worked for what you are trying to accomplish. It basically does something like the following in blocking manner. 

```
public static async Task<T> WaitForNotNull<T>(Func<T> NotToReturnNull,
                         double giveUpAfterMilliseconds = 2000,
                         double retryIntervalInMilliseconds = 200) {

            var fromTime = DateTime.Now;
            T thing = NotToReturnNull();
            return await Task.Run(() => {
                while (true) {   
                    if (thing != null) return thing;
                    if (TimedOut(fromTime, TimeSpan.FromMilliseconds(giveUpAfterMilliseconds))) break;
                    Thread.Sleep(TimeSpan.FromMilliseconds(retryIntervalInMilliseconds));
                    thing = NotToReturnNull();
                }
                // error handling here
                return thing;
            });
        }
```

**Comment by Roemer** [comment]
Most "waiting" methods would wait on something different. So you would have to add a different waiting hook to most controls which in the end does not save anything. You could also hide the waiting methods in the ScreenObjects. For example by providing a "PerformSearch" method on the screen object which would click the search button and wait until the results show up.

If you have the same wait method all over you could still create an extension method like "ClickAndWait" which, well, clicks and performs your generic wait.

Also have a look at the Retry methods as @rafaelubaldo mentioned above.

**Comment by joemorr** [comment]
Thanks. I will take a look at the retry methods and see if those can help me refactor some stuff.
