### ISSUE TITLE
Sign the assembly

### ISSUE THREAD

**Issue by JohanLarsson** [Roemer/FlaUI#68]
As it is now it cannot be used for testing signed assemblies.

Sceanrio: the tested assembly is signed and has `InternalsVisibleTo` the test assembly. I think this means the test assembly must also be signed.

**Comment by Roemer** [comment]
How do you mean this? Flaui tests a running application and therefore does not need to reference any of the applications assembly.

**Comment by JohanLarsson** [comment]
While it does not need to reference the assembly there can be scenarios where referencing can make sense.

**Comment by Roemer** [comment]
Do you have an example? :) Just wondering how urgent this is.

**Comment by JohanLarsson** [comment]
I changed [this](https://github.com/JohanLarsson/Gu.Wpf.NumericInput) lib from white to flaui. After that the UI-tests did not run.
![error](https://user-images.githubusercontent.com/1640096/27429748-7f5c7ece-5746-11e7-8e0d-706252503fe4.png)

The R# runner showed ^ and reported 'Test not run' for all tests.
I fixed it by removing the `InternalsVisibleTo` and signing of the test project but wrote this issue as I thought it can happen in other projects.

**Comment by JohanLarsson** [comment]
A use case that is perhaps more common is if you have a test project and `InternalsVisibleTo` and then add UI-tests to that project.

**Comment by Roemer** [comment]
The problem should only arise if your test-assembly is signed (which usually is not needed).

**Comment by godrose** [comment]
I've done several projects on automation using TestStack.White and never had to reference the actual application.
Is there something I'm missing?

**Comment by JohanLarsson** [comment]
White is signed I think.

**Comment by Roemer** [comment]
Duplicate of #64
