### ISSUE TITLE
Enabled properties are not available via wrapper classes

### ISSUE THREAD

**Issue by godrose** [Roemer/FlaUI#69]
I'm migrating code from **TestStack.White** to this library.
There are lost of things missing especially `Enabled` property on various wrapper classes.
Namely the `Button` class lacks such ability meaning existing tests cannot be written using **FlaUI**

**Comment by JohanLarsson** [comment]
`Assert.AreEqual(true, increaseButton.Properties.IsEnabled.Value);`
I agree that `IsEnabled` should probably be exposed on the wrapper. Should be an easy PR.

**Comment by Roemer** [comment]
Fixed in commit 450d7c75f655039df40712d97d99382acc77ceb7.
