### ISSUE TITLE
Window class doesn't have 'Visible' property

### ISSUE THREAD

**Issue by godrose** [Roemer/FlaUI#70]
I'm migrating code from **TestStack.White** to this library.
There are lots of things missing especially `Visible` and `Enabled` property on `Window` class
This means existing tests cannot be written using **FlaUI**

**Comment by Roemer** [comment]
As @JohanLarsson mentioned, that stuff is all in ```.Properties```. But I will add a few more into the wrapper element.

**Comment by godrose** [comment]
Thanks! I'll use the Properties for now.

**Comment by Roemer** [comment]
Fixed in commit 450d7c75f655039df40712d97d99382acc77ceb7.
