### ISSUE TITLE
Window object lacks some features

### ISSUE THREAD

**Issue by godrose** [Roemer/FlaUI#72]
The `Window` object lacks `IsVisible` or similar property.
Am I supposed to use `IsOffScreen` instead?

**Comment by Roemer** [comment]
Yes, it's ```IsOffScreen```. ```Visible``` could also mean something else (like the ```WindowState.Minimized```). So I prefer the ```IsOffScreen```.

**Comment by godrose** [comment]
Have you tried running automation in remote environments like **AppVeyor**?
Does this property behave as expected in headless mode?

**Comment by Roemer** [comment]
Yes I do run tests in AppVeyor actually but UI testing absolutely needs a desktop session (is now default in AppVeyor). Headless or without a logged in user won't work.

**Comment by zamirkhan** [comment]
For me, at least, IsOffscreen returns false if the Window is not minimized, but also not on top (i.e. completely covered by another maximized Window). Is that expected behaviour? If so, how do I determine whether the Window in question is visible?

**Comment by Roemer** [comment]
Offscreen means that it is off of all screens, not behind another window.
You can can use Focus or SetForeground to try making the window the topmost one.
To find out the z.order of the windows, you might implement something like that mentioned here (PR Welcome): https://stackoverflow.com/questions/825595/how-to-get-the-z-order-in-windows

**Comment by zamirkhan** [comment]
Thanks! I've found that using TryGetClickablePoint() appears to provide the information I'm looking for. If the control is not currently on-screen (e.g. actually visible), then that method appears to return false. Although that is probably not its intended usage and perhaps there is a performance penalty?

**Comment by Roemer** [comment]
That is totally fine. It tries to get a point it can use to click the element. If the element is hidden / offscreen / overlapped, it will return false.

**Comment by zamirkhan** [comment]
Awesome - thank you for your help and for creating FlaUI!
