### ISSUE TITLE
Application object does not return all windows

### ISSUE THREAD

**Issue by godrose** [Roemer/FlaUI#73]
Repro steps:
Create an app with two windows - one over the other, something like this:

![screen shot 2017-06-27 at 5 11 26 pm](https://user-images.githubusercontent.com/7791651/27591894-c790012a-5b5b-11e7-98be-97d9e03a8a60.png)

Run automation

Access the `Application` object like this `var app = new Application();//launch etc...`
Expected:
`app.GetTopLevelWindows` returns both windows enabling operations on both of them
Actual:
`app.GetTopLevelWindows` returns only the main window enabling operations on this window only

**Comment by Roemer** [comment]
Can you post a FlaUInspect screenshot showing the two windows?

**Comment by godrose** [comment]
> Can you post a FlaUInspect screenshot showing the two windows?
How is this achieved? Is it some external tool?

**Comment by Roemer** [comment]
https://github.com/FlauTech/FlaUInspect
or just ```choco install flauinspect``` if you're using chocolatey. You can also use and other inspect tool like UiaVerify or just Inspect.

**Comment by godrose** [comment]
checking

**Comment by godrose** [comment]
![screen shot 2017-06-27 at 5 26 58 pm](https://user-images.githubusercontent.com/7791651/27592742-ddbc6856-5b5d-11e7-9c38-6caac73ffc14.png)

**Comment by godrose** [comment]
![screen shot 2017-06-27 at 5 26 58 pm](https://user-images.githubusercontent.com/7791651/27592759-e7d5d5c0-5b5d-11e7-8a20-a594be8700be.png)

**Comment by Roemer** [comment]
A TopLevelWindow is just... well a top level window. Your second window (LoginView) is just a child of the TopLevel Window. So either use ```FindAllChildren/FindFirstChild) on the TopLevelWindow or manually search all windows on the desktop which match your processId.

**Comment by godrose** [comment]
Yeah. Figured that. Thanks!

**Comment by godrose** [comment]
FYI, It seems slower than TestStack.White
