### ISSUE TITLE
Listbox and ListboxItem support

### ISSUE THREAD

**Issue by emeied** [Roemer/FlaUI#74]
There is support for ComboBox, but not for Listbox.
Trying to cast Listbox to Combobox and using e.g. Items ends in a NullReferenceException. 
I see there is a ControlType List and ListItem defined, but no AutomationElement to wrap it.
I need to select and double click an item.

**Comment by Roemer** [comment]
You can always directly with with the patterns. Listbox usually is a grid/table so you could try that. Or show me a screenshot of your listbox in flauinspect.

**Comment by emeied** [comment]
Here is the difference of Win32 listbox and combobox:
![image](https://user-images.githubusercontent.com/16724144/29270600-e9abb292-80f7-11e7-8f44-dad711b6f7a7.png)
If you wish I can send you the used sample and source.
![image](https://user-images.githubusercontent.com/16724144/29270752-7ce6170a-80f8-11e7-8a13-c22cf3b58ec8.png)

**Comment by Roemer** [comment]
It's very easy to have a ListBox:
```csharp
public class ListBox : AutomationElement
{
    public ListBox(BasicAutomationElementBase basicAutomationElement) : base(basicAutomationElement)
    {
    }

    public ListBox(AutomationElement automationElement) : base(automationElement)
    {
    }

    public AutomationElement[] Items => this.FindAllChildren(cf => cf.ByControlType(ControlType.ListItem));
}
```

To add it to the base of FlaUI we would need to check if there are differences in wpf/Winforms/UWP and adjust the class accordingly.

**Comment by Roemer** [comment]
Just implemented that.
