### ISSUE TITLE
Add support for ToggleButton

### ISSUE THREAD

**Issue by Portikus** [Roemer/FlaUI#75]
Hi,

I have a UWP application with a ToggleButton.
The following code throws 

> FlaUI.Core.Exceptions.PatternNotSupportedException: 'The requested pattern 'Invoke [#10000]' is not supported'

```csharp
var button = mainWindow.FindFirstDescendant("Button1").AsButton();
button.Invoke();
```

**Comment by Roemer** [comment]
Please post a screenshot showing the button in FlaUInspect.

**Comment by Portikus** [comment]
![togglebuttonflawuinspect](https://user-images.githubusercontent.com/15127750/29027512-39354e9e-7b81-11e7-9a20-ba45414dd53f.png)

**Comment by Roemer** [comment]
As you see, it does not support the invoke pattern but the toggle pattern. So you should be able to use the .Toggle method. Alternative you could use the .Click method (but toggle would be better).

**Comment by Portikus** [comment]
Ah ok. Thank you :)

**Comment by Portikus** [comment]
Hmm it seems I still have some problems. 
The only way I could call a Toggle on my object is the following:

```csharp
var button = mainWindow.FindFirstDescendant("Button1").AsCheckBox();
button.Toggle();
```

This works fine. The ToggleButton toggles its state. But the problem is that the related ICommand wont be executed. 

So I decided to use the `.Click()` method, which seems to work fine the command is executed and the state is toggled. But the problem with that is that: running the test on a build agent doesn't work, I get the following message: 

> Could not send mouse input. ErrorCode: 5

So what is your advice?

**Comment by Portikus** [comment]
Do you have any idea why this happens? Or do you have a workaround for me? I really want to use your lib but this blocks me.

**Comment by Roemer** [comment]
Using ```Click``` is fine. Pitty that the ICommand is not executed on WPFs side.
For UI tests on build agents make sure that you have a correct desktop session. Does it work when you are connected with RDP?

**Comment by Portikus** [comment]
Yes when I am connected via RDP it works fine.
Therfore Click is not a option for me I guess. 
Do you have any Idea why the command is not executed? (I am using UWP by the way)

**Comment by Roemer** [comment]
On what event is your ICommand bound? Maybe you can bind it to another event.
Also you can easily setup your build agent to automatically login and therefore have a desktop session. Also make sure that it is not closed when closing the RDP by using ```tscon 1 /dest:console``` or similar to disconnect.

**Comment by Portikus** [comment]
I will try it thank you.
I didn't bound the command to a specific event. I just use the command property of the toggle button. 
If you want I can make you a small repo solution.
I also tried the same thing with a button and the `Invoke()`. With this the command will be executed.

**Comment by Roemer** [comment]
Yes a small repo would be good. Maybe we can also redirect this to Microsoft as it is probably a problem there (I'll do some IlSpying to verify this).

**Comment by Portikus** [comment]
Here is the [repo solution](https://github.com/Roemer/FlaUI/files/1224496/SmokeTests.zip) with a unit test to show the difference between a normal and a toggle button.

**Comment by Portikus** [comment]
Any updates to this?

**Comment by Roemer** [comment]
Not yet. Will look at it when I'm back from vacation.

**Comment by HyruleWarrior** [comment]
@Portikus you should be able to use the Toggle pattern to access the Toggle() method for the button. something like:
`var button = mainWindow.FindFirstDescendant("Button1").AsButton();
button.Patterns.Toggle.Pattern.Toggle()`

You would probably want to check the pattern was supported by the button though using the IsSupported property of the pattern. I ran into the same issue trying to get the ToggleState of a button. I was thinking about adding the pattern to the Button class by default, similar to how buttons in TestStack.White operate.

**Comment by Roemer** [comment]
I had a deeper look at it. I checked the ToggleButtonAutomationPeer and on the Toggle() method, it fires the ToggleButtons OnToggle method which internally only sets the cheched property.
So with the default Toggle it won't be possible. So there are two ways to do this:
1. Use Click
2. Create your own ToggleButton class with its own AutomationPeer which either fires the TogleButtons OnClick method (instead the OnToggle) or implement an additional pattern like invoke (see here for an example: https://stackoverflow.com/questions/24762533/togglebuttonautomationpeer-toggle-does-not-execute-command). This would mean you need to exchange all ToggleButtons to your own ToggleButton class.

**Comment by Roemer** [comment]
I just implemented a ToggleButton class which will handle this. Will be in the next release. There is nothing else I can do.

**Comment by HyruleWarrior** [comment]
I added a similar class to my branch, but I think the problem in this thread is different then the problem I was facing. I was just wanting a Button with the ToggleState and Toggle methods that could be used for Buttons that support this pattern (which matches the title of the issue). But the original poster seems to be having a deeper issue maybe? I don't know if it is good to wrap the Click() method with a Toggle() method though because if you actually were wanting to test the Toggle Pattern of a button this wouldn't do it. But you wouldn't know that without looking into the source code. It might just be better in this case to write it up in the FAQ that Click() should be used in the case that @Portikus was running into. You can check out what I implemented here:
https://github.com/HyruleWarrior/FlaUI/tree/buttonTogglePattern

**Comment by Roemer** [comment]
@HyruleWarrior Just stumbled uppon this again today. You are probably right.
I just changed the ToggleButton back to use Toggle but added a comment and also an FAQ entry.
