### ISSUE TITLE
InvokedEvent doesn't work properly,

### ISSUE THREAD

**Issue by getson** [Roemer/FlaUI#76]
I have a form which has some buttons and input fields. I have registered invoked event in this form :
`       var btn= activeWindow.FindFirstDescendant("cmdOptions").AsButton();
      btn.RegisterEvent(InvokePattern.InvokedEvent, TreeScope.Element, InvokeAction);`
           
but the event not fired when the user click cmdOptions.
This Button supports InvokePattern (I saw from FLAUInspect)
What should I do  ?

**Comment by Roemer** [comment]
I just had a look at it. The InvokedEvent is something very unreliable.
Depending in your application, you can try UIA2Automation or UIA3Automation. For Win32/WinForms, UIA2 seems much more reliable and for WPF, UIA3.
You can also quickly check with the tool AccEvent.exe if that one can see your invoked events.

There is probably nothing more I can do from FlaUIs side unfortunately.

**Comment by Roemer** [comment]
Another thing is that using Invoke() from the InvokePattern seems to never fire the InvokedEvent. You should use Click().

**Comment by Roemer** [comment]
It really is a mess. Sometimes it does register two events, sometimes none, only If I use a Click and an Invoke it works partially. All in all at least the InvokeEvent seems to be a complete mess.
Here is a small code sample I used to test things and I've never got exactly what I wanted. This is not FlaUIs fault but from the UIA framework itself. I currently have no final solution for that.
```csharp
var app = Application.Launch("notepad.exe");
using (var automation = new UIA2Automation())
{
    var window = app.GetMainWindow(automation);
                
    Keyboard.TypeSimultaneously(VirtualKeyShort.ALT, VirtualKeyShort.KEY_O);
    Keyboard.Type(VirtualKeyShort.KEY_S);

    var popupWindow = window.FindFirstChild(cf => cf.ByControlType(ControlType.Window));
    //popupWindow.RegisterEvent(InvokePattern.InvokedEvent, TreeScope.Subtree, InvokedEventAction);

    var buttonId = automation.AutomationType == AutomationType.UIA3 ? "UpButton" : "SmallDecrement";
    var button = popupWindow.FindFirstDescendant(cf => cf.ByAutomationId(buttonId)).AsButton();
    button.RegisterEvent(InvokePattern.InvokedEvent, TreeScope.Element, InvokedEventAction);

    Console.WriteLine("Clicking");
    //popupWindow.FindFirstDescendant(cf => cf.ByAutomationId(buttonId)).AsButton().Invoke();
    Console.WriteLine("Invoking");
    popupWindow.FindFirstDescendant(cf => cf.ByAutomationId(buttonId)).AsButton().Click();

    System.Threading.Thread.Sleep(1000);

    automation.UnregisterAllEvents();
    popupWindow.FindFirstChild(cf => cf.ByAutomationId("1")).AsButton().Invoke();
}
app.Close();
```

**Comment by Roemer** [comment]
It's probably far more reliable to use a Mouse and Keyboard (like Gma.System.MouseKeyHook) hook to get user input. You could watch the mouse and on click, get the element that is under the button (automation.FromPoint()) to know which button was clicked.
If you try this, please tell me if it worked.

**Comment by getson** [comment]
Yes, I tried this and is possible to get the clicked element, but the mouse freezes when I call automation.FromPoint(), Seems to be the only solution for buttons.

**Comment by getson** [comment]
How to check  if is clicked inside a specific application ?
I want to handle only clicks inside test application.
I tried this : `    bool IsMouseInsideApplication(Point point)
        {
            if (_app == null) return false;
            var wnd = _app.GetMainWindow(_automation);
                var rext = wnd.Properties.BoundingRectangle.Value;
                if (point.X >= rext.X && point.X <= rext.X + rext.Width
                    && point.Y >= rext.Y && point.Y <= rext.Y + rext.Height) return true;

            
            return false;
        }`
But seems to be not correct

**Comment by getson** [comment]
I will close this issue because the problem comes from UI automation not by FLaUI.

**Comment by JobaDiniz** [comment]
>How to check if is clicked inside a specific application ?

I think you should find the `window` which the `element` (returned from `automation.FromPoint` is into
