### ISSUE TITLE
listview items

### ISSUE THREAD

**Issue by danhi** [Roemer/FlaUI#77]
So, I may not understand how these work, but I've been using White and it has a shortcoming that I was hoping FlaUI would overcome, but it appears not.  I've got a listview, and I would like to be able to get the icon associated with the listview, or else the tag.  But it seems the only thing I can retrieve is the text.  Is there anyway to drill down into the listview item?

**Comment by Roemer** [comment]
Post a screenshot showing a listviewitem in FlauInspect or any other inspect tool.

**Comment by danhi** [comment]
![flaui](https://user-images.githubusercontent.com/3358389/29334015-bff8183c-81ba-11e7-8990-98023473a311.JPG)

**Comment by danhi** [comment]
![flaui](https://user-images.githubusercontent.com/3358389/29334050-e8496520-81ba-11e7-865e-46712f69ee96.JPG)

**Comment by Roemer** [comment]
This is a shortcoming of the UIA framework itself. The WinForms ListViewItem does not expose the icon :( You could however try to use the BoundingRectangle, do some math on it and try getting the icon with the ScreenCapture class.

**Comment by danhi** [comment]
How about the tag?

**Comment by Roemer** [comment]
What tag?

**Comment by danhi** [comment]
You can set a tag on a listview item, to whatever you want.

 

https://msdn.microsoft.com/en-us/library/system.windows.forms.listviewitem(v=vs.110).aspx

**Comment by danhi** [comment]
You can set a tag to any object on a listview item:

https://msdn.microsoft.com/en-us/library/system.windows.forms.listviewitem(v=vs.110).aspx

**Comment by Roemer** [comment]
The Tag is just internal to the application and not exposed to UIA by the default provider.

**Comment by danhi** [comment]
Oh well, it would have been nice to have access to it.  I'll try the screencapture thing and see if I can get that to work.

I've just begun to look at this, is there a sample app (preferably in VB.Net or C#, but anything would do)?  I am interested in moving away from White, as they don't seem to be working on it anymore, and you're amazingly responsive to questions.

**Comment by Roemer** [comment]
You can look ak the UITest project in FlaUIs repository.

**Comment by Roemer** [comment]
Here's a link to them:
https://github.com/Roemer/FlaUI/tree/master/src/FlaUI.Core.UITests
They contain many tests which give you a hint on how you use FlaUI.

**Comment by Roemer** [comment]
Oh and please inform me if the ScreenCapturing way worked.

**Comment by danhi** [comment]
It did, I had to mess around a little bit to get what I needed, but I did.

I'll look at the tests you referenced and see if I can convert over to FlaUI from White.

**Comment by Roemer** [comment]
Can you post some hints or code how you did it in the end? For future reference and that we can close this issue :)

**Comment by danhi** [comment]
I will do this.  Where do you want me to post?  On the closed ticket?

**Comment by Roemer** [comment]
Yes please.

**Comment by danhi** [comment]
So, to get the icon from a listviewitem, I did the following:
        br = lvResults.Rows(resultIndex).Properties.BoundingRectangle.Value
        rc = New Rect(br.X, br.Y, br.Height, br.Height) ' just want the beginning square
        bm = ScreenCapture.CaptureArea(rc)
Then I captured the bmp's (using bm.save) for the icons I wanted to recognize, and them compared them to this bitmap to see which one it was.

**Comment by danhi** [comment]
I posted the code that I used to figure out the icon in a listviewitem.  I’ll take a look at the UITests when I get a chance.

 

As for the UITests, I can’t compile them until I install VS 2017.  I’ll put that on my todo list.

 

Out of curiosity, what requires VS 2017?

**Comment by Roemer** [comment]
The csproj format is the new VS2017 format. Also adding additional files to the nugets needs VS2017.3 to work.

**Comment by danhi** [comment]
OK, I’ll get 2017 one of these days and then take a look at the uitests.

**Comment by Roemer** [comment]
Guess this is solved now. Otherwise reopen it.
