### ISSUE TITLE
Building with VS 2010

### ISSUE THREAD

**Issue by danhi** [Roemer/FlaUI#79]
When I try to build using VS 2010, I get the following message:

C:\Source\FlaUI\src\FlaUI.Core\FlaUI.Core.csproj : error  : Unable to read the project file 'FlaUI.Core.csproj'. 
C:\Source\FlaUI\src\FlaUI.Core\FlaUI.Core.csproj(1,1): The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.

**Comment by Roemer** [comment]
Won't work. You need VS2017.3 to build it. But you can use it with anything that supports .net 3.5 or higher.
