### ISSUE TITLE
Properties not supported

### ISSUE THREAD

**Issue by danhi** [Roemer/FlaUI#80]
I'm trying to iterate over the controls in my app, and can't figure out how to tell if Properties is supported besides letting it fault.  I'm using (VB.Net):
```vb
For Each uii As AutomationElements.Infrastructure.AutomationElement In window.FindAllChildren()
    Dim s As String = uii.ToString
    If uii.ToString.Contains("MainToolStrip") Then
        For Each uii2 As AutomationElements.Infrastructure.AutomationElement In uii.FindAllChildren
            Select Case uii2.Properties.Name
                Case "Open File"
                    Dim btnOpen As Button = uii2.AsButton
            End Select
        Next
    End If
Next
```

**Comment by maxinfet** [comment]
On an `AutomationElement` it should have the method `IsPatternSupported` that takes a `PatternId`

Here is an example of how to checkin C# (I am not familiar with VB.Net)

```window.IsPatternSupported(Automation.PatternLibrary.<PatternYouCareAbout>);```

**Comment by maxinfet** [comment]
Sorry didn't mean to close this right away.

**Comment by danhi** [comment]
I have a similar problem trying to use a condition.  Intellisense tells me that the parmameter to IsPatternSupported is of type FlaUI.Core.Identifiers.PatternId, but there aren't any properties to that type, and if I try to create a new instance of that type it requires an integer, a string and a FlaUI.Core.Identifiers.PropertyID.

And if I try using System.Windows.Automation, there isn't a patternlibrary.

What am I doing wrong?

**Comment by danhi** [comment]
I couldn't get isPatternSupported working (would still like to know what I'm doing wrong there) but found out that if I use <automationelement>.properties.<item>.tostring, it works!  Fairly strange,  but it lets me do what I need.

But if someone could tell me how to use things like IsPatternSupported in VB.Net, it would be appreciated.

**Comment by Roemer** [comment]
Several things here:

1. To check if a property is supported, it is best to use the TryGetValue from the property. For example:
```csharp
string value;
bool isSupported = calc.Button1.Properties.AriaRole.TryGetValue(out value);
```

2. It is a bad approach to always get all elements and then by code iterate thru the elements and search the one you need. It is much better to directly filter the elements on UIA side to get the element you want. Have a look at [Searching](../wiki/Searching) to narrow down the elements found.
In your example, that would be something like:
```csharp
var toolStrip = window.FindFirstChild(cf => cf.ByName("MainToolStrip"));
var openFile = toolStrip.FindFirstChild(cf => cf.ByName("Open File")).AsButton();
```

**Comment by Roemer** [comment]
Btw, the next release will have an IsSupported flag on the property.

**Comment by Roemer** [comment]
Is this still an issue or can we close it?

**Comment by Roemer** [comment]
Guess this is solved then.
