### ISSUE TITLE
Clicking a menuitem

### ISSUE THREAD

**Issue by danhi** [Roemer/FlaUI#82]
I have a toolbar in my app with toolbaritems defined.  I use the following to get a particular menu item:

        MetaX = Application.Launch(psi)
        mainWindow = MetaX.GetMainWindow(FlaAutomation)
        mm = mainWindow.FindFirstChild(Function(cf) cf.ByName("MainToolStrip")).AsMenu
        mnuOpenFile = mm.FindFirstChild(Function(cf) cf.ByName("Open File")).AsButton

Which works fine, but when I try to use mnuOpenFile.Click, it tells me no clickable point.  I've also tried defining mnuOpenFile as menuItem, but that has the same problem.

I'm sure I'm missing something basic here, can you tell me what I'm doing wrong?

**Comment by danhi** [comment]
I'm really missing something.  Now I tried setting the text of a textbox, and I get an error target element cannot receive focus.  I tried looking in the uitests, but couldn't find anything.

Also, how do you send a ctl+<char> sequence using keyboard?

Is there any test app that uses a wider range of flaui that I could look at?  I'm pretty good at working from examples, and there's clearly some basic thing that I'm not understanding.

Any help would be greatly appreciated.

Dan

**Comment by Roemer** [comment]
Regarding keyboard, look at: https://github.com/Roemer/FlaUI/wiki/Keyboard
Also how do you set the text? With the Text property?
Can you try using mnuOpenFile.Invoke()?

**Comment by danhi** [comment]
So looking at gitter, I saw the invoke, so I tried that and it worked.  Buy any idea why click (which seems the obvious choice) doesn't work?

Got it on the keyboard.  I need to go through the wiki, maybe it will enlighten me.

And yes, I'm using the text property:

        modals = mainWindow.ModalWindows()
        fileOpenWindow = modals(0)
        tbFilename = fileOpenWindow.FindFirstChild(Function(cf) cf.ByName("File name:")).AsTextBox
        tbFilename.Text = "test"

**Comment by Roemer** [comment]
Are you running on a build system where you don't have a desktop session?

**Comment by danhi** [comment]
No, just running a plain vanilla Win 10.

**Comment by Roemer** [comment]
Is it a free application you're trying to automate?

**Comment by danhi** [comment]
It’s my own app, so I have access to the automation id’s as well as the names.

**Comment by Roemer** [comment]
It's more if it's possible to share the app with me or not :)

**Comment by danhi** [comment]
I can, or I could create a small test app that shows the problem as well.  The entire app is kind of large.  let me see if I can create a small app that shows the problem.

**Comment by Roemer** [comment]
Would be awesome and much easier for me to find issues then.

**Comment by danhi** [comment]
Actually, it's the standard file open box, which is actually a combobox.  So setting it to that, the only thing I can see to use if value or editabletext.  Value give me value not supported, editabletext tells me not editable.  So I created an app with my own combobox and it works fine, but then in the test app if I use the openfiledialog, I can find the combobox, but get the pattern value not supported.

I can send you the code for both the app that has the openfiledialog and the app that has the flaui calls.  But I think if you just create an app that calls openfiledialog, then try to set the value from another test app, you'd get the issue.

But whichever is easiest for you.

**Comment by danhi** [comment]
Thought I'd just send these along.  FlaTest has the openfiledialog, 
[FlaTest.zip](https://github.com/Roemer/FlaUI/files/1250198/FlaTest.zip), testharness has the FlaUI calls
[Testharness.zip](https://github.com/Roemer/FlaUI/files/1250199/Testharness.zip)

**Comment by danhi** [comment]
Found this in the microsoft automation docs:


IValueProvider | Depends | If the combo box has the ability to take arbitrary text values, the Value pattern must be supported. This pattern provides the ability to programmatically set the string contents of the combo box. If the Value pattern is not supported, this indicates that the user must make a selection from the list items within the subtree of the combo box.
-- | -- | --

**Comment by Roemer** [comment]
Yeah, docs and reality are mostly not the same :)

**Comment by Roemer** [comment]
Use the EditableText property on the ComboBox element.

**Comment by danhi** [comment]
I also am trying to use a radiobutton (this time in my own code) and the click event raises the noclickable exception.

**Comment by danhi** [comment]
Never mind about the radiobutton, realized I just need to select it and then click the ok button.  Still seems like the semantics should work for click, but at least now I know what to do.

**Comment by Roemer** [comment]
Regarding your combobox:
You are using: `cmb = mw.FindFirstChild(Function(cf) cf.ByName("File name:")).AsComboBox`
Which returns the `Label` (as this comes before the combobox). And a label cannot change the text. So it is absolutely correct.
You need to find the combobox:
`cmb = mw.FindFirstChild(Function(cf) cf.ByName("File name:").And(cf.ByControlType(ControlType.ComboBox))).AsComboBox`
Then everything works as expected.

**Comment by danhi** [comment]
I had to change controltype.combobox to definitions.controltype.combobox and then everything works.

You might consider adding something to the wrapper that makes this a little more intuitive, seems like the main thing someone is going to want to do with a combobox is either select one of the pre-filled entries or enter in an entry.

The same is true for a toolbar item and click versus invoke, and click on a radiobutton.  Having the semantics be more intuitive would mean less work for you in the long term.

But thanks for doing this.  I tried White and it was really slow, had bugs, and no support.  So just the great support you provide makes this much, much better.

Dan

**Comment by Roemer** [comment]
UIA is very fragile. UIA2 and UIA3 behaves differently. Then there's also WPF, WinForms, UWP, Win32 and custom UI control libraries which all behave differently. I don't get what doesn't work on the combobox in the example above. The problem was you just took the label (the control before the combobox). There is no way FlaUI can automatically assume that you wanted the combobox and not the label, so you had to fix the searching.
Fragility is also about clicks / invokes. Sometimes one works and the other not. I know that like toggle buttons in WPF do NOT fire any commands bound to the control when using invoke, you need to use click there. The whole UIA is full of bugs and FlaUI tries to fix those which are clear. It will always be a bit trial and error.
But if you do see improvement possibilities, I'm happy to take PRs or feature requests.

**Comment by Roemer** [comment]
Also the togglebutton has a select method. When using controls always first try what's on the control itself. I know, the wiki could have more information. Happy to take contributions there as well, it's open for anyone :)

**Comment by danhi** [comment]
Understood.  Now that I understand it, it won’t be a problem for me.

 

If I get some time I’ll create a test app with a lot of controls and a FlaUI that works with them.  If I get it done, I’ll see if you want to put it on your github.

 

Dan

**Comment by danhi** [comment]
And in case some other user runs into it, toolboxitems don’t have an automation id, you have to use the name.

**Comment by Roemer** [comment]
There is a FlaUI WPF and a WinForms Test App and some UI-Tests that test them, maybe you can extend them?
Regarding how to find items: You should always use an inspect tool like FlaUInspect.
