### ISSUE TITLE
void Textbox.Enter(String args) inverts capitalization if Caps Lock is ON

### ISSUE THREAD

**Issue by JoryAnderson** [Roemer/FlaUI#83]
The function somewhat emulates a keyboard, so if use "Sample Text" as a parameter, it will enter "sAMPLE tEXT" into the textbox.

**Comment by Roemer** [comment]
Haha yes it simulates real keyboard input.

**Comment by Roemer** [comment]
Same things probably happen if you press shift while flaui writes. Maybe other keys (alt, cmd) also do strange things?

**Comment by JoryAnderson** [comment]
Is that intentional?

**Comment by Roemer** [comment]
A side effect because I try to simulate keyboard input as good as possible.

**Comment by Roemer** [comment]
Maybe there needs to be an alternative which uses sendmessage instead of sendkeys.

**Comment by Roemer** [comment]
Just did a small improvement. It not unsets capslock (and re-sets it if needed) when using Type.
See: https://github.com/Roemer/FlaUI/commit/a886216ddbf9f23ec46c62704d7f54c5890ed87b
