### ISSUE TITLE
Click/Invoke on Janus UICommand not working

### ISSUE THREAD

**Issue by twenzel** [Roemer/FlaUI#84]
On a legacy WinForms application we're using [Janus Controls](http://www.janusys.com/). Unfortunately the `Invoke()` method does not work on their UICommand (menu item).

I've attached a sample application. Trying to invoke the 'Search\Tickets' menu item with following code

```
var app = Application.Launch("TestUIApp.exe");
using (var automation = new UIA3Automation())
{
	var window = app.GetMainWindow(automation);
	var menuBar = window.FindFirstDescendant(cf => cf.ByAutomationId("uiCommandBar1")).AsMenu();
	var searchItem = menuBar.FindFirstChild(cf => cf.ByName("Search")).AsMenu();
	var tickets = searchItem.FindFirstDescendant(cf => cf.ByName("Tickets")).AsMenuItem();
	tickets.Invoke();

	var ticketSearchWindow = window.FindFirstDescendant("ChildForm");
	var ticketIdEdit = ticketSearchWindow.FindFirstDescendant("28515994").AsTextBox();
	ticketIdEdit.Text = "80801";
}

app.Close();
```

[Debug.zip](https://github.com/Roemer/FlaUI/files/1251859/Debug.zip)

Is this a bug in FlaUI or are the JanusControl just not meant to be testable ;) ?

**Comment by Roemer** [comment]
Various things here:
The menu in Janus Controls seems not to be what you think :) Even thou there are the sub-menu items (Tickets) visible, the real item (when you open the menu by clicking "Search" sits directly on the desktop as a menu. I already have a hack for win32 menus which behave also differently (https://github.com/Roemer/FlaUI/blob/master/src/FlaUI.Core/AutomationElements/Menu.cs) but this one is different again.
What you can do is search on the desktop for the dropdown and for the Tickets menu item element.
Additionally, `Invoke` seems to "block", therefore you should probably use Click here.
See the following which seems to work:
```csharp
var app = Application.Launch(@"C:\Users\rbl\Downloads\Debug\TestUIApp.exe");
using (var automation = new UIA3Automation())
{
    var window = app.GetMainWindow(automation);
    var menuBar = window.FindFirstDescendant(cf => cf.ByAutomationId("uiCommandBar1")).AsMenu();
    var searchItem = menuBar.MenuItems["Search"];
    searchItem.Click();
    // Wait a bit for the animation
    System.Threading.Thread.Sleep(500);

    var dd = automation.GetDesktop().FindFirstChild(cf => cf.ByName("SearchDropDown"));
    var tickets = dd.FindFirstChild(cf => cf.ByName("Tickets")).AsMenuItem();
    tickets.Click();

    var ticketSearchWindow = window.FindFirstDescendant("ChildForm");
    var ticketIdEdit = ticketSearchWindow.FindFirstChild(cf => cf.ByControlType(ControlType.Edit)).AsTextBox();
    ticketIdEdit.Text = "80801";
}
app.Close();
```

**Comment by twenzel** [comment]
Thanks a lot.
