### ISSUE TITLE
It would be useful if the TreeItem class had a property for ExpandCollapseState

### ISSUE THREAD

**Issue by HyruleWarrior** [Roemer/FlaUI#87]
It would be much easier to get it from the class then to get it from the pattern. I think this is a pretty common property to be used for TreeItem. Right now I have to do something like "TreeItem.Patterns.ExpandCollapse?.Pattern.ExpandCollapseState" each time I want to get the value.

**Comment by Roemer** [comment]
Will be in the next release :) Btw, I always accept PRs for such things.

**Comment by HyruleWarrior** [comment]
Nice! I actually already did a quick version of it just to try it out. Maybe I will finish it and submit it before you add it.

**Comment by Roemer** [comment]
I already did :)
