### ISSUE TITLE
Can't get all elements when there are scroll bars

### ISSUE THREAD

**Issue by Davidacu** [Roemer/FlaUI#89]
Whenever  a vertical scroll bar is present, and I want to get all elements with the search methods provided in this library, I only get the elements that are visible, so to get more elements I need to scroll down and search again, is there a way I can get all elements without needing to make a new search for every time I scroll down?

**Comment by Roemer** [comment]
Do you mean in a Table/Grid or just the controls in a panel? Can you show a FlaUInspect screenshot showing some elements that only appear when scrolling?

**Comment by Davidacu** [comment]
Sorry I wasn't clear, 
So I have a custom control and that control is the view that contains a few buttons, and panels.
these panels contains more controls including the scroll bars, 
the panels I can detect with Inspect.exe are 13, which are the panels that are visible.
if I scroll down, then what happens is that those existing 13 panels are updated with new
information from the new visible controls.

So at the end these panels contains information about users, and what i want to do is save everything in a collection, but since the same panels elements are updated I need to save in memory the first 13 panels, then scroll down and save the rest until I reach the bottom.

**Comment by ivan-danilov** [comment]
That's UI virtualization mechanisms at work. WPF does not instantiate those invisible controls until they are scrolled to. And since controls don't exist - their AutomationPeers don't either.
One way to solve this is to turn off UI virtualization in your control... which is clearly not ideal since it really helps performance. Another is to use ItemContainerPattern, like this: https://blogs.msdn.microsoft.com/llobo/2009/11/16/new-wpf-features-uia-virtualization/

**Comment by Roemer** [comment]
Can you show a screenshot showing your custom control in an inspect tool? But I guess @ivan-danilov is right. You either need to turn UI virtualization off or use an appropriate pattern / automationpeer to get the items with that pattern.

**Comment by Davidacu** [comment]
Hi Guys, Thanks for replying, I believe @ivan-danilov is right, it makes perfect sense, however I'm not allowed to change the source code, so turning UI virtualization off is not an option, the second approach is still a little confusing for me, @Roemer  do you think you could show me an example on how to do it with FlaUI?

**Comment by Roemer** [comment]
The second approach also means changing the source code except if it already contains the needed patterns. Thats why I ask for a screenshot to see, what patterns are available :)

**Comment by Davidacu** [comment]
![inspect](https://user-images.githubusercontent.com/4731836/30392217-5ee4ae72-9879-11e7-8deb-05904034d77e.jpg)
ok, It looks like the pain that contains all of the controls does not have a lot patterns available, here's the screenshot.

**Comment by Roemer** [comment]
Can you show the patterns of the custom control which contains all the other controls?

**Comment by Davidacu** [comment]
the one that contains all the other panes?
this one?
![inspect2](https://user-images.githubusercontent.com/4731836/30396737-d8d7bc5c-9887-11e7-85ae-2ae1c780ee36.jpg)

**Comment by Roemer** [comment]
Yes thanks. Unfortunately there are not more patterns available. So unless you can modify the source code, you are stuck with scrolling.

**Comment by Roemer** [comment]
Can we close this as FlaUI cannot do anything more to help here and the workaround with scrolling is not pretty but works?

**Comment by Davidacu** [comment]
Yes, thanks a lot
