### ISSUE TITLE
How to handle datagridview

### ISSUE THREAD

**Issue by danhi** [Roemer/FlaUI#92]
I have a datagridview, and when I use VisualUIAVerify it shows up as a table, but there's no AsTable for FindFirstDescendant.  I tried using asGrid, but then I get property not supported for all the interesting items (row count, rows, ...).

How should I cast a datagridview?

**Comment by Roemer** [comment]
The DataGridView seems to support almost no patterns unfortunately. You might need to work with FindAllChildren to get the rows, columns and such. Could you post a screenshot from inspect/UIAVerify showing your datagridview?

**Comment by danhi** [comment]
Here it is.  You can see all the data is there, I just don't know how to access it.  Am I correct in that there isn't an .AsDataGridView option?
![flaui](https://user-images.githubusercontent.com/3358389/30492849-cb23fac4-99f6-11e7-97ed-be978ded27b1.JPG)

**Comment by Roemer** [comment]
The DataGridView pretty much does not support any patterns. So you need to use "Find..." almost everywhere.

I made a quick prototype how a DataGridView class could look like.

Can you test it with your DataGridView?

Here is to code:
```csharp
using System.Linq;
using FlaUI.Core.AutomationElements.Infrastructure;
using FlaUI.Core.Definitions;
using FlaUI.Core.Patterns;
using FlaUI.Core.Tools;

namespace FlaUI.Core.AutomationElements
{
    /// <summary>
    /// Class to interact with a WinForms DataGridView
    /// </summary>
    public class DataGridView : AutomationElement
    {
        public DataGridView(BasicAutomationElementBase basicAutomationElement) : base(basicAutomationElement)
        {
        }

        /// <summary>
        /// Flag to indicate if the grid has the "Add New Item" row or not.
        /// </summary>
        public bool HasAddRow { get; set; }

        public virtual DataGridViewHeader Header
        {
            get
            {
                var header = FindFirstChild(cf => cf.ByName(LocalizedStrings.DataGridViewHeader));
                return new DataGridViewHeader(header.BasicAutomationElement);
            }
        }

        public virtual DataGridViewRow[] Rows
        {
            get
            {
                var rows = FindAllChildren(cf => cf.ByControlType(ControlType.Custom).And(cf.ByName(LocalizedStrings.DataGridViewHeader).Not()));
                // Remove the last row if we have the "add" row
                if (HasAddRow)
                {
                    rows = rows.Take(rows.Length - 1).ToArray();
                }
                return rows.Select(x => new DataGridViewRow(x.BasicAutomationElement)).ToArray();
            }
        }
    }

    public class DataGridViewHeader : AutomationElement
    {
        public DataGridViewHeader(BasicAutomationElementBase basicAutomationElement) : base(basicAutomationElement)
        {
        }

        public DataGridViewHeaderItem[] Columns
        {
            get
            {
                var headerItems = FindAllChildren(cf => cf.ByControlType(ControlType.Header));
                var convertedHeaderItems = headerItems.Select(x => new DataGridViewHeaderItem(x.BasicAutomationElement))
                    .ToList();
                // Remove the top-left header item if it exists (can be the first or last item)
                if (convertedHeaderItems.Last().Text == LocalizedStrings.DataGridViewHeaderItemTopLeft)
                {
                    convertedHeaderItems = convertedHeaderItems.Take(convertedHeaderItems.Count - 1).ToList();
                }
                else if (convertedHeaderItems.First().Text == LocalizedStrings.DataGridViewHeaderItemTopLeft)
                {
                    convertedHeaderItems = convertedHeaderItems.Skip(1).ToList();
                }
                return convertedHeaderItems.ToArray();
            }
        }
    }

    public class DataGridViewHeaderItem : AutomationElement
    {
        public DataGridViewHeaderItem(BasicAutomationElementBase basicAutomationElement) : base(basicAutomationElement)
        {
        }

        public string Text => Properties.Name.Value;
    }

    public class DataGridViewRow : AutomationElement
    {
        public DataGridViewRow(BasicAutomationElementBase basicAutomationElement) : base(basicAutomationElement)
        {
        }

        public DataGridViewCell[] Cells
        {
            get
            {
                var cells = FindAllChildren(cf => cf.ByControlType(ControlType.Header).Not());
                return cells.Select(x => new DataGridViewCell(x.BasicAutomationElement)).ToArray();
            }
        }
    }

    public class DataGridViewCell : AutomationElement
    {
        public DataGridViewCell(BasicAutomationElementBase basicAutomationElement) : base(basicAutomationElement)
        {
        }

        protected IValuePattern ValuePattern => Patterns.Value.Pattern;

        public string Value
        {
            get => ValuePattern.Value.Value;
            set => ValuePattern.SetValue(value);
        }
    }
}
```
just use it like:
```csharp
var dataGridView = new DataGridView(yourFoundElement.BasicAutomationElement);
```
and then access the properties like Header, Rows and in Rows->Cells and such.
Hope to hear from you so I could improve it a bit more and add it to FlaUI directly.

**Comment by Roemer** [comment]
Ah you're probably missing the LocalizedStrings values. You can hard code them like:
```csharp
DataGridViewHeader = "Top Row";
DataGridViewHeaderItemTopLeft = "Top Left Header Cell";
```

**Comment by Roemer** [comment]
I actually added it to the code (with a bit more comments). See https://github.com/Roemer/FlaUI/commit/8eef349ea8ad42f5058b7fabd1a2a4bc49771e9d
Can you try it and give me feedback?

**Comment by danhi** [comment]
I haven’t gotten around to installing the latest version of Visual Studio, so I can’t build the project.  The only binaries I could find in the new source tree were the two interop files, not the uia3.dll, which is where I suspect the new asdatagridview is.  If I can get these from you’ll I’ll jump on testing it out.

**Comment by Roemer** [comment]
You can get pre release nuget packages on appveyor: https://ci.appveyor.com/project/RomanBaeriswyl/flaui/build/artifacts
Just add them or unzip them and use the dlls.

**Comment by danhi** [comment]
Sorry for being a nuget newbi, but …

 

I’m using the windows command line nuget.  I added appveyor to sources,

 

nuget sources

Registered Sources:

 

  1.  nuget.org [Enabled]

      https://api.nuget.org/v3/index.json

  2.  appveyor [Enabled]

      https://ci.appveyor.com

 

then downloaded the nupkg package, used nuget install <pkg name> and I get the error:

 

An error occurred while retrieving package metadata for 'flaui.uia2.1.3.0-dev.nupkg' from source 'appveyor'.

  'doctype' is an unexpected token. The expected token is 'DOCTYPE'. Line 1, position 3.

 

Can you tell me what I’m doing wrong?

**Comment by Roemer** [comment]
That's not at all how this works. Appveyor is not a nuget feed.
Either you download the nuget from there to a local folder and add the local folder to the nuget feeds or you unzip the nuget package and just use the dlls somewhere in ther directly as references in your project.

**Comment by danhi** [comment]
Sorry, didn’t understand that.  I’ve got them now and will test them today.

 

Thanks for the great support.

 

Dan

**Comment by danhi** [comment]
OK, got that going and it appears to work (I’ll do some more testing today) but now ScreenCapture doesn’t appear to be defined.  Is this gone or just moved somewhere?

**Comment by Roemer** [comment]
Its called Capture now.

**Comment by danhi** [comment]
Tested out the Capture and the new DataGridView.  Both are working great.

 

Thanks,

 

Dan

**Comment by Roemer** [comment]
Cool so I'll close this. You can re-open it or create a new issue if needed.

**Comment by danhi** [comment]
I’m not sure if this is possible, but capture doesn’t seem to capture relative to the window, but the screen?  When I’m debugging, if the debugging screen is on top of the app that I’m controlling, I get the capture of the debugging screen.  Obviously not a major issue, but make debugging a little harder, and makes it non-deterministic on a run if some window pops up on top during the run.

**Comment by danhi** [comment]
I need to be able to scroll down in a listbox.  I don’t see a member function in listbox that does anything like that, and when I use Key.Press or Key.PressVirtualKey, I don’t find an element for scroll down (I tried Key.PageDown, but that didn’t seem to work with PressVirtualKey).  Then I thought I could get the scrollbar byFindFirstChild(Function(cf) cf.ByControlType(Definitions.ControlType.ScrollBar)).AsScrollbar, but there isn’t a AsScrollbar.

 

Anyway, is there a way to accomplish scrolling down in a listbox?

**Comment by Roemer** [comment]
For the Scrollbar: there is a ToHScrollBar and ToVScrollBar in the old version and a ToHorizontalScrollBar and ToVerticalScrollBar in the current build.
About the Capture, I will investigate. Can you in the future create new issues for each thing you encounter?

**Comment by danhi** [comment]
I will open issues from now on.  Didn’t know if you wanted questions opened as issues.  Do you want me to open an issue on Capture?

 

Where do I find the ToVerticalScrollBar function?  I can’t find it on any of the UI elements.

**Comment by danhi** [comment]
I did find a workaround for the vertical scrollbar issue:

 

        ' this is a workaround, hopefully there's a better way

        For Each uii As AutomationElements.Infrastructure.AutomationElement In uie.lv.FindAllDescendants()

            If uii.Properties.AutomationId.ToString = "Vertical ScrollBar" Then

                scrollDown = uii.FindFirstChild(Function(cf) cf.ByAutomationId("LargeIncrement")).AsButton

                Exit For

            End If

        Next

 

Then I can call scrollDown.invoke and it scrolls down.  Still hoping for a better way, but this works.

 

Dan

**Comment by Roemer** [comment]
Yes please open an issue for the Capture.

For the Scrollbar:
You can use the AsHorizontalScrollBar and AsVerticalScrollBar to get a scrollbar elements which already provide you with the buttons and scrolling abilities. Also to find it, there is a Horizontal-/VerticalScrollBar method in the ConditionFactory which already provides you with the condition for a Scrollbar.
Use it like: ```FindXXX(cf=>cf.HorizontalScrollBar))```

**Comment by danhi** [comment]
Clearly my brain is turning to mush.  I really thought I had tried AsVerticalScrollBar.

But now that I see it, when I try:

        scrollBar = uie.lv.FindFirstDescendant(Function(cf) cf.VerticalScrollBar).AsVerticalScrollBar()
        scrollBar.ScrollDown()

I get a horizontal scroll, not a vertical one.

**Comment by Roemer** [comment]
Yikes. The search condition for the scrollbars was an "or" instead of an "and". Fixed that. For ther other issues, you created separate ones so I will close this unless you have further problems :)

**Comment by danhi** [comment]
Nope, I’ll check it out today and let you know if I have another issue.
