### ISSUE TITLE
focus before click

### ISSUE THREAD

**Issue by apobekiaris** [Roemer/FlaUI#93]
Hi

My app takes a long time to start so it is not possible to run it on each test. So I got my checkbox and tried to toggle it. This focused my app, however when try to click it fails as my app did not had the focus, is there a way to focus ?

**Comment by Roemer** [comment]
There are several methods available you can try:

- SetForeground
- FocusNative
- Focus

**Comment by apobekiaris** [comment]
i must be blind thnks!

However this 

`            using (var automation = new UIA3Automation()) {
                using (var application = FlaUI.Core.Application.Attach(process)) {
                    var mainWindow = application.GetMainWindow(automation);
                    mainWindow.SetForeground();`

fails to bring the mainwindow into foreground. Do I miss anything?

**Comment by Roemer** [comment]
Is your `mainWindow` minimized?

**Comment by Roemer** [comment]
Closed due to inactivity. Please re-open if the problem still exists.
