### ISSUE TITLE
Update NuGet packages

### ISSUE THREAD

**Issue by HyruleWarrior** [Roemer/FlaUI#95]
How often will NuGet packages be updated? There are a lot of recent changes that would be nice to be able to grab from there. For now I am just building the project and using those dlls, but pushing the newer stuff with NuGet would be nice.

**Comment by Roemer** [comment]
Yes that is planned fairly soon. I need to run some more tests and then I will release the new version. I'm on vacation currently so it won't be this and probably also not next week.
