### ISSUE TITLE
Have Capture be window relative, not screen relative

### ISSUE THREAD

**Issue by danhi** [Roemer/FlaUI#97]
Right now capture appears to capture based on the screen coordinates, not window coordinates.  This has the unwelcome side effect of capturing a different window if the app under test isn't on top (which can happen if another app gets triggered by some event).  If capture could work based on the window under test, it would be more consistent.

**Comment by Roemer** [comment]
Do you mean the `Rectangle` Method?

**Comment by danhi** [comment]
Yes:

bm = FlaUI.Core.Capture.Rectangle(rc)

**Comment by Roemer** [comment]
How about having an overload where you can pass an AutomationElement (e.g. a Window) as "Reference point"?

**Comment by danhi** [comment]
That would work as long as that caused it to ignore a window that was on top of the targeted window.

**Comment by Roemer** [comment]
How about bringing the element to the front when one is given?

**Comment by danhi** [comment]
Yep, that would work.  As long as it's on top when the capture.rectangle is done, that solves the problem.

**Comment by Roemer** [comment]
I just reworked the Capture class. Please have a look at the current master and check if that fullfills your needs.

**Comment by danhi** [comment]
So where can I download the binaries with the changes?  I still haven’t gotten around to being able to build FlaUI yet.

**Comment by Roemer** [comment]
Still from the CI:
https://ci.appveyor.com/project/RomanBaeriswyl/flaui/build/artifacts

**Comment by danhi** [comment]
Well, nothing good.  First the capture works the same, if I'm in the debugger when the capture happens, I get the image from the debugger.

Second I tried the fix for VerticalScrollBar.  With the change, I can't even get the vertical scrollbar anymore.  I tried the following (the first is what I was using before that worked to get it, it just scrolled the wrong way).

        ae = uie.lv.FindFirstDescendant(Function(cf) cf.VerticalScrollBar)
        ae = uie.lv.FindFirstDescendant(Function(cf) cf.ByAutomationId("NonClientVerticalScrollBar"))
        ae = uie.lv.FindFirstDescendant(Function(cf) cf.ByName("Vertical"))

**Comment by Roemer** [comment]
To capture: If your debugger window obscures the window it should capture, then you'll see the content of the debugger of course. Maybe some sleeps around the capture will work in that case.

You could find the scrollbar before because it searched by ControlType.ScrollBar OR by Name, now it searches for both.
Can you give me an inspect screenshot showing the scrollbar? You probably have another name I haven't yet.

**Comment by danhi** [comment]
![capture](https://user-images.githubusercontent.com/3358389/31237135-e23d32ca-a9aa-11e7-8388-7a9873b70f3e.JPG)
Here it is.  So I should have two cf's, one for type and one for name?

**Comment by Roemer** [comment]
Is it clear now and working regarding Capture?

I have added some more logic to find scrollbars. Can you try again with the latest build?

**Comment by danhi** [comment]
The vertical scrollbar is working perfectly now.

I understand about the capture, it's not normally an issue, just when I'm debugging and I can work around that.  Just thought it would be nice if there was a capture that was window specific, not desktop specific.  But I can work with what's there.
