### ISSUE TITLE
Return null for Findxxx that doesn't find the element instead of raising exception

### ISSUE THREAD

**Issue by danhi** [Roemer/FlaUI#98]
Sometimes (like looking for a scrollbar) you don't know for sure that a UI element exists.  Right now Findxxx raises an exception when it doesn't find something.  It would be nice if it would just return null, so it wouldn't be necessary to wrap Findxxx calls in a try.

**Comment by Roemer** [comment]
What kind of exception do you get?

**Comment by danhi** [comment]
System.NullReferenceException.  It's pretty easy to recreate, just search with

.FindFirstDescendant(Function(cf) cf.ByAutomationId("foobar")).AsTextBox

on a window.

**Comment by Roemer** [comment]
The problem is the `.AsTextBox`. You should use `?.AsTextBox`

**Comment by danhi** [comment]
Ahhh, I see.  I'll have to think about how best to encapsulate this to detect the null.

**Comment by Roemer** [comment]
Exactly :)
